<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Admin\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Admin\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang="en" <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir='rtl'" : '' ?>>
<head>
    <title><lang>WelineFramework开发文档</lang></title>
    <hook>title</hook>
    <!--模板Weline_DeveloperWorkspace::common/head.phtml-->
    <template>Weline_Frontend::public/head.phtml</template>
    <!-- jvectormap -->
    <css>Weline_Frontend::assets/libs/jqvmap/jqvmap.min.css</css>
    <!--树形插件-->
    <css>Weline_Frontend::/libs/bootstrap-treeview-master/dist/bootstrap-treeview.min.css</css>
    <js a="1">Weline_Frontend::/libs/bootstrap-treeview-master/dist/bootstrap-treeview.min.js</js>
    <!--测试-->
    @js(Weline_Frontend::/libs/bootstrap-treeview-master/dist/bootstrap-treeview.min.js)
</head>

<body <?= $themeConfig->getLayouts() ?? ''; ?>>
<!--加载中组件 开始-->
@template(Weline_DeveloperWorkspace::common/page/loading.phtml)
<!-- 开始 页面 -->
<div id="layout-wrapper">

    <!--页头工具条 开始-->
    @template(Weline_DeveloperWorkspace::common/page/topbar.phtml)
    <!--页头工具条 结束-->

    <!-- ========== Left Sidebar Start ========== -->
    <!--左侧菜单栏 开始-->
    <block>Weline\DeveloperWorkspace\Block\Catalogs</block>
    <!--左侧菜单栏 结束-->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">
        <div class="page-content" style="min-height: 800px">
            <div class="container-fluid">
                <div class='row'>
                    <h4 class='card-title'>
                        <lang>开发文档->目录分类管理</lang>
                    </h4>
                    <p class='card-title-desc'>
                        <lang>开发文档目录分类管理</lang>
                    </p>
                    <div class="col-12">
                        <div class='card'>
                            <div class='card-body'>
                                <button type='button'
                                        onclick='window.location.href="@url('dev/tool/admin/document')"'
                                        class='btn btn-dark waves-effect waves-light pull-right '>
                                    <lang>返回</lang>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class='col-6'>
                        <!--消息-->
                        <template>Weline_Component::message.phtml</template>
                        <div class='card'>
                            <div class='card-body'>
                                <div class="panel">
                                    <h4>
                                        <lang>新建分类</lang>
                                    </h4>
                                    <form class='needs-validation' method='post'
                                          action='@url("dev/tool/admin/document/catalog/post")' novalidate>
                                        <div class='row col'>
                                            <div class='col-6 pull-left'>

                                            </div>
                                            <div class='col-6 pull-right button-items'>
                                                <button type='submit'
                                                        class='btn btn-primary waves-effect waves-light pull-right'>
                                                    <lang>保存</lang>
                                                </button>
                                            </div>
                                        </div>
                                        <div class='row'>
                                            <div class='col-md-6'>
                                                <div class='mb-3 position-relative'>
                                                    <label class='form-label' for='name'>
                                                        <lang>目录名</lang>
                                                    </label>
                                                    <input type='text' name='name' class='form-control' id='name'
                                                           placeholder='@lang(目录名)' required>
                                                    <div class='valid-feedback'>
                                                        <lang>请输入目录名</lang>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class='col-md-3'>
                                                <div class='mb-3 position-relative'>
                                                    <label class='form-label'
                                                           for='pid'>
                                                        <lang>父级分类</lang>
                                                    </label>
                                                    <div class='input-group'>
                                                        <div class='input-group-prepend'>
                                                        <span class='input-group-text'
                                                              id='pid-prepend'>@</span>
                                                        </div>
                                                        <select name='pid' class='form-control'
                                                                id='pid'
                                                                aria-describedby='pid-prepend' required>
                                                            <option value="0-0">
                                                                <lang>请选择</lang>
                                                            </option>
                                                            <foreach name="catalogs" item="v">
                                                                <option value="@var{$v->getId()}-@var{$v->getLevel()}">
                                                                    <var>$v->getName()</var>
                                                                </option>
                                                            </foreach>
                                                            <if condition="$a>$b">
                                                                <var a="1">$a</var>
                                                                <elseif condition="$a<$b"/>
                                                                <var>$b</var>
                                                                <else/>
                                                                <var>$a</var>
                                                                <var>$b</var>
                                                            </if>
                                                        </select>
                                                        <div class='valid-feedback'>
                                                            <lang>请选择父级分类</lang>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class='row col'>
                                            <div class='col-6 pull-left'>

                                            </div>
                                            <div class='col-6 pull-right button-items'>
                                                <button type='submit'
                                                        class='btn btn-primary waves-effect waves-light pull-right'>
                                                    <lang>保存</lang>
                                                </button>
                                                <button type='button'
                                                        onclick='window.location.href="@url('dev/tool/admin/document')"'
                                                        class='btn btn-default waves-effect waves-light pull-right '>
                                                    <lang>返回</lang>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div> <!-- end col -->
                    <div class='col-6'>
                        <div class='card'>
                            <div class='card-body'>
                                <div class="panel">
                                    <h4>分类管理</h4>
                                    <div id="catalog-tree">
                                    </div>
                                    <script>
                                        function renderTree() {
                                            $.get({
                                                url: '@admin-url("dev/tool/admin/document/catalog/tree")',
                                            }).done(res => {
                                                console.log(res)
                                                $('#catalog-tree').treeview({
                                                    data: res,
                                                    enableLinks: true,
                                                    expandIcon: 'glyphicon glyphicon-plus'
                                                });
                                            })
                                        }

                                        renderTree();
                                    </script>
                                </div>
                            </div>
                        </div>
                    </div> <!-- end col -->

                </div> <!-- end row -->
            </div>
            <!-- container-fluid -->
        </div>
        <!-- End Page-content -->

        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <script>document.write(new Date().getFullYear())</script>
                        © Weline.
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end d-none d-sm-block">
                            Crafted with <i class="mdi mdi-heart text-danger"></i> By <a
                                    href="https://www.aiweline.com/">秋枫雁飞(aiweline)</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>
    <!-- end main content-->


</div>
<!-- END layout-wrapper -->

<!--右边栏-->
@template(Weline_DeveloperWorkspace::common/right-sidebar.phtml)
<!--tinymce js-->
<script src='@static(Weline_Frontend::assets/libs/tinymce/tinymce.min.js)'></script>

<!-- init js -->
<script src='@static(Weline_Frontend::assets/js/pages/form-editor.init.js)'></script>

<!--页脚-->
@template(Weline_DeveloperWorkspace::common/footer.phtml)

<!-- jquery.vectormap map -->
<script src="@static(Weline_Frontend::assets/libs/jqvmap/jquery.vmap.min.js)"></script>
<script src="@static(Weline_Frontend::assets/libs/jqvmap/maps/jquery.vmap.usa.js)"></script>
</body>
</html>

