<!--
===================================================================================================================== 
模板文件：E:\WelineFramework\DEV-workspace\app\code\Weline\Eav\view\templates\Backend\Attribute\form.phtml START
=====================================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang='en' <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    <!--
================================================================================================================= 
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\templates\common\head.phtml START
=================================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<meta charset="UTF-8">
<title><?php echo $this->getData('title'); ?></title>
<!--元数据-->
<meta content="<?php echo $this->getData('description'); ?>" name="description"/>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, shrink-to-fit=no'>
<meta content="<?php echo $this->getData('title'); ?>" name='author'/>
<meta content="<?php echo $this->getData('description'); ?>" name='description'/>
<link rel="Shortcut Icon" href="/weline/module-backend/view/statics/img/favicon.png?v=92912">
<link rel="Shortcut Icon" href="/weline/module-backend/view/statics/img/favicon.png?v=92912">
<link rel="Bookmark" href="/weline/module-backend/view/statics/img/favicon.png?v=92912">
<!--加载requirejs-->
<?php if (DEV) : ?>
    <!--        <script src="/weline/module-backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.js?v=34295"></script>-->
<?php
else:
    ?>
    <!--        <script src="/weline/module-backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.min.js?v=40627"></script>-->
<?php
endif;
?>
<!--加载require常用js模块-->
<!--<script src="/weline/module-backend/view/statics/base/require.configs.js?v=45421"></script>-->
<?php echo framework_view_process_block([
    'class' => 'Weline\\Backend\\Block\\Header\\Base',
    'template' => 'Weline_Admin::header/base.phtml',
]);?>

<!--css-->
<!--loading-->
<link  href='/weline/module-admin/view/statics/libs/loading/loading.css?v=53857' rel="stylesheet" type="text/css"/>
<link  href='/weline/module-admin/view/statics/backend/lib/bootstrap-5.1.3-dist/css/bootstrap.min.css?v=14718' rel="stylesheet" type="text/css"/>
<link  href='/weline/module-admin/view/statics/backend/lib/font-awesome-4.7.0/css/font-awesome.min.css?v=19447' rel="stylesheet" type="text/css"/>
<!-- Bootstrap Css -->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/bootstrap' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet"
      type="text/css"/>
<!-- Icons Css -->
<link  href='/weline/module-admin/view/statics/assets/css/icons.min.css?v=95962' rel="stylesheet" type="text/css"/>
<!-- App Css-->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/app' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet" type="text/css"/>
<!--JS-->
<script  src='/weline/module-backend/view/statics/backend/lib/jquery/3.6.0/jquery.js?v=99826'></script>
<?php if (DEV): ?>
<!--        <script src="/weline/module-backend/view/statics/backend/lib/jquery/3.6.0/jquery.map?v=81791"></script>-->
<?php endif; ?>
<!--加载配置页头-->
<?php
echo $this->getHeader()->getHtml();
?>

<!--
===================================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\tpl\\zh_Hans_CN\templates\common\com_head.phtml END
===================================================================================================================================
-->
    <title><?= __('Weline Admin 管理面板') ?></title>
    <!-- twitter-bootstrap-wizard css -->
    <link rel='stylesheet' href='/weline/module-admin/view/statics/assets/libs/twitter-bootstrap-wizard/prettify.css?v=49156'>
    <!-- Sweet Alert-->
    <link href='/weline/module-admin/view/statics/assets/libs/sweetalert2/sweetalert2.min.css?v=68150' rel='stylesheet' type='text/css'/>
</head>

<body <?= $themeConfig->getLayouts() ?? ''; ?> class='bg-transparent'>

<!--页头工具条 开始-->
<!--
========================================================================================================================= 
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\templates\common\page\loading.phtml START
=========================================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<!--Loading-->
<section id="loading">
    <div class='loader loader-1'>
        <div class='loader-outter'></div>
        <div class='loader-inner'></div>
    </div>
</section>
<script>
    function showLoading() {
        $('#loading').show()
    }

    function hideLoading() {
        $('#loading').hide()
    }

    $(function () {
        $('#loading').hide()
    })
</script>
<!--
===========================================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\tpl\\zh_Hans_CN\templates\common\page\com_loading.phtml END
===========================================================================================================================================
-->
<!--页头工具条 结束-->

<!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- 开始 页面 -->
<div id="layout-wrapper">
    <!-- start page message -->
    <div class='row'>
        <!--
================================================================================================================= 
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-component\view\templates\message.phtml START
=================================================================================================================
 -->
<?php
echo \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Framework\Manager\MessageManager::class);
?>
<!--
===================================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-component\view\tpl\\zh_Hans_CN\templates\com_message.phtml END
===================================================================================================================================
-->
    </div> <!-- end message -->
    <div class='row'>
        <div class='col-lg-12'>
            <div class='card'>
                <div class='card-body'>
                    <div id='progress-wizard' class='twitter-bs-wizard'>
                        <ul class='twitter-bs-wizard-nav nav-justified'>
                            <li class='nav-item'>
                                <a href='#progress-select-entity'
                                   data-target="<?php if($progress === 'progress-select-entity' ):echo '1'; else: echo '0'; endif;?>"
                                   class='nav-link'
                                   data-progress="<?=$progress ;?>"
                                   data-toggle='tab'>
                                    <span class='step-number'>01</span>
                                    <span class='step-title'>选择实体</span>
                                    <?php if(!empty($eav_entity ) ): ?>
                                        <span class="help-block">
                                            你选择了
                                            <span class="text-primary"><?=($eav_entity['name']??'') ;?></span>
                                        </span>
                                    <?php endif; ?>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='#progress-select-set'
                                   data-target="<?php if($progress === 'progress-select-set' ):echo '1'; else: echo '0'; endif;?>"
                                   class='nav-link'
                                   data-progress='<?=$progress ;?>'
                                   data-toggle='tab'>
                                    <span class='step-number'>02</span>
                                    <span class='step-title'>选择属性集</span>
                                    <?php if(!empty($eav_entity_attribute_set ) ): ?>
                                        <span class='help-block'>
                                            你选择了
                                            <span class='text-primary'><?=($eav_entity_attribute_set['name']??'') ;?></span>
                                        </span>
                                    <?php endif; ?>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='#progress-select-group'
                                   data-target="<?php if($progress === 'progress-select-group' ):echo '1'; else: echo '0'; endif;?>"
                                   class='nav-link'
                                   data-progress='<?=$progress ;?>'
                                   data-toggle='tab'>
                                    <span class='step-number'>03</span>
                                    <span class='step-title'>选择属性组</span>
                                    <?php if(!empty($eav_entity_attribute_set_group ) ): ?>
                                        <span class='help-block'>
                                            你选择了
                                            <span class='text-primary'><?=($eav_entity_attribute_set_group['name']??'') ;?></span>
                                        </span>
                                    <?php endif; ?>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='#progress-attribute-details'
                                   data-target="<?php if($progress === 'progress-attribute-details' ):echo '1'; else: echo '0'; endif;?>"
                                   class='nav-link'
                                   data-progress='<?=$progress ;?>'
                                   data-toggle='tab'>
                                    <span class='step-number'>04</span>
                                    <span class='step-title'>创建属性</span>
                                    <?php if(!empty($attribute ) ): ?>
                                        <span class='help-block'>
                                            你创建了
                                            <span class='text-primary'><?=($attribute['name']??'') ;?>（<?=($attribute['code']??'') ;?>）</span>
                                        </span>
                                    <?php endif; ?>
                                </a>
                            </li>
                            <!--如果有配置属性配置项-->
                            <?php if(!empty(($attribute['has_option']??'') ) ): ?>
                                <li class='nav-item'>
                                    <a href='#progress-attribute-option'
                                       class='nav-link <?php if($progress === "progress-attribute-option" ):echo "active";endif;?>' data-toggle='tab'>
                                        <span class='step-number'>05</span>
                                        <span class='step-title'>配置项</span>
                                    </a>
                                </li>
                            <?php endif; ?>
                        </ul>

                        <div id='bar' class='progress mt-5'>
                            <div class='progress-bar bg-success progress-bar-striped progress-bar-animated'></div>
                        </div>
                        <div class='tab-content twitter-bs-wizard-tab-content'>
                            <div class='tab-pane' id='progress-select-entity'>
                                <form action="<?=$action ;?>" method="post">
                                    <input type='hidden' name='selected' value='<?php if(!empty($eav_entity )):echo 1; else: echo 0; endif;?>'>
                                    <input type="hidden" name="progress" value="progress-select-entity">
                                    <input type="hidden" name="next_progress" value="progress-select-set">
                                    <div class="row">
                                        <div class="mx-auto col-lg-6 mt-2 mb-4">
                                            <div class='input-group'>
                                                <input type='search' class='form-control rounded' id='search-entity'
                                                       placeholder='请输入要查找的实体名或者实体代码'
                                                       aria-label='请输入要查找的实体名或者实体代码'
                                                       aria-describedby='search-addon'/>
                                                <button type='button' class='btn btn-outline-primary'
                                                        onclick='renderSearchEntities(event)'>
                                                    搜索实体
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class='mx-auto col-lg-6 mt-2 mb-4'>
                                            <div class='input-group'>
                                                <select id='search-entity-result' class='form-select form-control rounded'
                                                        size="10"
                                                        name="entity_code"
                                                        data-style='btn-primary' data-width='fit'
                                                        aria-label='搜索实体结果'
                                                        aria-describedby='search-addon' required>
                                                    <?php foreach($entities  as $v):?>
                                                        <option value='<?=($v['code']??'') ;?>' <?php if(($eav_entity['code']??'') === ($v['code']??'') ):echo 'selected';endif;?>>
                                                            <?=($v['name']??'') ;?>
                                                        </option>
                                                    <?php endforeach;?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class='tab-pane' id='progress-select-set'>
                                <div>
                                    <form action="<?=$action ;?>" method="post">
                                        <input type='hidden' name='selected' value='<?php if(!empty($eav_entity_attribute_set )):echo 1; else: echo 0; endif;?>'>
                                        <input type='hidden' name='progress' value='progress-select-set'>
                                        <input type='hidden' name='next_progress' value='progress-select-group'>
                                        <div class='row'>
                                            <div class='mx-auto col-lg-6 mt-2 mb-4'>
                                                <div class='input-group'>
                                                    <input type='search' class='form-control rounded' id='search-entity-attribute-set'
                                                           placeholder='请输入要查找的 属性集名 或者 属性集代码'
                                                           aria-label='请输入要查找的 属性集名或者 属性集代码'
                                                           aria-describedby='search-addon'/>
                                                    <button type='button' class='btn btn-outline-primary' id="renderSearchEntityAttributeSetButton"
                                                            onclick='renderSearchEntityAttributeSet(event)'>
                                                        搜索 <?=($eav_entity['name']??'') ;?> 属性集
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class='row'>
                                            <div class='mx-auto col-lg-6 mt-2 mb-4'>
                                                <div class='input-group'>
                                                    <select id='search-entity-attribute-set-result' class='form-select form-control rounded'
                                                            size='10'
                                                            name='set_code'
                                                            data-style='btn-primary' data-width='fit'
                                                            aria-label='搜索 属性集 结果'
                                                            aria-describedby='search-addon' required>
                                                        <?php foreach($sets  as $v):?>
                                                            <option value='<?=($v['code']??'') ;?>' <?php if(($eav_entity_attribute_set['code']??'') === ($v['code']??'') ):echo 'selected';endif;?>>
                                                                <?=($v['name']??'') ;?>
                                                            </option>
                                                        <?php endforeach;?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class='tab-pane' id='progress-select-group'>
                                <div>
                                    <form action="<?=$action ;?>" method="post">
                                        <input type='hidden' name='selected' value='<?php if(!empty($eav_entity_attribute_set_group )):echo 1; else: echo 0; endif;?>'>
                                        <input type='hidden' name='progress' value='progress-select-group'>
                                        <input type='hidden' name='next_progress' value='progress-attribute-details'>
                                        <div class='row'>
                                            <div class='mx-auto col-lg-6 mt-2 mb-4'>
                                                <div class='input-group'>
                                                    <input type='search' class='form-control rounded' id='search-entity-attribute-set-group'
                                                           placeholder='请输入要查找的【实体-属性集-属性组】名或者【实体-属性集-属性组】代码'
                                                           aria-label='请输入要查找的【实体-属性集-属性组】名或者【实体-属性集-属性组】代码'
                                                           aria-describedby='search-addon'/>
                                                    <button type='button' class='btn btn-outline-primary'
                                                            id="renderSearchEntityAttributeSetGroupButton"
                                                            onclick='renderSearchEntityAttributeSetGroup(event)'>
                                                        搜索【实体-属性集-属性组】
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class='row'>
                                            <div class='mx-auto col-lg-6 mt-2 mb-4'>
                                                <div class='input-group'>
                                                    <select id='search-entity-attribute-set-group-result' class='form-select form-control rounded'
                                                            size='10'
                                                            name='group_code'
                                                            data-style='btn-primary' data-width='fit'
                                                            aria-label='搜索【实体-属性集-属性组】结果'
                                                            aria-describedby='search-addon' required>
                                                        <?php foreach($groups  as $v):?>
                                                            <option value='<?=($v['code']??'') ;?>' <?php if(($eav_entity_attribute_set_group['code']??'') === ($v['code']??'') ):echo 'selected';endif;?>>
                                                                <?=($v['name']??'') ;?>
                                                            </option>
                                                        <?php endforeach;?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class='tab-pane' id='progress-attribute-details'>
                                <form class='needs-validation' novalidate='' action='<?=$action ;?>' method='post'>
                                    <input type='hidden' name='selected' value='<?php if(($attribute['has_option']??'') ):echo 1; else: echo 0; endif;?>'>
                                    <input type='hidden' name='progress' value="progress-attribute-details">
                                    <input type='hidden' name='next_progress' value="<?php if(($attribute['has_option']??'') === '1' ):echo 'progress-attribute-option'; else: echo 'progress_submit'; endif;?>">
                                    <div class='row'>
                                        <div class='col-lg-6'>
                                            <div class='mb-3'>
                                                <label class='form-label' for='progress-attribute-code'>
                                                    属性代码
                                                </label>
                                                <input type='text' class='form-control' id='progress-attribute-code'
                                                       name="code" value="<?=($attribute['code']??'') ;?>"
                                                       maxlength='60' data-parsley-minlength='3' placeholder="属性代码" required>
                                                <div class='valid-feedback'>
                                                    填写正确！
                                                </div>
                                                <div class='valid-feedback'>
                                                    请正确填写正确属性代码，最小长度3个字符，最大长度60个字符
                                                </div>
                                            </div>
                                        </div>
                                        <div class='col-lg-6'>
                                            <div class='mb-3'>
                                                <label class='form-label' for='progress-attribute-name'>
                                                    属性名
                                                </label>
                                                <input type='text' class='form-control' id='progress-attribute-name' name='name'
                                                       value="<?=($attribute['name']??'') ;?>"
                                                       maxlength='128' data-parsley-minlength='3' placeholder='属性名' required>
                                                <div class='valid-feedback'>
                                                    填写正确！
                                                </div>
                                                <div class='valid-feedback'>
                                                    请正确填写正确属性代码，最小长度3个字符，最大长度128个字符
                                                </div>
                                            </div>
                                        </div>
                                        <div class='col-lg-6'>
                                            <div class='mb-3'>
                                                <label class='form-label' for='validationType'>
                                                    属性类型
                                                </label>
                                                <select class='form-control' id='validationType' name='type' required='' <?php if(($attribute['attribute_id']??'') ):echo 'disabled';endif;?>>
                                                    <?php foreach($types  as $type):?>
                                                        <option value='<?=($type['code']??'') ;?>' <?php if(($attribute['type']??'') == ($type['code']??'') ):echo 'selected';endif;?>>
                                                            <?=($type['name']??'') ;?>
                                                        </option>
                                                    <?php endforeach;?>
                                                </select>
                                                <div class='invalid-feedback'>
                                                    必须选择一个类型
                                                </div>
                                            </div>
                                        </div>
                                        <div class='col-lg-6'>
                                            <div class='mb-3'>
                                                <label class='form-label' for='validationEnable'>
                                                    是否启用
                                                </label>
                                                <select class='form-control' id='validationEnable' required=''
                                                        name='is_enable'>
                                                    <option value='0'
                                                            <?php if(($attribute['is_enable']??'') == 0 ):echo 'selected';endif;?>>
                                                        禁用
                                                    </option>
                                                    <option value='1'
                                                            <?php if(($attribute['is_enable']??'') == 1 ):echo 'selected';endif;?>>
                                                        启用
                                                    </option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class='col-lg-12'>
                                            <!--高级信息-->
                                            <div class='accordion mb-3' id='accordionAdvanced'>
                                                <div class='accordion-item'>
                                                    <h2 class='accordion-header' id='headingOne'>
                                                        <button class='accordion-button' type='button' data-bs-toggle='collapse'
                                                                data-bs-target='#collapseAdvanced'
                                                                aria-expanded='true' aria-controls='collapseAdvanced'>
                                                            高级设置
                                                        </button>
                                                    </h2>
                                                    <div id='collapseAdvanced' class='accordion-collapse collapse show'
                                                         aria-labelledby='headingAdvanced'
                                                         data-bs-parent='#accordionAdvanced'>
                                                        <div class='accordion-body'>
                                                            <div class='row'>
                                                                <div class='col-md-4'>
                                                                    <div class='mb-3'>
                                                                        <label class='form-label' for='validationType'>
                                                                            是否多值
                                                                        </label>
                                                                        <select class='form-control' id='validationType' required=''
                                                                                name='multiple_valued'
                                                                                <?php if(($attribute['attribute_id']??'') ):echo 'disabled';endif;?>>
                                                                            <option value='0' <?php if(($attribute['multiple_valued']??'') == 0 ):echo 'selected';endif;?>>单值
                                                                            </option>
                                                                            <option value='1' <?php if(($attribute['multiple_valued']??'') == 1 ):echo 'selected';endif;?>>多值
                                                                            </option>
                                                                        </select>
                                                                        <div class='invalid-feedback'>
                                                                            必须选择一个多值类型
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class='col-md-4'>
                                                                    <div class='mb-3'>
                                                                        <label class='form-label' for='validationOption'>
                                                                            是否有配置项
                                                                        </label>
                                                                        <select class='form-control' id='validationOption' required=''
                                                                                name='has_option'
                                                                                <?php if(($attribute['attribute_id']??'') ):echo 'disabled';endif;?>>
                                                                            <option value='0'
                                                                                    <?php if(($attribute['has_option']??'') == 0 ):echo 'selected';endif;?>>
                                                                                没有特定配置项
                                                                            </option>
                                                                            <option value='1'
                                                                                    <?php if(($attribute['has_option']??'') == 1 ):echo 'selected';endif;?>>
                                                                                有特定配置项
                                                                            </option>
                                                                        </select>
                                                                        <span class='help-block'>有配置项则只能选择配置项内设置的值，没有配置项可以输入任意值。</span>
                                                                    </div>
                                                                </div>
                                                                <div class='col-md-4'>
                                                                    <div class='mb-3'>
                                                                        <label class='form-label' for='validationSystem'>
                                                                            是否是系统生成
                                                                        </label>
                                                                        <select class='form-control' id='validationSystem' required=''
                                                                                name='is_system'
                                                                                disabled>
                                                                            <option value='0'
                                                                                    <?php if(($attribute['is_system']??'') == 0 ):echo 'selected';endif;?>>
                                                                                非系统属性
                                                                            </option>
                                                                            <option value='1'
                                                                                    <?php if(($attribute['is_system']??'') == 1 ):echo 'selected';endif;?>>
                                                                                系统属性
                                                                            </option>
                                                                        </select>
                                                                        <span class='help-block'>仅做标记是否由系统生成，或者非系统生成（用户自定义）。</span>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <?php if(!empty(($attribute['has_option']??'') ) ): ?>
                                <div class='tab-pane' id='progress-attribute-option'>
                                    <form class='needs-validation' novalidate='' action='<?=$action ;?>' method='post'>
                                        <input type='hidden' name='selected' value='<?php if($attribute_option ):echo 1; else: echo 0; endif;?>'>
                                        <input type='hidden' name='progress' value='progress-attribute-details'>
                                        <input type='hidden' name='next' value='progress_submit'>
                                        <div class='row'>
                                            <div class='col-lg-12'>
                                               <!--生成一个表，记录属性options-->

                                            </div>
                                        </div>
                                    </form>
                                </div>
                            <?php endif; ?>
                        </div>
                        <ul class='pager wizard twitter-bs-wizard-pager-link'>
                            <li class='previous'><a href='javascript: void(0);'>
                                    返回上一步
                                </a></li>
                            <li class='next'><a href='javascript: void(0);'>
                                    下一步
                                </a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end row -->
</div>
<!-- END layout-wrapper -->
<!--右边栏-->
<!--
========================================================================================================================== 
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\templates\common\right-sidebar.phtml START
==========================================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!-- Right Sidebar -->
<div class='right-bar'>
    <div data-simplebar class='h-100'>
        <div class='rightbar-title d-flex align-items-center px-3 py-4'>

            <h5 class='m-0 me-2'><?= __('设置') ?></h5>

            <a href="javascript:void(0);" class="right-bar-toggle ms-auto">
                <i class="mdi mdi-close noti-icon"></i>
            </a>
        </div>

        <!-- Settings -->
        <hr class='mt-0'/>
        <h6 class='text-center mb-0'>系统配置</h6>
        <div class='p-4'>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        全局 默认/还原
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='reset-theme'
                               value=''>
                        <label class='form-check-label' for='data-topbar-light'>
                            还原
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='light-mode-switch'
                               id='light-mode-radio'
                               value='light' <?= $themeConfig->getThemeConfig('light-mode-switch') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-light'>
                            明亮
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='dark-mode-radio'
                               value='dark' <?= $themeConfig->getThemeConfig('dark-mode-switch') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-light'>
                            暗黑
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <hr class='mt-0'/>
        <h6 class='text-center mb-0'><?= __('布局元素') ?></h6>
        <div class='p-4'>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        导航栏
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='data-topbar-light'
                               value='light' <?= ($themeConfig->getThemeConfig('data-topbar') === 'light') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-light'>
                            明亮
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='data-topbar-colored'
                               value='colored' <?= ($themeConfig->getThemeConfig('data-topbar') === 'colored') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-colored'>
                            有色
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='data-topbar-dark'
                               value='dark' <?= ($themeConfig->getThemeConfig('data-topbar') === 'dark') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-dark'>
                            暗黑
                        </label>
                    </div>
                </div>
            </div>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        侧边栏
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar'
                               id='data-sidebar-light'
                               value='light' <?= ($themeConfig->getThemeConfig('data-sidebar') === 'light') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-light'>
                            明亮
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar'
                               id='data-sidebar-dark'
                               value='dark' <?= ($themeConfig->getThemeConfig('data-sidebar') === 'dark') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-dark'>
                            暗黑
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar-size'
                               id='data-sidebar-size-default'
                               value='' <?= ($themeConfig->getThemeConfig('data-sidebar-size') === '') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-size-default'>
                            默认尺寸
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar-size'
                               id='data-sidebar-size-small'
                               value='small' <?= ($themeConfig->getThemeConfig('data-sidebar-size') === 'small') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-size-small'>
                            小尺寸
                        </label>
                    </div>
                </div>
            </div>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        布局尺寸
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-layout-size'
                               id='data-layout-size-default'
                               value='' <?= ($themeConfig->getThemeConfig('data-layout-size') === '') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-layout-size-default'>
                            默认
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-layout-size'
                               id='data-layout-size-boxed'
                               value='boxed' <?= ($themeConfig->getThemeConfig('data-layout-size') === 'boxed') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-layout-size-boxed'>
                            盒子
                        </label>
                    </div>
                </div>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='data-layout'
                    <?= $themeConfig->getThemeConfig('data-layout') ? 'checked' : '' ?>>
                <label class="form-check-label" for="data-layout"
                       title='"默认无布局：开启后，设置水平布局，关闭后，设置垂直布局"'><?= __('水平布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='data-keep-enlarged'
                    <?= $themeConfig->getThemeConfig('data-keep-enlarged') ? 'checked' : '' ?>>
                <label class="form-check-label" for="data-keep-enlarged"
                       title='"开启后，保持内容最大化"'><?= __('保持最大化') ?></label>
            </div>

            <div class='mb-3'>
                <h5 class='font-size-14 mb-3'>
                    布局类
                </h5>
                <div class='form-check form-check-inline'>
                    <input class='form-check-input' type='radio' name='layout-class'
                           id='layout-class-default'
                           value='' <?= ($themeConfig->getThemeConfig('layout-class') === '') ? 'checked' : '' ?>>
                    <label class='form-check-label' for='layout-class-default'>
                        默认
                    </label>
                </div>
                <div class='form-check form-check-inline'>
                    <input class='form-check-input' type='radio' name='layout-class'
                           id='layout-class-vertical-collpsed'
                           value='vertical-collpsed' <?= ($themeConfig->getThemeConfig('layout-class') === 'vertical-collpsed') ? 'checked' : '' ?>>
                    <label class='form-check-label' for='layout-class-vertical-collpsed'>
                        垂直塌陷
                    </label>
                </div>
            </div>
        </div>
        <hr class="mt-0"/>
        <h6 class='text-center mb-0'><?= __('菜单布局') ?></h6>
        <div class='p-4'>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='light-sidebar'
                    <?= $themeConfig->getThemeConfig('light-sidebar') ? 'checked' : '' ?>>
                <label class="form-check-label" for="light-sidebar"><?= __('菜单明亮') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='topnav'
                    <?= $themeConfig->getThemeConfig('topnav') ? 'checked' : '' ?>>
                <label class="form-check-label" for="topnav"><?= __('页顶菜单') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='icon-sidebar'
                    <?= $themeConfig->getThemeConfig('icon-sidebar') ? 'checked' : '' ?>>
                <label class="form-check-label" for="icon-sidebar"><?= __('图标菜单') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='layouts-compact-sidebar'
                    <?= $themeConfig->getThemeConfig('layouts-compact-sidebar') ? 'checked' : '' ?>>
                <label class="form-check-label" for="layouts-compact-sidebar"><?= __('图文菜单') ?></label>
            </div>
        </div>

        <hr class="mt-0"/>
        <h6 class='text-center mb-0'><?= __('主题布局') ?></h6>
        <div class='p-4'>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='horizontal_menu_top'
                    <?= $themeConfig->getThemeConfig('horizontal_menu_top') ? 'checked' : '' ?>>
                <label class="form-check-label" for="horizontal_menu_top"><?= __('水平菜单置顶') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='boxed'
                    <?= $themeConfig->getThemeConfig('boxed') ? 'checked' : '' ?>>
                <label class="form-check-label" for="boxed"><?= __('紧凑布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='horizontal-boxed'
                    <?= $themeConfig->getThemeConfig('horizontal-boxed') ? 'checked' : '' ?>>
                <label class="form-check-label" for="horizontal-boxed"><?= __('水平紧凑布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='horizontal'
                    <?= $themeConfig->getThemeConfig('horizontal') ? 'checked' : '' ?>>
                <label class="form-check-label" for="horizontal"><?= __('水平布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='layouts-hori-topbar-dark'
                    <?= $themeConfig->getThemeConfig('layouts-hori-topbar-dark') ? 'checked' : '' ?>>
                <label class="form-check-label" for="layouts-hori-topbar-dark"><?= __('水平顶黑') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='layouts-hori-boxed-width'
                    <?= $themeConfig->getThemeConfig('layouts-hori-boxed-width') ? 'checked' : '' ?>>
                <label class="form-check-label" for="layouts-hori-boxed-width"><?= __('水平盒子') ?></label>
            </div>
        </div>
        <hr class="mt-0"/>
        <h6 class="text-center mb-0"><?= __('主题颜色') ?></h6>

        <div class="p-4">
            <div class="mb-2">
                <img src="/weline/module-admin/view/statics/assets/images/layouts/layout-1.png?v=89193" class="img-thumbnail"
                     alt="layout-1">
            </div>
            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="checkbox" id="light-mode-switch"
                    <?= $themeConfig->getThemeConfig('light-mode-switch') ? 'checked' : '' ?>>
                <label class="form-check-label" for="light-mode-switch"><?= __('明亮模式') ?></label>
            </div>

            <div class="mb-2">
                <img src="/weline/module-admin/view/statics/assets/images/layouts/layout-2.png?v=88502" class="img-thumbnail"
                     alt="layout-2">
            </div>
            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="checkbox"
                       id="dark-mode-switch" <?= $themeConfig->getThemeConfig('dark-mode-switch') ? 'checked' : '' ?>>
                <label class="form-check-label" for="dark-mode-switch"><?= __('暗黑模式') ?></label>
            </div>

            <div class="mb-2">
                <img src="/weline/module-admin/view/statics/assets/images/layouts/layout-3.png?v=61754" class="img-thumbnail"
                     alt="layout-3">
            </div>
            <div class="form-check form-switch mb-5">
                <input class="form-check-input theme-choice" type="checkbox"
                       id="rtl-mode-switch" <?= $themeConfig->getThemeConfig('rtl-mode-switch') ? 'checked' : '' ?>>
                <label class="form-check-label" for="rtl-mode-switch"><?= __('RTL模式') ?></label>
            </div>
        </div>
    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>
<!--
============================================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\tpl\\zh_Hans_CN\templates\common\com_right-sidebar.phtml END
============================================================================================================================================
-->

<!--
=================================================================================================================== 
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\templates\common\footer.phtml START
===================================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="footer-wapper">
                <?php echo framework_view_process_block([
    0 => 'Weline\\Backend\\Block\\Version',
]);?>
            </div>
        </div>
    </div>
</div>
<!-- end Account pages -->

<!-- JAVASCRIPT -->
<!--<script src="/weline/module-admin/view/statics/assets/libs/jquery/jquery.min.js?v=19245"></script>-->
<script src="/weline/module-admin/view/statics/assets/libs/bootstrap/js/bootstrap.bundle.min.js?v=86466"></script>
<script src="/weline/module-admin/view/statics/assets/libs/metismenu/metisMenu.min.js?v=54588"></script>
<script src="/weline/module-admin/view/statics/assets/libs/simplebar/simplebar.min.js?v=95082"></script>
<script src="/weline/module-admin/view/statics/assets/libs/node-waves/waves.min.js?v=45462"></script>

<script src="/weline/module-admin/view/statics/assets/js/app.js?v=23921"></script>
<!--
===================================================================================================================== 
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-backend\view\templates\public\footer.phtml START
=====================================================================================================================
 -->
<?php echo framework_view_process_block([
    0 => 'Weline\\Backend\\Block\\Footer\\Base',
]);?>
<!--加载配置页脚-->
<?php
/**@var \Weline\Framework\View\Template $this */
if($this->getFooter()){
    echo $this->getFooter()->getHtml();
}
?>
<!--
=======================================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-backend\view\tpl\\zh_Hans_CN\templates\public\com_footer.phtml END
=======================================================================================================================================
-->
<!--
=====================================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\tpl\\zh_Hans_CN\templates\common\com_footer.phtml END
=====================================================================================================================================
-->
<!-- twitter-bootstrap-wizard js -->
<script src='/weline/module-admin/view/statics/assets/libs/twitter-bootstrap-wizard/jquery.bootstrap.wizard.min.js?v=64718'></script>

<script src='/weline/module-admin/view/statics/assets/libs/twitter-bootstrap-wizard/prettify.js?v=49645'></script>

<!-- form wizard init -->
<script src='/Weline/Eav/view/statics/js/pages/attribute-add/form-wizard.init.js?v=60131'></script>
<!-- Sweet Alerts js -->
<script src='/weline/module-admin/view/statics/assets/libs/sweetalert2/sweetalert2.min.js?v=36764'></script>

<!-- Sweet alert init js-->
<script src='/weline/module-admin/view/statics/assets/js/pages/sweet-alerts.init.js?v=54586'></script>
<script>

    function getEntityCode() {
        let entity_code = '<?=($eav_entity['code']??'') ;?>';
        if (entity_code === '') {
            entity_code = $('#progress-select-entity').find('option:selected').val()
        }
        return entity_code;
    }

    function getSetCode() {
        let set_code = '<?=($eav_entity_attribute_set['code']??'') ;?>';
        if (set_code === '') {
            set_code = $('#progress-select-set').find('option:selected').val()
        }
        return set_code;
    }

    function getGroupCode() {
        let group_code = '<?=($eav_entity_attribute_set_group['code']??'') ;?>';
        if (group_code === '') {
            group_code = $('#progress-select-group').find('option:selected').val()
        }
        return group_code;
    }

    /*实体搜索*/
    function renderSearchEntities(e) {
        let search_entity = $(e.target)
        let search = search_entity.val()
        $.ajax({
            url: '<?=$this->getBackendUrl("*/backend/entity/search")?>?search=' + search,
            success: function (res) {
                let items = res['items']
                let search_entity_result = $('#search-entity-result')
                search_entity_result.empty()
                for (const item of items) {
                    search_entity_result.append(`<option value="${item.code}">${item.name}</option>`)
                }
                $('#progress-select-entity').find('input[name=\'selected\']').val(0)
            }
        })
    }

    /* 实体属性集搜索 */
    function renderSearchEntityAttributeSet(e) {
        let search = $(e.target)
        search = search.val()
        let entity_code = getEntityCode()
        $.ajax({
            url: '<?=$this->getBackendUrl("*/backend/attribute/set/search")?>?search=' + search + '&entity_code=' + entity_code,
            success: function (res) {
                if (res['msg']) {
                    Swal.fire(
                        {
                            title: '警告！',
                            text: res['msg'],
                            icon: 'error',
                            dangerMode: true,
                            confirmButtonText: '好的'
                        }
                    )
                    return false;
                }
                let items = res['items']
                let search_entity_attribute_set_result = $('#search-entity-attribute-set-result')
                search_entity_attribute_set_result.empty()
                for (const item of items) {
                    search_entity_attribute_set_result.append(`<option value="${item.code}">${item.name}</option>`)
                }
                $('#progress-select-set').find('input[name=\'selected\']').val(0)
            }
        })
    }

    /* 实体属性集属性组 */
    function renderSearchEntityAttributeSetGroup(e) {
        let search = $(e.target)
        search = search.val()
        let entity_code = getEntityCode()
        let set_code = getSetCode()
        $.ajax({
            url: '<?=$this->getBackendUrl("*/backend/attribute/group/search")?>?search=' + search +
                '&entity_code=' + entity_code + '&set_code=' + set_code,
            success: function (res) {
                if (res['msg']) {
                    Swal.fire(
                        {
                            title: '警告！',
                            text: res['msg'],
                            icon: 'error',
                            dangerMode: true,
                            confirmButtonText: '好的'
                        }
                    )
                    return false;
                }
                let items = res['items']
                let search_entity_attribute_set_result = $('#search-entity-attribute-set-group-result')
                search_entity_attribute_set_result.empty()
                for (const item of items) {
                    search_entity_attribute_set_result.append(`<option value="${item.code}">${item.name}</option>`)
                }
                $('#rogress-select-group').find('input[name=\'selected\']').val(0)
            }
        })
    }

    /*监听实体选择*/
    $('#search-entity-result').on('change', (e) => {
        let target = $(e.target).find('option:selected')
        let stepHelper = $('a[class="nav-link active"]')
        stepHelper.find('.help-block').remove()
        stepHelper.append(`<span class="help-block">
                                            ${__('你选择了')}
                                            <span class="text-primary">${target.text()}</span>
                                        </span>`)
        // 渲染下一个
        $('#renderSearchEntityAttributeSetButton').click()
    })
    /*监听属性集选择*/
    $('#search-entity-attribute-set-result').on('change', (e) => {
        let target = $(e.target).find('option:selected')
        let stepHelper = $('a[class="nav-link active"]')
        stepHelper.find('.help-block').remove()
        stepHelper.append(`<span class="help-block">
                                            ${__('你选择了')}
                                            <span class="text-primary">${target.text()}</span>
                                        </span>`)
        // 渲染下一个
        $('#renderSearchEntityAttributeSetGroupButton').click()
    })
    /*监听属性组选择*/
    $('#search-entity-attribute-set-group-result').on('change', (e) => {
        let target = $(e.target).find('option:selected')
        let stepHelper = $('a[class="nav-link active"]')
        stepHelper.find('.help-block').remove()
        stepHelper.append(`<span class="help-block">
                                            ${__('你选择了')}
                                            <span class="text-primary">${target.text()}</span>
                                        </span>`)
    })
    // 初始化选中步骤
    $(document).ready(() => {
        $('.twitter-bs-wizard-nav .nav-link[data-target="1"]').tab('show')

        /*延迟期间最多执行一次：优化输入请求过多ajax*/
        function debounce(func, delay) {
            let timeoutId;
            return function (...args) {
                if (timeoutId) {
                    clearTimeout(timeoutId);
                }
                timeoutId = setTimeout(() => {
                    func.apply(this, args);
                    timeoutId = null;
                }, delay);
            };
        }

        function throttle(func, delay) {
            let timeoutId;
            let lastExecTime = 0;
            return function (...args) {
                const elapsedTime = new Date().getTime() - lastExecTime;
                if (elapsedTime > delay) {
                    lastExecTime = new Date().getTime();
                    func.apply(this, args);
                } else {
                    clearTimeout(timeoutId);
                    timeoutId = setTimeout(() => {
                        lastExecTime = new Date().getTime();
                        func.apply(this, args);
                        timeoutId = null;
                    }, delay - elapsedTime);
                }
            };
        }

        /*监听属性代码是否可用*/
        const throttledProgressAttributeCode = debounce((e) => {
            let search = $(e.target).val()
            let name = $('#progress-attribute-name').val()
            let stepHelper = $('a[class="nav-link active"]')
            stepHelper.find('.help-block').remove()
            stepHelper.append(`<span class="help-block">
                                            ${__('你选择了')}
                                            <span class="text-primary">${search}(${name})</span>
                                        </span>`)
            $.ajax({
                url: '<?=$this->getBackendUrl("*/backend/attribute/search")?>?field=code&limit=1&search=' + search +
                    '&entity_code=' + getEntityCode() + '&set_code=' + getSetCode() + '&group_code=' + getGroupCode(),
                success: function (res) {
                    if (res['msg']) {
                        Swal.fire(
                            {
                                title: '警告！',
                                text: res['msg'],
                                icon: 'error',
                                dangerMode: true,
                                confirmButtonText: '好的'
                            }
                        )
                        return false;
                    }
                    let items = res['items']
                    let attribute_code_input = $('#progress-attribute-code')
                    if (items.length) {
                        attribute_code_input.removeClass('border-success')
                        attribute_code_input.addClass('border-danger')
                    } else {
                        attribute_code_input.removeClass('border-danger')
                        attribute_code_input.addClass('border-success')
                    }
                }
            })
        }, 500);
        $('#progress-attribute-code').on('input', throttledProgressAttributeCode)
        /*监听属性名称是否可用*/
        const throttledProgressAttributeName = debounce((e) => {
            let search = $(e.target).val()
            let code = $('#progress-attribute-code').val()
            let stepHelper = $('a[class="nav-link active"]')
            stepHelper.find('.help-block').remove()
            stepHelper.append(`<span class="help-block">
                                            ${__('属性数据')}
                                            <span class="text-primary">${code}(${search})</span>
                                        </span>`)
            $.ajax({
                url: '<?=$this->getBackendUrl("*/backend/attribute/search")?>?field=name&limit=1&search=' + search +
                    '&entity_code=' + getEntityCode() + '&set_code=' + getSetCode() + '&group_code=' + getGroupCode(),
                success: function (res) {
                    if (res['msg']) {
                        Swal.fire(
                            {
                                title: '警告！',
                                text: res['msg'],
                                icon: 'error',
                                dangerMode: true,
                                confirmButtonText: '好的'
                            }
                        )
                        return false;
                    }
                    let items = res['items']
                    let attribute_code_input = $('#progress-attribute-name')
                    if (items.length) {
                        attribute_code_input.removeClass('border-success')
                        attribute_code_input.addClass('border-danger')
                    } else {
                        attribute_code_input.removeClass('border-danger')
                        attribute_code_input.addClass('border-success')
                    }
                }
            })
        }, 500);
        $('#progress-attribute-name').on('input', throttledProgressAttributeName)

        // 选择切换配置项时 调整 progress-submit
        let changeOptionConfig = $('#validationOption')
        changeOptionConfig.change((e) => {
            // 获取当前选中的值
            var selectedValue = $(e.target).find('option:selected').val();
            // 如果选中1 说明需要配置配置项
            let attribute_detail_container = $('#progress-attribute-details')
            let form = attribute_detail_container.find('form')
            if (form.get(0).reportValidity()) {
                if(selectedValue === '1'){
                    form.find('input[name="progress"]').val('progress-attribute-details')
                    form.find('input[name="next_progress"]').val('progress-attribute-option')
                }
                form.submit()
            }
        })
    })

</script>
</body>
</html>

<!--
=======================================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\app\code\Weline\Eav\view\tpl\\zh_Hans_CN\templates\Backend\Attribute\com_form.phtml END
=======================================================================================================================================
-->