<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!--加载require常用js模块-->
<!--<script src='@static(Weline_Frontend::base/require.configs.js)'></script>-->
<script>
    window.site = {
        host: '<?=$this->request->getBaseHost()?>',
        env_model: '<?=\Weline\Framework\App\Env::getInstance()->getConfig('deploy')?>',
        env_model_media_base_path_template: '<?=$this->request->getBaseHost()?>'+'<?php if(DEV):echo '/{module}/view/statics/{path}'; else:echo
        '/static/'.\Weline\Framework\App\Env::getInstance()->getTheme()['path'].'/{module}/view/statics/{path}';endif;?>',
        base_host: '<?=$this->request->getPrePath()?>',
        base_router: '<?=$this->request->getRouterData('router')?>',
        i18n: <?= json_encode(Weline\Framework\Phrase\Parser::getI18nWords())?>,
        buildUrl: (path) => {
            return window.site.host + path;
        },
        buildStaticMediaUrl: (path,module='<?=$this->request->getModuleName()?>') => {
            module = module.replace('_','/')
            return window.site.env_model_media_base_path_template.replace('{path}',path).replace('{module}',module)
        },
        buildApi: (path) => {
            return window.site.host + path;
        },
        buildFrontendApiUrl: (path) => {
            return window.site.host + path;
        },
        themeConfig: <?=json_encode($themeConfig->getThemeConfig()) ?? '{}';?>,
        selectLanguage: (lang) => {
            setCookie('WELINE-USER-LANG', lang);
            window.location.reload();
        },

    }

    /**
     * 设置Cookie
     * @param cname
     * @param cvalue
     * @param exdays
     */
    function setCookie(cname, cvalue, exdays) {
        let d = new Date();
        d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
        let expires = 'expires=' + d.toGMTString();
        document.cookie = cname + '=' + cvalue + '; ' + expires;
    }

    /**
     * 获取Cookie
     * @param cname
     * @returns {string}
     */
    function getCookie(cname) {
        let name = cname + '=';
        let ca = document.cookie.split(';');
        for (let i = 0; i < ca.length; i++) {
            let c = ca[i].trim();
            if (c.indexOf(name) === 0) return c.substring(name.length, c.length);
        }
        return '';
    }

    /**
     * 通用打印函数
     * @param data
     */
    function p(data) {
        console.log(data)
    }

    /**
     * 翻译函数
     * @param phrase
     * @returns {*}
     * @private
     */
    function __(phrase) {
        if (window.site.i18n[phrase] !== undefined) {
            phrase = window.site.i18n[phrase]
        }
        return phrase
    }
</script>