<?php
/**
 * @var $this \Weline\Framework\View\Template
 */
?>
@template(Weline_Backend::public/header.phtml)
<link rel="stylesheet" href="@static(Weline_Admin::backend/theme/material/css/iot-theme-bundle.min.css)">
<link rel="stylesheet" href="@static(Weline_Admin::backend/theme/material/css/material.css)">
</head>
<body>
<div class="header-wapper">
    <div>Menu</div>
</div>
@template(Weline_Backend::blocks/menu.phtml)
<script>
    require(['jquery','bootstrapBundle'],function ($,bootstrapBundle){
        alert($(window).width())
    })
</script>
</body>
@template(Weline_Backend::public/footer.phtml)