<?php
/*
 * 本文件由 秋枫雁飞 编写，所有解释权归Aiweline所有。
 * 邮箱：aiweline@qq.com
 * 网址：aiweline.com
 * 论坛：https://bbs.aiweline.com
 */
?>
<div class='col-12'>
    <div class='card'>
        <div class='card-body'>
            <a href="@url('/dev/tool/')" class='btn btn-dark'>
                <lang>返回欢迎页</lang>
            </a>
            <a href='javascript:window.history.back();' class='btn btn-info'>
                <lang>返回上一页</lang>
            </a>
        </div>
    </div>
</div>
