<!--
=============================================================================================================== 
模板文件：D:\wwwroot\dev-bbs.aiweline.com\app\code\Weline\Backend\view\templates\public\footer.phtml START
===============================================================================================================
 -->
<?php echo framework_view_process_block([
    0 => 'Weline\\Backend\\Block\\Footer\\Base',
]);?>
<!--加载配置页脚-->
<?php
/**@var \Weline\Framework\View\Template $this */
echo $this->getFooter()->getHtml();
?>
<!--
=================================================================================================================================
模板文件：D:\wwwroot\dev-bbs.aiweline.com\app\code\Weline\Backend\view\tpl\\zh_Hans_CN\templates\public\com_footer.phtml END
=================================================================================================================================
-->