<?php
/**
 * @var $this \Weline\Framework\View\Template
 */?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="Shortcut Icon" href="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("/img/favicon.png"));// 读取资源文件 ?>">
    <link rel="Bookmark" href="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("/img/favicon.png"));// 读取资源文件 ?>">
    <link href="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("/css/header.css"));// 读取资源文件 ?>" type="text/css" rel="stylesheet">
    <title>欢迎加入 Weline Framework 的世界! 发现不一样的世界！</title>
    <?php
    /**
     * @var $this \Weline\Framework\View\Template
     */
    ?>
    <link href="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("/css/index.css"));// 读取资源文件 ?>" type="text/css" rel="stylesheet">
    <script src="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("/js/demo.js"));// 读取资源文件 ?>"></script>
</head>
<div class="header">
    我是头部
</div>