<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang='en' <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    @template(Weline_Admin::common/head.phtml)
    <!-- jvectormap -->
    <link href="@static(Weline_Admin::assets/libs/jqvmap/jqvmap.min.css)" rel="stylesheet"/>
    <!-- jquery.mCustomScrollbar 插件 -->
    <link href="@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.css)" rel="stylesheet"/>
    <!-- Sweet Alert-->
    <link href='@static(Weline_Admin::assets/libs/sweetalert2/sweetalert2.min.css)' rel='stylesheet' type='text/css'/>
    <title><?= __('Weline Admin 管理面板') ?></title>
</head>

<body <?= $themeConfig->getLayouts() ?? ''; ?>>

<!--页头工具条 开始-->
@template(Weline_Admin::common/page/loading.phtml)
<!--页头工具条 结束-->

<!-- 开始 页面 -->
<div id="layout-wrapper">


    <!--页头工具条 开始-->
    <w:block class='Weline\Admin\Block\Backend\Page\Topbar'/>
    <!--页头工具条 结束-->

    <!-- ========== Topnav Start ========== -->
    <!--页头菜单栏 开始-->
    <w:block class='Weline\Admin\Block\Backend\Page\Topnav'/>
    <!--页头菜单栏 结束-->

    <!-- ========== Left Sidebar Start ========== -->
    <!--左侧菜单栏 开始-->
    <w:template>Weline_Admin::common/left-sidebar.phtml</w:template>
    <!--左侧菜单栏 结束-->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class="page-content">
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <h4 class="mb-sm-0"><?= __('菜单管理') ?></h4>

                            <div class="page-title-right">
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="javascript: void(0);"><?= __('系统') ?></a></li>
                                    <li class="breadcrumb-item active"><?= __('菜单管理') ?></li>
                                </ol>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- end page title -->
                <!-- start page message -->
                <div class='row'>
                    <template>Weline_Component::message.phtml</template>
                </div> <!-- end message -->
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                <h4 class="card-title"><?= __('菜单编辑器') ?></h4>

                                <!--<div class="table-responsive mCustomScrollbar" data-mcs-axis="yx" data-mcs-theme='dark'
                                     style="height: 800px">-->
                                <div class='table-responsive mCustomScrollbar' data-mcs-axis='x'
                                     data-mcs-theme='dark'>
                                    <table class="table table-editable table-nowrap align-middle table-edits">
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th><?= __('菜单名') ?></th>
                                            <th><?= __('标题') ?></th>
                                            <th><?= __('资源') ?></th>
                                            <th><?= __('父资源') ?></th>
                                            <th><?= __('动作') ?></th>
                                            <th><?= __('模组') ?></th>
                                            <th><?= __('Icon图标') ?></th>
                                            <th><?= __('排序') ?></th>
                                            <th><?= __('是否系统菜单') ?></th>
                                            <th><?= __('创建时间') ?></th>
                                            <th><?= __('更新时间') ?></th>
                                            <th><?= __('操作') ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        /**@var \Weline\Backend\Model\Menu $menu */
                                        foreach ($this->getData('menus') as $menu) {
                                            ?>
                                            <tr data-id='<?= $menu->getId() ?>'>
                                                <td data-field='id' style='width: 80px'><?= $menu->getId() ?></td>
                                                <td data-field='name'><?= $menu->getName() ?></td>
                                                <td data-field='title'><?= $menu->getTitle() ?></td>
                                                <td data-field='source'><?= $menu->getSource() ?></td>
                                                <td data-field='parent_source'><?= $menu->getParentSource() ?></td>
                                                <td data-field='action'><?= $menu->getAction() ?></td>
                                                <td data-field='module'><?= $menu->getModule() ?></td>
                                                <td data-field='icon'><i class='<?= $menu->getIcon() ?>'
                                                                         style="margin-right: 25px"></i><span><?= $menu->getIcon() ?></span>
                                                </td>
                                                <td data-field='order'><?= $menu->getOrder() ?></td>
                                                <td data-field='is_system'><?= $menu->isSystem() ?></td>
                                                <td data-field='create_time'><?= $menu->getCreateTime() ?></td>
                                                <td data-field='update_time'><?= $menu->getUpdateTime() ?></td>
                                                <td style='width: 100px'>
                                                    <a class='btn btn-outline-secondary btn-sm edit'
                                                       title='<?= __('编辑') ?>'>
                                                        <i class='fas fa-pencil-alt'></i>
                                                    </a>
                                                    <a class='btn btn-outline-secondary btn-sm <?= $menu->isSystem() ? '' : 'menu-delete' ?>'
                                                       data-id="<?= $menu->getId() ?>"
                                                       title='<?= $menu->isSystem() ? __('系统菜单无法删除！') : __('删除') ?>'>
                                                        <i class='mdi <?= $menu->isSystem() ? 'mdi-delete-off' : 'mdi-delete' ?> '
                                                           style="<?= $menu->isSystem() ? 'color:red' : '' ?>"
                                                           data-id="<?= $menu->getId() ?>"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            <?php
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <var>pagination</var>
                    </div> <!-- end col -->
                </div> <!-- end row -->
            </div> <!-- container-fluid -->
        </div>
        <!-- End Page-content -->

        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <script>document.write(new Date().getFullYear())</script>
                        © Weline.
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end d-none d-sm-block">
                            Crafted with <i class="mdi mdi-heart text-danger"></i> By <a
                                    href="https://www.aiweline.com/">秋枫雁飞(aiweline)</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>
    <!-- end main content-->

</div>
<!-- END layout-wrapper -->
<!--右边栏-->
@template(Weline_Admin::common/right-sidebar.phtml)

<!-- Table Editable plugin -->
<script src="@static(Weline_Admin::assets/libs/table-edits/build/table-edits.min.js)"></script>
<script src="@static(Weline_Admin::assets/js/pages/menus/table-editable.init.js)"></script>
<script src='@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js)'></script>
<!-- Sweet Alerts js -->
<script src='@static(Weline_Admin::assets/libs/sweetalert2/sweetalert2.min.js)'></script>

<!-- Sweet alert init js-->
<script src='@static(Weline_Admin::assets/js/pages/menus/sweet-alerts.init.js)'></script>
@template(Weline_Admin::common/footer.phtml)
</body>
</html>
