
<?php
//$this->getViewFile('templates/public/header.phtml');
?>
@template public/header.phtml
<body>
<h1>欢迎加入 M Framework 的世界! 发现不一样的世界！</h1>
<div class="img-box"><img src="@static/img/logo.png" alt=""></div>
<p class="official-p">开发者：秋枫雁飞&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;论坛：<a href="http://bbs.aiweline.com" target="_blank">bbs.aiweline.com</a></p>
<div class="feature">
    <div class="feature-detail">
        <h3>提示：</h3>
        <p>这里是功能使用测试，有关如何使用的简单demo。</p>
    </div>
</div>
<div class="feature">
    <div class="feature-detail">
        <h3>数据库数据：</h3>
        <php>
            print_r($this->getData('data'));
        </php>
    </div>
</div>
<?php
//$this->getViewFile('templates/public/footer.phtml');
?>
@template public/footer.phtml
</body>
</html>
