<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         描述
-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $this->getData('title');?></title>
    <link rel="Shortcut Icon" href="__STATIC__/img/favicon.png">
    <link rel="Shortcut Icon" href="__STATIC__/img/favicon.png">
    <link rel="Bookmark" href="__STATIC__/img/favicon.png">
    <script src="__STATIC__/lib/vue/vue2.6.11.js"></script>

