
<?php
//$this->getViewFile('templates/public/header.phtml');
?>
<?php
/**
 * @var $this \Weline\Framework\View\Template
 */?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="Shortcut Icon" href="/Aiweline/HelloWorld/view/statics/img/favicon.png?v=56384">
    <link rel="Bookmark" href="/Aiweline/HelloWorld/view/statics/img/favicon.png?v=56384">
    <link href="/Aiweline/HelloWorld/view/statics/css/header.css?v=84453" type="text/css" rel="stylesheet">
    <title>欢迎加入 Weline Framework 的世界! 发现不一样的世界！</title>
    <?php
    /**
     * @var $this \Weline\Framework\View\Template
     */
    ?>
    <link href="/Aiweline/HelloWorld/view/statics/css/index.css?v=19566" type="text/css" rel="stylesheet">
    <script src="/Aiweline/HelloWorld/view/statics/js/demo.js?v=70835"></script>
</head>
<div class="header">
    我是头部
</div>
<body>
<h1>欢迎加入 Weline Framework 的世界! 发现不一样的世界！</h1>
<div class="img-box"><img src="/Aiweline/HelloWorld/view/statics/img/logo.png?v=26130" alt=""></div>
<p class="official-p">开发者：秋枫雁飞&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;论坛：<a href="http://bbs.aiweline.com" target="_blank">bbs.aiweline.com</a></p>
<div class="feature">
    <div class="feature-detail">
        <h3>提示：</h3>
        <p>这里是功能使用测试，有关如何使用的简单demo。</p>
    </div>
</div>
<div class="feature">
    <div class="feature-detail">
        <h3>数据库数据：</h3>
        <?php 
            p($this->getData('data'),true);
        ?>
    </div>
</div>
<?php
//$this->getViewFile('templates/public/footer.phtml');
?>
<?php
/**
 * @var $this \Weline\Framework\View\Template
 */?>
<div class="footer">
    <link href="/Aiweline/HelloWorld/view/statics/css/footer.css?v=51574" type="text/css" rel="stylesheet">
我是页脚
</div>
</body>
</html>
