<?php
/**@var \Weline\Framework\View\Template $this*/
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $this->getData('title'); ?></title>
    <link rel="Shortcut Icon" href="@static(Weline_Backend::img/favicon.png)">
    <link rel="Shortcut Icon" href="@static(Weline_Backend::img/favicon.png)">
    <link rel="Bookmark" href="@static(Weline_Backend::img/favicon.png)">
    <!--css-->
    <link rel="stylesheet" href="@static(Weline_Backend::lib/bootstrap-4.6.0-dist/css/bootstrap.min.css)">
    <link rel="stylesheet" href="@static(Weline_Backend::lib/font-awesome-4.7.0/css/font-awesome.min.css)">
    <!--加载requirejs-->
    <?php if (DEV) : ?>
        <script src="@static(Weline_Backend::lib/requirejs/2.3.6/requirejs.js)"></script>
    <?php
    else:
    ?>
        <script src="@static(Weline_Backend::lib/requirejs/2.3.6/requirejs.min.js)"></script>
    <?php
    endif;
    ?>
    <!--加载require常用js模块-->
    <script src="@static(Weline_Backend::require.config.js)"></script>
    <!--    <script src="@static/lib/vue/vue2.6.11.js"></script>-->
    <?php
    echo $this->getHeader()->getHtml();
    ?>
</head>

