<?php
/**@var \Weline\Framework\View\Template $this */
?>
<meta charset="UTF-8">
<title><?php echo $this->getData('title'); ?></title>
<meta content="<?php echo $this->getData('description'); ?>" name="description"/>
<link rel="Shortcut Icon" href="@static(Weline_Backend::img/favicon.png)">
<link rel="Shortcut Icon" href="@static(Weline_Backend::img/favicon.png)">
<link rel="Bookmark" href="@static(Weline_Backend::img/favicon.png)">
<!--加载基础JS-->
<w:block class='Weline\Backend\Block\Header\Base' template='Weline_Backend::header/base.phtml'/>
<!--加载requirejs-->
<?php if (DEV) : ?>
    <!--    <script src="@static(Weline_Backend::backend/lib/requirejs/2.3.6/requirejs.js)"></script>-->
<?php
else:
    ?>
    <!--    <script src="@static(Weline_Backend::backend/lib/requirejs/2.3.6/requirejs.min.js)"></script>-->
<?php
endif;
?>
<!--加载require常用js模块-->
<!--<script src="@static(Weline_Backend::base/require.configs.js)"></script>-->
<!--加载配置页头-->
<?php
echo $this->getHeader()->getHtml();
?>

