<div class='card'>
    <div class='card-body'>
        <div class='d-flex text-muted'>
            <div class='flex-shrink-0 me-3 align-self-center'>
                <div id='<?=$id ?>' class='apex-charts' dir='ltr'></div>
            </div>
            <div class='flex-grow-1 overflow-hidden'>
                <p class='mb-1'>
                    <?=$title ?>
                </p>
                <h5 class='mb-3'><?=$total ?></h5>
                <p class='text-truncate mb-0'>
                    <?=$tip ?>
                    <span class='<?=$class ?> me-2'>
                        <?=$rate ?>
                        <i class='ri-arrow-right-<?=$up_down ?>-line align-bottom ms-1'></i>
                    </span>
                </p>
            </div>
        </div>
    </div>
    <!-- end card-body -->
</div>
<!-- end card -->