<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang='en' <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    @template(Weline_Admin::common/head.phtml)
    <title><?= __('Weline Admin 管理面板') ?></title>
    <!-- twitter-bootstrap-wizard css -->
    <link rel='stylesheet' href='@static(Weline_Admin::assets/libs/twitter-bootstrap-wizard/prettify.css)'>
    <!-- Sweet Alert-->
    <link href='@static(Weline_Admin::assets/libs/sweetalert2/sweetalert2.min.css)' rel='stylesheet' type='text/css'/>
</head>

<body <?= $themeConfig->getLayouts() ?? ''; ?> class='bg-transparent'>

<!--页头工具条 开始-->
@template(Weline_Admin::common/page/loading.phtml)
<!--页头工具条 结束-->

<!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- 开始 页面 -->
<div id="layout-wrapper">
    <!-- start page message -->
    <div class='row'>
        <template>Weline_Component::message.phtml</template>
    </div> <!-- end message -->
    <div class='row'>
        <div class='col-lg-12'>
            <div class='card'>
                <div class='card-body'>
                    <div id='progress-wizard' class='twitter-bs-wizard'>
                        <ul class='twitter-bs-wizard-nav nav-justified'>
                            <li class='nav-item'>
                                <a href='#progress-select-entity'
                                   data-target="@if{progress==='progress-select-entity'=>'1'|'0'}"
                                   class='nav-link'
                                   data-progress="{{progress}}"
                                   data-toggle='tab'>
                                    <span class='step-number'>01</span>
                                    <span class='step-title'><lang>选择实体</lang></span>
                                    <notempty name="eav_entity">
                                        <span class="help-block">
                                            <lang>你选择了</lang>
                                            <span class="text-primary">{{eav_entity.name}}</span>
                                        </span>
                                    </notempty>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='#progress-select-set'
                                   data-target="@if{progress==='progress-select-set'=>'1'|'0'}"
                                   class='nav-link'
                                   data-progress='{{progress}}'
                                   data-toggle='tab'>
                                    <span class='step-number'>02</span>
                                    <span class='step-title'><lang>选择属性集</lang></span>
                                    <notempty name='eav_entity_attribute_set'>
                                        <span class='help-block'>
                                            <lang>你选择了</lang>
                                            <span class='text-primary'>{{eav_entity_attribute_set.name}}</span>
                                        </span>
                                    </notempty>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='#progress-select-group'
                                   data-target="@if{progress==='progress-select-group'=>'1'|'0'}"
                                   class='nav-link'
                                   data-progress='{{progress}}'
                                   data-toggle='tab'>
                                    <span class='step-number'>03</span>
                                    <span class='step-title'><lang>选择属性组</lang></span>
                                    <notempty name="eav_entity_attribute_set_group">
                                        <span class='help-block'>
                                            <lang>你选择了</lang>
                                            <span class='text-primary'>{{eav_entity_attribute_set_group.name}}</span>
                                        </span>
                                    </notempty>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='#progress-attribute-details'
                                   data-target="@if{progress==='progress-attribute-details'=>'1'|'0'}"
                                   class='nav-link'
                                   data-progress='{{progress}}'
                                   data-toggle='tab'>
                                    <span class='step-number'>04</span>
                                    <span class='step-title'>创建属性</span>
                                    <notempty name="attribute">
                                        <span class='help-block'>
                                            <lang>你创建了</lang>
                                            <span class='text-primary'>{{attribute.name}}（{{attribute.code}}）</span>
                                        </span>
                                    </notempty>
                                </a>
                            </li>
                            <!--如果有配置属性配置项-->
                            <notempty name='attribute.has_option'>
                                <li class='nav-item'>
                                    <a href='#progress-attribute-option'
                                       class='nav-link @if{progress==="progress-attribute-option"=>"active"}' data-toggle='tab'>
                                        <span class='step-number'>05</span>
                                        <span class='step-title'><lang>配置项</lang></span>
                                    </a>
                                </li>
                            </notempty>
                        </ul>

                        <div id='bar' class='progress mt-5'>
                            <div class='progress-bar bg-success progress-bar-striped progress-bar-animated'></div>
                        </div>
                        <div class='tab-content twitter-bs-wizard-tab-content'>
                            <div class='tab-pane' id='progress-select-entity'>
                                <form action="{{action}}" method="post">
                                    <input type='hidden' name='selected' value='@has{eav_entity=>1|0}'>
                                    <input type="hidden" name="progress" value="progress-select-entity">
                                    <input type="hidden" name="next_progress" value="progress-select-set">
                                    <div class="row">
                                        <div class="mx-auto col-lg-6 mt-2 mb-4">
                                            <div class='input-group'>
                                                <input type='search' class='form-control rounded' id='search-entity'
                                                       placeholder='@lang{请输入要查找的实体名或者实体代码}'
                                                       aria-label='@lang{请输入要查找的实体名或者实体代码}'
                                                       aria-describedby='search-addon'/>
                                                <button type='button' class='btn btn-outline-primary'
                                                        onclick='renderSearchEntities(event)'>
                                                    <lang>搜索实体</lang>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class='mx-auto col-lg-6 mt-2 mb-4'>
                                            <div class='input-group'>
                                                <select id='search-entity-result' class='form-select form-control rounded'
                                                        size="10"
                                                        name="entity_code"
                                                        data-style='btn-primary' data-width='fit'
                                                        aria-label='@lang{搜索实体结果}'
                                                        aria-describedby='search-addon' required>
                                                    <foreach name="entities">
                                                        <option value='{{v.code}}' @if{eav_entity.code===v.code=>'selected'}>
                                                            {{v.name}}
                                                        </option>
                                                    </foreach>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class='tab-pane' id='progress-select-set'>
                                <div>
                                    <form action="{{action}}" method="post">
                                        <input type='hidden' name='selected' value='@has{eav_entity_attribute_set=>1|0}'>
                                        <input type='hidden' name='progress' value='progress-select-set'>
                                        <input type='hidden' name='next_progress' value='progress-select-group'>
                                        <div class='row'>
                                            <div class='mx-auto col-lg-6 mt-2 mb-4'>
                                                <div class='input-group'>
                                                    <input type='search' class='form-control rounded' id='search-entity-attribute-set'
                                                           placeholder='@lang{请输入要查找的 属性集名 或者 属性集代码}'
                                                           aria-label='@lang{请输入要查找的 属性集名或者 属性集代码}'
                                                           aria-describedby='search-addon'/>
                                                    <button type='button' class='btn btn-outline-primary' id="renderSearchEntityAttributeSetButton"
                                                            onclick='renderSearchEntityAttributeSet(event)'>
                                                        <lang>搜索 {{eav_entity.name}} 属性集</lang>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class='row'>
                                            <div class='mx-auto col-lg-6 mt-2 mb-4'>
                                                <div class='input-group'>
                                                    <select id='search-entity-attribute-set-result' class='form-select form-control rounded'
                                                            size='10'
                                                            name='set_code'
                                                            data-style='btn-primary' data-width='fit'
                                                            aria-label='@lang{搜索 属性集 结果}'
                                                            aria-describedby='search-addon' required>
                                                        <foreach name='sets'>
                                                            <option value='{{v.code}}' @if{eav_entity_attribute_set.code===v.code=>'selected'}>
                                                                {{v.name}}
                                                            </option>
                                                        </foreach>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class='tab-pane' id='progress-select-group'>
                                <div>
                                    <form action="{{action}}" method="post">
                                        <input type='hidden' name='selected' value='@has{eav_entity_attribute_set_group=>1|0}'>
                                        <input type='hidden' name='progress' value='progress-select-group'>
                                        <input type='hidden' name='next_progress' value='progress-attribute-details'>
                                        <div class='row'>
                                            <div class='mx-auto col-lg-6 mt-2 mb-4'>
                                                <div class='input-group'>
                                                    <input type='search' class='form-control rounded' id='search-entity-attribute-set-group'
                                                           placeholder='@lang{请输入要查找的【实体-属性集-属性组】名或者【实体-属性集-属性组】代码}'
                                                           aria-label='@lang{请输入要查找的【实体-属性集-属性组】名或者【实体-属性集-属性组】代码}'
                                                           aria-describedby='search-addon'/>
                                                    <button type='button' class='btn btn-outline-primary'
                                                            id="renderSearchEntityAttributeSetGroupButton"
                                                            onclick='renderSearchEntityAttributeSetGroup(event)'>
                                                        <lang>搜索【实体-属性集-属性组】</lang>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class='row'>
                                            <div class='mx-auto col-lg-6 mt-2 mb-4'>
                                                <div class='input-group'>
                                                    <select id='search-entity-attribute-set-group-result' class='form-select form-control rounded'
                                                            size='10'
                                                            name='group_code'
                                                            data-style='btn-primary' data-width='fit'
                                                            aria-label='@lang{搜索【实体-属性集-属性组】结果}'
                                                            aria-describedby='search-addon' required>
                                                        <foreach name='groups'>
                                                            <option value='{{v.code}}' @if{eav_entity_attribute_set_group.code===v.code=>'selected'}>
                                                                {{v.name}}
                                                            </option>
                                                        </foreach>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class='tab-pane' id='progress-attribute-details'>
                                <form class='needs-validation' novalidate='' action='{{action}}' method='post'>
                                    <input type='hidden' name='selected' value='@if{attribute.has_option=>1|0}'>
                                    <input type='hidden' name='progress' value="progress-attribute-details">
                                    <input type='hidden' name='next_progress' value="@if{attribute
                                    .has_option==='1'=>'progress-attribute-option'|'progress_submit'}">
                                    <div class='row'>
                                        <div class='col-lg-6'>
                                            <div class='mb-3'>
                                                <label class='form-label' for='progress-attribute-code'>
                                                    <lang>属性代码</lang>
                                                </label>
                                                <input type='text' class='form-control' id='progress-attribute-code'
                                                       name="code" value="{{attribute.code}}"
                                                       maxlength='60' data-parsley-minlength='3' placeholder="@lang{属性代码}" required>
                                                <div class='valid-feedback'>
                                                    <lang>填写正确！</lang>
                                                </div>
                                                <div class='valid-feedback'>
                                                    <lang>请正确填写正确属性代码，最小长度3个字符，最大长度60个字符</lang>
                                                </div>
                                            </div>
                                        </div>
                                        <div class='col-lg-6'>
                                            <div class='mb-3'>
                                                <label class='form-label' for='progress-attribute-name'>
                                                    <lang>属性名</lang>
                                                </label>
                                                <input type='text' class='form-control' id='progress-attribute-name' name='name'
                                                       value="{{attribute.name}}"
                                                       maxlength='128' data-parsley-minlength='3' placeholder='@lang{属性名}' required>
                                                <div class='valid-feedback'>
                                                    <lang>填写正确！</lang>
                                                </div>
                                                <div class='valid-feedback'>
                                                    <lang>请正确填写正确属性代码，最小长度3个字符，最大长度128个字符</lang>
                                                </div>
                                            </div>
                                        </div>
                                        <div class='col-lg-6'>
                                            <div class='mb-3'>
                                                <label class='form-label' for='validationType'>
                                                    <lang>属性类型</lang>
                                                </label>
                                                <select class='form-control' id='validationType' name='type' required='' @if{attribute.attribute_id=>'disabled'}>
                                                    <foreach name='types' item='type'>
                                                        <option value='{{type.code}}' @if{attribute.type== type.code=>'selected'}>
                                                            {{type.name}}
                                                        </option>
                                                    </foreach>
                                                </select>
                                                <div class='invalid-feedback'>
                                                    <lang>必须选择一个类型</lang>
                                                </div>
                                            </div>
                                        </div>
                                        <div class='col-lg-6'>
                                            <div class='mb-3'>
                                                <label class='form-label' for='validationEnable'>
                                                    <lang>是否启用</lang>
                                                </label>
                                                <select class='form-control' id='validationEnable' required=''
                                                        name='is_enable'>
                                                    <option value='0'
                                                            @if{attribute.is_enable== 0=>'selected'}>
                                                        <lang>禁用</lang>
                                                    </option>
                                                    <option value='1'
                                                            @if{attribute.is_enable== 1=>'selected'}>
                                                        <lang>启用</lang>
                                                    </option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class='col-lg-12'>
                                            <!--高级信息-->
                                            <div class='accordion mb-3' id='accordionAdvanced'>
                                                <div class='accordion-item'>
                                                    <h2 class='accordion-header' id='headingOne'>
                                                        <button class='accordion-button' type='button' data-bs-toggle='collapse'
                                                                data-bs-target='#collapseAdvanced'
                                                                aria-expanded='true' aria-controls='collapseAdvanced'>
                                                            <lang>高级设置</lang>
                                                        </button>
                                                    </h2>
                                                    <div id='collapseAdvanced' class='accordion-collapse collapse show'
                                                         aria-labelledby='headingAdvanced'
                                                         data-bs-parent='#accordionAdvanced'>
                                                        <div class='accordion-body'>
                                                            <div class='row'>
                                                                <div class='col-md-4'>
                                                                    <div class='mb-3'>
                                                                        <label class='form-label' for='validationType'>
                                                                            <lang>是否多值</lang>
                                                                        </label>
                                                                        <select class='form-control' id='validationType' required=''
                                                                                name='multiple_valued'
                                                                                @if{attribute.attribute_id=>'disabled'}>
                                                                            <option value='0' @if{attribute.multiple_valued== 0=>'selected'}>单值
                                                                            </option>
                                                                            <option value='1' @if{attribute.multiple_valued== 1=>'selected'}>多值
                                                                            </option>
                                                                        </select>
                                                                        <div class='invalid-feedback'>
                                                                            <lang>必须选择一个多值类型</lang>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class='col-md-4'>
                                                                    <div class='mb-3'>
                                                                        <label class='form-label' for='validationOption'>
                                                                            <lang>是否有配置项</lang>
                                                                        </label>
                                                                        <select class='form-control' id='validationOption' required=''
                                                                                name='has_option'
                                                                                @if{attribute.attribute_id=>'disabled'}>
                                                                            <option value='0'
                                                                                    @if{attribute.has_option== 0=>'selected'}>
                                                                                <lang>没有特定配置项</lang>
                                                                            </option>
                                                                            <option value='1'
                                                                                    @if{attribute.has_option== 1=>'selected'}>
                                                                                <lang>有特定配置项</lang>
                                                                            </option>
                                                                        </select>
                                                                        <span class='help-block'><lang>有配置项则只能选择配置项内设置的值，没有配置项可以输入任意值。</lang></span>
                                                                    </div>
                                                                </div>
                                                                <div class='col-md-4'>
                                                                    <div class='mb-3'>
                                                                        <label class='form-label' for='validationSystem'>
                                                                            <lang>是否是系统生成</lang>
                                                                        </label>
                                                                        <select class='form-control' id='validationSystem' required=''
                                                                                name='is_system'
                                                                                disabled>
                                                                            <option value='0'
                                                                                    @if{attribute.is_system== 0=>'selected'}>
                                                                                <lang>非系统属性</lang>
                                                                            </option>
                                                                            <option value='1'
                                                                                    @if{attribute.is_system== 1=>'selected'}>
                                                                                <lang>系统属性</lang>
                                                                            </option>
                                                                        </select>
                                                                        <span class='help-block'><lang>仅做标记是否由系统生成，或者非系统生成（用户自定义）。</lang></span>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <notempty name='attribute.has_option'>
                                <div class='tab-pane' id='progress-attribute-option'>
                                    <form class='needs-validation' novalidate='' action='{{action}}' method='post'>
                                        <input type='hidden' name='selected' value='@if{attribute_option=>1|0}'>
                                        <input type='hidden' name='progress' value='progress-attribute-details'>
                                        <input type='hidden' name='next' value='progress_submit'>
                                        <div class='row'>
                                            <div class='col-lg-12'>
                                               <!--FIXME 生成一个表，记录属性options -->

                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </notempty>
                        </div>
                        <ul class='pager wizard twitter-bs-wizard-pager-link'>
                            <li class='previous'><a href='javascript: void(0);'>
                                    <lang>返回上一步</lang>
                                </a></li>
                            <li class='next'><a href='javascript: void(0);'>
                                    <lang>下一步</lang>
                                </a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end row -->
</div>
<!-- END layout-wrapper -->
<!--右边栏-->
@template(Weline_Admin::common/right-sidebar.phtml)

@template(Weline_Admin::common/footer.phtml)
<!-- twitter-bootstrap-wizard js -->
<script src='@static(Weline_Admin::assets/libs/twitter-bootstrap-wizard/jquery.bootstrap.wizard.min.js)'></script>

<script src='@static(Weline_Admin::assets/libs/twitter-bootstrap-wizard/prettify.js)'></script>

<!-- form wizard init -->
<script src='@static(Weline_Eav::js/pages/attribute-add/form-wizard.init.js)'></script>
<!-- Sweet Alerts js -->
<script src='@static(Weline_Admin::assets/libs/sweetalert2/sweetalert2.min.js)'></script>

<!-- Sweet alert init js-->
<script src='@static(Weline_Admin::assets/js/pages/sweet-alerts.init.js)'></script>
<script>

    function getEntityCode() {
        let entity_code = '{{eav_entity.code}}';
        if (entity_code === '') {
            entity_code = $('#progress-select-entity').find('option:selected').val()
        }
        return entity_code;
    }

    function getSetCode() {
        let set_code = '{{eav_entity_attribute_set.code}}';
        if (set_code === '') {
            set_code = $('#progress-select-set').find('option:selected').val()
        }
        return set_code;
    }

    function getGroupCode() {
        let group_code = '{{eav_entity_attribute_set_group.code}}';
        if (group_code === '') {
            group_code = $('#progress-select-group').find('option:selected').val()
        }
        return group_code;
    }

    /*实体搜索*/
    function renderSearchEntities(e) {
        let search_entity = $(e.target)
        let search = search_entity.val()
        $.ajax({
            url: '@backend-url("*/backend/entity/search")?search=' + search,
            success: function (res) {
                let items = res['items']
                let search_entity_result = $('#search-entity-result')
                search_entity_result.empty()
                for (const item of items) {
                    search_entity_result.append(`<option value="${item.code}">${item.name}</option>`)
                }
                $('#progress-select-entity').find('input[name=\'selected\']').val(0)
            }
        })
    }

    /* 实体属性集搜索 */
    function renderSearchEntityAttributeSet(e) {
        let search = $(e.target)
        search = search.val()
        let entity_code = getEntityCode()
        $.ajax({
            url: '@backend-url("*/backend/attribute/set/search")?search=' + search + '&entity_code=' + entity_code,
            success: function (res) {
                if (res['msg']) {
                    Swal.fire(
                        {
                            title: '警告！',
                            text: res['msg'],
                            icon: 'error',
                            dangerMode: true,
                            confirmButtonText: '@lang{好的}'
                        }
                    )
                    return false;
                }
                let items = res['items']
                let search_entity_attribute_set_result = $('#search-entity-attribute-set-result')
                search_entity_attribute_set_result.empty()
                for (const item of items) {
                    search_entity_attribute_set_result.append(`<option value="${item.code}">${item.name}</option>`)
                }
                $('#progress-select-set').find('input[name=\'selected\']').val(0)
            }
        })
    }

    /* 实体属性集属性组 */
    function renderSearchEntityAttributeSetGroup(e) {
        let search = $(e.target)
        search = search.val()
        let entity_code = getEntityCode()
        let set_code = getSetCode()
        $.ajax({
            url: '@backend-url("*/backend/attribute/group/search")?search=' + search +
                '&entity_code=' + entity_code + '&set_code=' + set_code,
            success: function (res) {
                if (res['msg']) {
                    Swal.fire(
                        {
                            title: '警告！',
                            text: res['msg'],
                            icon: 'error',
                            dangerMode: true,
                            confirmButtonText: '@lang{好的}'
                        }
                    )
                    return false;
                }
                let items = res['items']
                let search_entity_attribute_set_result = $('#search-entity-attribute-set-group-result')
                search_entity_attribute_set_result.empty()
                for (const item of items) {
                    search_entity_attribute_set_result.append(`<option value="${item.code}">${item.name}</option>`)
                }
                $('#rogress-select-group').find('input[name=\'selected\']').val(0)
            }
        })
    }

    /*监听实体选择*/
    $('#search-entity-result').on('change', (e) => {
        let target = $(e.target).find('option:selected')
        let stepHelper = $('a[class="nav-link active"]')
        stepHelper.find('.help-block').remove()
        stepHelper.append(`<span class="help-block">
                                            ${__('你选择了')}
                                            <span class="text-primary">${target.text()}</span>
                                        </span>`)
        // 渲染下一个
        $('#renderSearchEntityAttributeSetButton').click()
    })
    /*监听属性集选择*/
    $('#search-entity-attribute-set-result').on('change', (e) => {
        let target = $(e.target).find('option:selected')
        let stepHelper = $('a[class="nav-link active"]')
        stepHelper.find('.help-block').remove()
        stepHelper.append(`<span class="help-block">
                                            ${__('你选择了')}
                                            <span class="text-primary">${target.text()}</span>
                                        </span>`)
        // 渲染下一个
        $('#renderSearchEntityAttributeSetGroupButton').click()
    })
    /*监听属性组选择*/
    $('#search-entity-attribute-set-group-result').on('change', (e) => {
        let target = $(e.target).find('option:selected')
        let stepHelper = $('a[class="nav-link active"]')
        stepHelper.find('.help-block').remove()
        stepHelper.append(`<span class="help-block">
                                            ${__('你选择了')}
                                            <span class="text-primary">${target.text()}</span>
                                        </span>`)
    })
    // 初始化选中步骤
    $(document).ready(() => {
        $('.twitter-bs-wizard-nav .nav-link[data-target="1"]').tab('show')

        /*延迟期间最多执行一次：优化输入请求过多ajax*/
        function debounce(func, delay) {
            let timeoutId;
            return function (...args) {
                if (timeoutId) {
                    clearTimeout(timeoutId);
                }
                timeoutId = setTimeout(() => {
                    func.apply(this, args);
                    timeoutId = null;
                }, delay);
            };
        }

        function throttle(func, delay) {
            let timeoutId;
            let lastExecTime = 0;
            return function (...args) {
                const elapsedTime = new Date().getTime() - lastExecTime;
                if (elapsedTime > delay) {
                    lastExecTime = new Date().getTime();
                    func.apply(this, args);
                } else {
                    clearTimeout(timeoutId);
                    timeoutId = setTimeout(() => {
                        lastExecTime = new Date().getTime();
                        func.apply(this, args);
                        timeoutId = null;
                    }, delay - elapsedTime);
                }
            };
        }

        /*监听属性代码是否可用*/
        const throttledProgressAttributeCode = debounce((e) => {
            let search = $(e.target).val()
            let name = $('#progress-attribute-name').val()
            let stepHelper = $('a[class="nav-link active"]')
            stepHelper.find('.help-block').remove()
            stepHelper.append(`<span class="help-block">
                                            ${__('你选择了')}
                                            <span class="text-primary">${search}(${name})</span>
                                        </span>`)
            $.ajax({
                url: '@backend-url("*/backend/attribute/search")?field=code&limit=1&search=' + search +
                    '&entity_code=' + getEntityCode() + '&set_code=' + getSetCode() + '&group_code=' + getGroupCode(),
                success: function (res) {
                    if (res['msg']) {
                        Swal.fire(
                            {
                                title: '警告！',
                                text: res['msg'],
                                icon: 'error',
                                dangerMode: true,
                                confirmButtonText: '@lang{好的}'
                            }
                        )
                        return false;
                    }
                    let items = res['items']
                    let attribute_code_input = $('#progress-attribute-code')
                    if (items.length) {
                        attribute_code_input.removeClass('border-success')
                        attribute_code_input.addClass('border-danger')
                    } else {
                        attribute_code_input.removeClass('border-danger')
                        attribute_code_input.addClass('border-success')
                    }
                }
            })
        }, 500);
        $('#progress-attribute-code').on('input', throttledProgressAttributeCode)
        /*监听属性名称是否可用*/
        const throttledProgressAttributeName = debounce((e) => {
            let search = $(e.target).val()
            let code = $('#progress-attribute-code').val()
            let stepHelper = $('a[class="nav-link active"]')
            stepHelper.find('.help-block').remove()
            stepHelper.append(`<span class="help-block">
                                            ${__('属性数据')}
                                            <span class="text-primary">${code}(${search})</span>
                                        </span>`)
            $.ajax({
                url: '@backend-url("*/backend/attribute/search")?field=name&limit=1&search=' + search +
                    '&entity_code=' + getEntityCode() + '&set_code=' + getSetCode() + '&group_code=' + getGroupCode(),
                success: function (res) {
                    if (res['msg']) {
                        Swal.fire(
                            {
                                title: '警告！',
                                text: res['msg'],
                                icon: 'error',
                                dangerMode: true,
                                confirmButtonText: '@lang{好的}'
                            }
                        )
                        return false;
                    }
                    let items = res['items']
                    let attribute_code_input = $('#progress-attribute-name')
                    if (items.length) {
                        attribute_code_input.removeClass('border-success')
                        attribute_code_input.addClass('border-danger')
                    } else {
                        attribute_code_input.removeClass('border-danger')
                        attribute_code_input.addClass('border-success')
                    }
                }
            })
        }, 500);
        $('#progress-attribute-name').on('input', throttledProgressAttributeName)

        // 选择切换配置项时 调整 progress-submit
        let changeOptionConfig = $('#validationOption')
        changeOptionConfig.change((e) => {
            // 获取当前选中的值
            var selectedValue = $(e.target).find('option:selected').val();
            // 如果选中1 说明需要配置配置项
            let attribute_detail_container = $('#progress-attribute-details')
            let form = attribute_detail_container.find('form')
            if (form.get(0).reportValidity()) {
                if(selectedValue === '1'){
                    form.find('input[name="progress"]').val('progress-attribute-details')
                    form.find('input[name="next_progress"]').val('progress-attribute-option')
                }
                form.submit()
            }
        })
    })

</script>
</body>
</html>
