<?php
/**
 * @var $this \Weline\Framework\View\Template
 */
?>
<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_TEMPLATE,trim("Weline_Backend::public/header.phtml"));// 读取资源文件 ?>
<link rel="stylesheet" href="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("Weline_Admin::backend/css/login_type2.css"));// 读取资源文件 ?>">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-lg-3 col-md-2"></div>
        <div class="col-lg-6 col-md-8 login-box">
            <div class="col-lg-12 login-key">
                <i class="fa fa-key" aria-hidden="true"></i>
            </div>
            <div class="col-lg-12 login-title">
                Weline Admin 面板
            </div>
            <div class="col-lg-12 login-form">
                <div class="col-lg-12 login-form">
                    <form method="post" action="<?= $this->getData('post_url') ?>">
                        <?= $this->getFormKey($this->getData('post_url')) ?>
                        <div class="form-group">
                            <label class="form-control-label"><?= __('用户名：') ?>
                                <input name="username" type="text" class="form-control" value="admin">
                            </label>
                        </div>
                        <div class="form-group">
                            <label class="form-control-label"><?= __('密码：') ?>
                                <input name="password" type="password" class="form-control" value="admin">
                            </label>
                        </div>
                        <?php if ($this->getData('need_backend_verification_code')) {
                            ?>
                            <div class="form-group">
                                <img src="<?= $this->getData('backend_verification_code_url') ?>" alt="">
                                <label class="form-control-label"><?= __('验证码：') ?>
                                    <input name="code" type="text" class="form-control" value=""
                                           placeholder="<?= __('请输入验证码！') ?>" required>
                                </label>
                            </div>
                            <?php
                        } ?>
                        <div class="col-lg-12 loginbttm">
                            <div class="col-lg-6 login-btm login-text">
                                <?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_TEMPLATE,trim("Weline_Component::message.phtml"));// 读取资源文件 ?>
                            </div>
                            <?php
                            /**@var \Weline\Framework\Session\Session $session */
                            $session = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Framework\Session\Session::class);
                            ?>
                            <div class="col-lg-6 login-btm login-button">
                                <button type="submit"
                                        class="btn btn-outline-primary <?php if ($session->getData('backend_disable_login')) echo 'disable' ?>"><?= __('登 录') ?></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-3 col-md-2"></div>
        </div>
    </div>
</body>
<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_TEMPLATE,trim("Weline_Backend::public/footer.phtml"));// 读取资源文件 ?>