<?php
/**
 * @var $this \Weline\Framework\View\Template
 */?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="Shortcut Icon" href="\Aiweline\HelloWorld\view\statics\/img/favicon.png">
    <link rel="Shortcut Icon" href="\Aiweline\HelloWorld\view\statics\/img/favicon.png">
    <link rel="Bookmark" href="\Aiweline\HelloWorld\view\statics\/img/favicon.png">
    <link href="\Aiweline\HelloWorld\view\statics\/css/header.css" type="text/css" rel="stylesheet">
    <title>欢迎加入 M Framework 的世界! 发现不一样的世界！</title>
    <?php
    /**
     * @var $this \Weline\Framework\View\Template
     */
    ?>
    <link href="\Aiweline\HelloWorld\view\statics\/css/index.css" type="text/css" rel="stylesheet">
    <script src="\Aiweline\HelloWorld\view\statics\/js/demo.js"></script>
</head>
<div class="header">
    我是头部
</div>