<?php
/**@var \Weline\Backend\Block\Menu $block */
$block = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\Menu::class);
$menus = $block->getMenus();
if (count($menus) > 0):
    ?>
    <div class="menu">
        <ul>
            <?php
            foreach ($menus as $menu) {
                ?>
                <li class="menu-item"><a href="<?=$menu->getUrl()?>"><?=$menu->getName()?></a></li>
                <?php
            }
            ?>
        </ul>
    </div>
<?php
endif; ?>