<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang='en' <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    @template(Weline_Admin::common/head.phtml)
    <!-- jvectormap -->
    <link href="@static(Weline_Admin::assets/libs/jqvmap/jqvmap.min.css)" rel="stylesheet"/>
    <!-- jquery.mCustomScrollbar 插件 -->
    <link href="@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.css)" rel="stylesheet"/>
    <!-- Sweet Alert-->
    <link href='@static(Weline_Admin::assets/libs/sweetalert2/sweetalert2.min.css)' rel='stylesheet' type='text/css'/>
    <title><?= __('Weline Admin 管理面板') ?></title>
</head>

<body <?= $themeConfig->getLayouts() ?? ''; ?>>

<!--页头工具条 开始-->
@template(Weline_Admin::common/page/loading.phtml)
<!--页头工具条 结束-->

<!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- 开始 页面 -->
<div id="layout-wrapper">


    <!--页头工具条 开始-->
    <w:block class='Weline\Admin\Block\Backend\Page\Topbar' module='300'/>
    <!--页头工具条 结束-->

    <!-- ========== Topnav Start ========== -->
    <!--页头菜单栏 开始-->
    <w:block class='Weline\Admin\Block\Backend\Page\Topnav' module='300'/>
    <!--页头菜单栏 结束-->

    <!--左侧菜单栏 开始-->
    @template(Weline_Admin::common/left-sidebar.phtml)
    <!--左侧菜单栏 结束-->

    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class="page-content">
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <h4 class="mb-sm-0"><?= __('模组管理') ?></h4>

                            <div class="page-title-right">
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="javascript: void(0);"><?= __('系统') ?></a></li>
                                    <li class="breadcrumb-item active"><?= __('模组管理') ?></li>
                                </ol>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- end page title -->

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                <h4 class="card-title"><?= __('模组控制器') ?>:
                                    <lang>一共有</lang>
                                    <var>total</var>
                                    <lang>条数据</lang>
                                </h4>

                                <!--<div class="table-responsive mCustomScrollbar" data-mcs-axis="yx" data-mcs-theme='dark'
                                     style="height: 800px">-->
                                <div class='table-responsive mCustomScrollbar' data-mcs-axis='x'
                                     data-mcs-theme='dark'>
                                    <table class="table table-editable table-nowrap align-middle table-edits">
                                        <thead>
                                        <tr>
                                            <th>
                                                <lang>ID</lang>
                                            </th>
                                            <th>
                                                <lang>模组</lang>
                                            </th>
                                            <th>
                                                <lang>状态</lang>
                                            </th>
                                            <th>
                                                <lang>描述</lang>
                                            </th>
                                            <th>
                                                <lang>类型</lang>
                                            </th>
                                            <th>
                                                <lang>基础命名空间</lang>
                                            </th>
                                            <th>
                                                <lang>基础路径</lang>
                                            </th>
                                            <th>
                                                <lang>上一个版本</lang>
                                            </th>
                                            <th>
                                                <lang>当前版本</lang>
                                            </th>
                                            <th>
                                                <lang>路由</lang>
                                            </th>
                                            <th>
                                                <lang>创建时间</lang>
                                            </th>
                                            <th>
                                                <lang>更新时间</lang>
                                            </th>
                                            <th><?= __('操作') ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <foreach name="modules" item="module">
                                            <tr>
                                                <td><var>$module->getId()</var></td>
                                                <td><var>$module->getName()</var></td>
                                                <td>
                                                    <if condition="module.status">
                                                        <b class="text-success">
                                                            <lang>启用</lang>
                                                        </b>
                                                        <else/>
                                                        <b class="text-danger">
                                                            <lang>禁用</lang>
                                                        </b>
                                                    </if>
                                                </td>
                                                <td>
                                                    <string>$module->getDescription()|50</string>
                                                </td>
                                                <td @if{$module->getPosition() ==='system'=>"class='disabled text-danger'"}>
                                                    <if condition="module.position === 'app'">
                                                        <lang>第三方</lang>
                                                        <elseif condition="module.position === 'composer'"/>
                                                        <lang>Composer</lang>
                                                        <else/>
                                                        <lang>系统</lang>
                                                    </if>
                                                </td>
                                                <td><var>$module->getNamespacePath()</var></td>
                                                <td><var>$module->getBasePath()</var></td>
                                                <td><var>$module->getLastVersion()</var></td>
                                                <td><var>$module->getVersion()</var></td>
                                                <td><var>$module->getRouter()</var></td>
                                                <td><var>$module->getCreateTime()</var></td>
                                                <td>{{$module->getUpdateTime()}}</td>
                                                <td style='width: 100px'>
                                                    <input class='form-check form-switch' type='checkbox'
                                                           alt="@var{$module->getStatus()?__('开启'):__('关闭')}"
                                                           id='@var{$module->getName()}' switch='bool' @if{$module->getStatus()=>'checked'}
                                                    @if{$module->getPosition()==='system'=>'disabled'}>
                                                    <label class='form-label' for='@var{$module->getName()}'
                                                           data-on-label='<?= __('开启') ?>'
                                                           data-off-label='<?= __('关闭') ?>'>
                                                    </label>
                                                </td>
                                            </tr>
                                        </foreach>
                                        </tbody>
                                    </table>
                                    <div>
                                        <var>pagination</var>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> <!-- end col -->
                </div> <!-- end row -->
            </div> <!-- container-fluid -->
        </div>
        <!-- End Page-content -->

        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <script>document.write(new Date().getFullYear())</script>
                        © Weline.
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end d-none d-sm-block">
                            Crafted with <i class="mdi mdi-heart text-danger"></i> By <a
                                    href="https://www.aiweline.com/">秋枫雁飞(aiweline)</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>
    <!-- end main content-->

</div>
<!-- END layout-wrapper -->
<!--右边栏-->
@template(Weline_Admin::common/right-sidebar.phtml)

<!-- Table Editable plugin -->
<script src="@static(Weline_Admin::assets/libs/table-edits/build/table-edits.min.js)"></script>
<script src="@static(Weline_Admin::assets/js/pages/menus/table-editable.init.js)"></script>
<script src='@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js)'></script>
<!-- Sweet Alerts js -->
<script src='@static(Weline_Admin::assets/libs/sweetalert2/sweetalert2.min.js)'></script>

<!-- Sweet alert init js-->
<js>Weline_Admin::assets/js/pages/menus/sweet-alerts.init.js</js>
@template(Weline_Admin::common/footer.phtml)
<script>
    $('.form-switch').bind('input propertychange', (e) => {
        let input = $(e.target);
        let id = input.attr('id');
        let value = input.is(':checked');
        let url = '@admin-url("module-manager/backend/module/status")';
        let data = {
            module: id,
            status: value
        };
        $.post(url, data, (res) => {
            if (res.code === 200) {
                input.prop('checked', res.data);
                //SweetAlert 提示 成功 自动关闭
                Swal.fire({
                    title: '操作成功',
                    text: res.msg,
                    type: 'success',
                }).then(() => {
                    window.location.reload();
                });
            } else {
                input.prop('checked', !res.data);
            }
        });
    })
</script>
</body>
</html>
