<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Admin\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Admin\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang="en" <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?> class='no-js'>
<head>
    <title><lang>Weline Admin 管理面板</lang></title>
    <!--模板Weline_Admin::common/head.phtml-->
    <w-template>Weline_Admin::common/head.phtml</w-template>
    <!-- jvectormap -->
    <w-css>Weline_Admin::assets/libs/jqvmap/jqvmap.min.css</w-css>
    <!-- Responsive Table css -->
    <link href='@static(Weline_Admin::assets/libs/admin-resources/rwd-table/rwd-table.min.css)' rel='stylesheet'
          type='text/css'/>
</head>

<!--<body data-sidebar="dark" data-topbar='colored' data-layout='horizontal'>-->
<body <?= $themeConfig->getLayouts() ?? ''; ?>>
<!--加载中组件 开始-->
@template(Weline_Admin::common/page/loading.phtml)
<!-- 开始 页面 -->
<div id="layout-wrapper">

    <!--页头工具条 开始-->
    @template(Weline_Admin::common/page/topbar.phtml)
    <!--页头工具条 结束-->

    <!-- ========== Left Sidebar Start ========== -->
    <!--左侧菜单栏 开始-->
    @template(Weline_Admin::common/left-sidebar.phtml)
    <!--左侧菜单栏 结束-->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class="page-content" style="min-height: 800px">
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <h4 class="mb-sm-0">
                                <lang>开发文档管理器</lang>
                            </h4>

                            <div class="page-title-right">
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="javascript: void(0);">
                                            <lang>系统</lang>
                                        </a></li>
                                    <li class="breadcrumb-item active">
                                        <lang>开发文档管理器</lang>
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end page title -->
                <div class="row">
                    <div class='col-xl-3 col-sm-3'>
                        <div class='card'>
                            <div class='card-body'>
                                <div class='d-flex text-muted'>
                                    <div class='flex-shrink-0 me-3 align-self-center' style='position: relative;'>
                                        <div id='radialchart-1' class='apex-charts' dir='ltr'
                                             style='min-height: 73px;'>
                                            <div id='apexcharts9hss70qz'
                                                 class='apexcharts-canvas apexcharts9hss70qz apexcharts-theme-light'
                                                 style='width: 72px; height: 73px;'>
                                                <svg id='SvgjsSvg1001' width='72' height='73'
                                                     xmlns='http://www.w3.org/2000/svg' version='1.1'
                                                     xmlns:xlink='http://www.w3.org/1999/xlink'
                                                     xmlns:svgjs='http://svgjs.com/svgjs' class='apexcharts-svg'
                                                     xmlns:data='ApexChartsNS' transform='translate(0, 0)'
                                                     style='background: transparent;'>
                                                    <g id='SvgjsG1003' class='apexcharts-inner apexcharts-graphical'
                                                       transform='translate(0, 0)'>
                                                        <defs id='SvgjsDefs1002'>
                                                            <clipPath id='gridRectMask9hss70qz'>
                                                                <rect id='SvgjsRect1005' width='78' height='74'
                                                                      x='-3' y='-1' rx='0' ry='0' opacity='1'
                                                                      stroke-width='0' stroke='none'
                                                                      stroke-dasharray='0' fill='#fff'></rect>
                                                            </clipPath>
                                                            <clipPath id='gridRectMarkerMask9hss70qz'>
                                                                <rect id='SvgjsRect1006' width='76' height='76'
                                                                      x='-2' y='-2' rx='0' ry='0' opacity='1'
                                                                      stroke-width='0' stroke='none'
                                                                      stroke-dasharray='0' fill='#fff'></rect>
                                                            </clipPath>
                                                        </defs>
                                                        <g id='SvgjsG1007' class='apexcharts-radialbar'>
                                                            <g id='SvgjsG1008'>
                                                                <g id='SvgjsG1009' class='apexcharts-tracks'>
                                                                    <g id='SvgjsG1010'
                                                                       class='apexcharts-radialbar-track apexcharts-track'
                                                                       rel='1'>
                                                                        <path id='apexcharts-radialbarTrack-0'
                                                                              d='M 36 8.780487804878046 A 27.219512195121954 27.219512195121954 0 1 1 35.9952492989382 8.780488219454924'
                                                                              fill='none' fill-opacity='1'
                                                                              stroke='rgba(242,242,242,0.85)'
                                                                              stroke-opacity='1'
                                                                              stroke-linecap='round'
                                                                              stroke-width='5.1102439024390245'
                                                                              stroke-dasharray='0'
                                                                              class='apexcharts-radialbar-area'
                                                                              data:pathOrig='M 36 8.780487804878046 A 27.219512195121954 27.219512195121954 0 1 1 35.9952492989382 8.780488219454924'></path>
                                                                    </g>
                                                                </g>
                                                                <g id='SvgjsG1012'>
                                                                    <g id='SvgjsG1016'
                                                                       class='apexcharts-series apexcharts-radial-series'
                                                                       seriesName='seriesx1' rel='1'
                                                                       data:realIndex='0'>
                                                                        <path id='SvgjsPath1017'
                                                                              d='M 36 8.780487804878046 A 27.219512195121954 27.219512195121954 0 1 1 9.280586909083095 41.19372777659083'
                                                                              fill='none' fill-opacity='0.85'
                                                                              stroke='rgba(10,179,156,0.85)'
                                                                              stroke-opacity='1'
                                                                              stroke-linecap='round'
                                                                              stroke-width='5.2682926829268295'
                                                                              stroke-dasharray='0'
                                                                              class='apexcharts-radialbar-area apexcharts-radialbar-slice-0'
                                                                              data:angle='259' data:value='72'
                                                                              index='0' j='0'
                                                                              data:pathOrig='M 36 8.780487804878046 A 27.219512195121954 27.219512195121954 0 1 1 9.280586909083095 41.19372777659083'></path>
                                                                    </g>
                                                                    <circle id='SvgjsCircle1013'
                                                                            r='24.664390243902442' cx='36' cy='36'
                                                                            class='apexcharts-radialbar-hollow'
                                                                            fill='transparent'></circle>
                                                                    <g id='SvgjsG1014'
                                                                       class='apexcharts-datalabels-group'
                                                                       transform='translate(0, 0) scale(1)'
                                                                       style='opacity: 1;'>
                                                                        <text id='SvgjsText1015'
                                                                              font-family='Helvetica, Arial, sans-serif'
                                                                              x='36' y='41' text-anchor='middle'
                                                                              dominant-baseline='auto'
                                                                              font-size='14px' font-weight='400'
                                                                              fill='#373d3f'
                                                                              class='apexcharts-text apexcharts-datalabel-value'
                                                                              style='font-family: Helvetica, Arial, sans-serif;'>
                                                                            72%
                                                                        </text>
                                                                    </g>
                                                                </g>
                                                            </g>
                                                        </g>
                                                        <line id='SvgjsLine1018' x1='0' y1='0' x2='72' y2='0'
                                                              stroke='#b6b6b6' stroke-dasharray='0' stroke-width='1'
                                                              class='apexcharts-ycrosshairs'></line>
                                                        <line id='SvgjsLine1019' x1='0' y1='0' x2='72' y2='0'
                                                              stroke-dasharray='0' stroke-width='0'
                                                              class='apexcharts-ycrosshairs-hidden'></line>
                                                    </g>
                                                    <g id='SvgjsG1004' class='apexcharts-annotations'></g>
                                                </svg>
                                                <div class='apexcharts-legend'></div>
                                            </div>
                                        </div>
                                        <div class='resize-triggers'>
                                            <div class='expand-trigger'>
                                                <div style='width: 73px; height: 74px;'></div>
                                            </div>
                                            <div class='contract-trigger'></div>
                                        </div>
                                    </div>
                                    <div class='flex-grow-1 overflow-hidden'>
                                        <p class='mb-1'>Users</p>
                                        <h5 class='mb-3'>2.2k</h5>
                                        <p class='text-truncate mb-0'><span class='text-success me-2'> 0.02% <i
                                                        class='ri-arrow-right-up-line align-bottom ms-1'></i></span>
                                            From previous</p>
                                    </div>
                                </div>
                            </div>
                            <!-- end card-body -->
                        </div>
                        <!-- end card -->
                    </div>
                    <div class='col-xl-3 col-sm-3'>
                        <div class='card'>
                            <div class='card-body'>
                                <div class='d-flex text-muted'>
                                    <div class='flex-shrink-0 me-3 align-self-center' style='position: relative;'>
                                        <div id='radialchart-1' class='apex-charts' dir='ltr'
                                             style='min-height: 73px;'>
                                            <div id='apexcharts9hss70qz'
                                                 class='apexcharts-canvas apexcharts9hss70qz apexcharts-theme-light'
                                                 style='width: 72px; height: 73px;'>
                                                <svg id='SvgjsSvg1001' width='72' height='73'
                                                     xmlns='http://www.w3.org/2000/svg' version='1.1'
                                                     xmlns:xlink='http://www.w3.org/1999/xlink'
                                                     xmlns:svgjs='http://svgjs.com/svgjs' class='apexcharts-svg'
                                                     xmlns:data='ApexChartsNS' transform='translate(0, 0)'
                                                     style='background: transparent;'>
                                                    <g id='SvgjsG1003' class='apexcharts-inner apexcharts-graphical'
                                                       transform='translate(0, 0)'>
                                                        <defs id='SvgjsDefs1002'>
                                                            <clipPath id='gridRectMask9hss70qz'>
                                                                <rect id='SvgjsRect1005' width='78' height='74'
                                                                      x='-3' y='-1' rx='0' ry='0' opacity='1'
                                                                      stroke-width='0' stroke='none'
                                                                      stroke-dasharray='0' fill='#fff'></rect>
                                                            </clipPath>
                                                            <clipPath id='gridRectMarkerMask9hss70qz'>
                                                                <rect id='SvgjsRect1006' width='76' height='76'
                                                                      x='-2' y='-2' rx='0' ry='0' opacity='1'
                                                                      stroke-width='0' stroke='none'
                                                                      stroke-dasharray='0' fill='#fff'></rect>
                                                            </clipPath>
                                                        </defs>
                                                        <g id='SvgjsG1007' class='apexcharts-radialbar'>
                                                            <g id='SvgjsG1008'>
                                                                <g id='SvgjsG1009' class='apexcharts-tracks'>
                                                                    <g id='SvgjsG1010'
                                                                       class='apexcharts-radialbar-track apexcharts-track'
                                                                       rel='1'>
                                                                        <path id='apexcharts-radialbarTrack-0'
                                                                              d='M 36 8.780487804878046 A 27.219512195121954 27.219512195121954 0 1 1 35.9952492989382 8.780488219454924'
                                                                              fill='none' fill-opacity='1'
                                                                              stroke='rgba(242,242,242,0.85)'
                                                                              stroke-opacity='1'
                                                                              stroke-linecap='round'
                                                                              stroke-width='5.1102439024390245'
                                                                              stroke-dasharray='0'
                                                                              class='apexcharts-radialbar-area'
                                                                              data:pathOrig='M 36 8.780487804878046 A 27.219512195121954 27.219512195121954 0 1 1 35.9952492989382 8.780488219454924'></path>
                                                                    </g>
                                                                </g>
                                                                <g id='SvgjsG1012'>
                                                                    <g id='SvgjsG1016'
                                                                       class='apexcharts-series apexcharts-radial-series'
                                                                       seriesName='seriesx1' rel='1'
                                                                       data:realIndex='0'>
                                                                        <path id='SvgjsPath1017'
                                                                              d='M 36 8.780487804878046 A 27.219512195121954 27.219512195121954 0 1 1 9.280586909083095 41.19372777659083'
                                                                              fill='none' fill-opacity='0.85'
                                                                              stroke='rgba(10,179,156,0.85)'
                                                                              stroke-opacity='1'
                                                                              stroke-linecap='round'
                                                                              stroke-width='5.2682926829268295'
                                                                              stroke-dasharray='0'
                                                                              class='apexcharts-radialbar-area apexcharts-radialbar-slice-0'
                                                                              data:angle='259' data:value='72'
                                                                              index='0' j='0'
                                                                              data:pathOrig='M 36 8.780487804878046 A 27.219512195121954 27.219512195121954 0 1 1 9.280586909083095 41.19372777659083'></path>
                                                                    </g>
                                                                    <circle id='SvgjsCircle1013'
                                                                            r='24.664390243902442' cx='36' cy='36'
                                                                            class='apexcharts-radialbar-hollow'
                                                                            fill='transparent'></circle>
                                                                    <g id='SvgjsG1014'
                                                                       class='apexcharts-datalabels-group'
                                                                       transform='translate(0, 0) scale(1)'
                                                                       style='opacity: 1;'>
                                                                        <text id='SvgjsText1015'
                                                                              font-family='Helvetica, Arial, sans-serif'
                                                                              x='36' y='41' text-anchor='middle'
                                                                              dominant-baseline='auto'
                                                                              font-size='14px' font-weight='400'
                                                                              fill='#373d3f'
                                                                              class='apexcharts-text apexcharts-datalabel-value'
                                                                              style='font-family: Helvetica, Arial, sans-serif;'>
                                                                            72%
                                                                        </text>
                                                                    </g>
                                                                </g>
                                                            </g>
                                                        </g>
                                                        <line id='SvgjsLine1018' x1='0' y1='0' x2='72' y2='0'
                                                              stroke='#b6b6b6' stroke-dasharray='0' stroke-width='1'
                                                              class='apexcharts-ycrosshairs'></line>
                                                        <line id='SvgjsLine1019' x1='0' y1='0' x2='72' y2='0'
                                                              stroke-dasharray='0' stroke-width='0'
                                                              class='apexcharts-ycrosshairs-hidden'></line>
                                                    </g>
                                                    <g id='SvgjsG1004' class='apexcharts-annotations'></g>
                                                </svg>
                                                <div class='apexcharts-legend'></div>
                                            </div>
                                        </div>
                                        <div class='resize-triggers'>
                                            <div class='expand-trigger'>
                                                <div style='width: 73px; height: 74px;'></div>
                                            </div>
                                            <div class='contract-trigger'></div>
                                        </div>
                                    </div>
                                    <div class='flex-grow-1 overflow-hidden'>
                                        <p class='mb-1'>Users</p>
                                        <h5 class='mb-3'>2.2k</h5>
                                        <p class='text-truncate mb-0'><span class='text-success me-2'> 0.02% <i
                                                        class='ri-arrow-right-up-line align-bottom ms-1'></i></span>
                                            From previous</p>
                                    </div>
                                </div>
                            </div>
                            <!-- end card-body -->
                        </div>
                        <!-- end card -->
                    </div>
                </div>
                <div class='row'>
                    <div class='col-12'>
                        <div class='card'>
                            <div class='card-body'>
                                <h4 class='card-title'>
                                    <lang>开发文档</lang>
                                </h4>
                                <p class='card-title-desc'>
                                    <lang>编写开发文档</lang>
                                </p>
                                <div class="panel card">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class='col-6 pull-left'>
                                            </div>
                                            <div class='col-6 button-items'>
                                                <a href="@admin_url('dev/tool/admin/document/catalog')">
                                                    <button type='button'
                                                            class='btn btn-info waves-effect waves-light pull-right'>
                                                        <lang>目录管理</lang>
                                                    </button>
                                                </a>
                                                <a href="@admin_url('dev/tool/admin/document/')">
                                                    <button type='button'
                                                            class='btn btn-success waves-effect waves-light pull-right'>
                                                        <lang>新增文章</lang>
                                                    </button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class='table-rep-plugin'>
                                    <div class='table-responsive mb-0' data-pattern='priority-columns'>
                                        <table id='tech-companies-1' class='table table-striped'>
                                            <thead>
                                            <tr>
                                                <foreach name="columns" key="k" item="v">
                                                    <th data-priority='@var($k)'
                                                        data-field="@var{$v->Field}"><var>$v->Comment</var>
                                                    </th>
                                                </foreach>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <foreach name="catalogs" item="vo">
                                                <tr>
                                                    <th><var>$vo->id</var></th>
                                                    <th><var>$vo->name</var></th>
                                                    <th><var>$vo->pid</var></th>
                                                    <th><var>$vo->create_time</var></th>
                                                    <th><var>$vo->update_time</var></th>
                                                </tr>
                                            </foreach>
                                            </tbody>
                                        </table>
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div> <!-- end col -->
                </div> <!-- end row -->
            </div>
            <!-- container-fluid -->
        </div>
        <!-- End Page-content -->

        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <script>document.write(new Date().getFullYear())</script>
                        © Weline.
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end d-none d-sm-block">
                            Crafted with <i class="mdi mdi-heart text-danger"></i> By <a
                                    href="https://www.aiweline.com/">秋枫雁飞(aiweline)</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>
    <!-- end main content-->

</div>
<!-- END layout-wrapper -->

<!--右边栏-->
@template(Weline_Admin::common/right-sidebar.phtml)
<!--tinymce js-->
<script src='@static(Weline_Admin::assets/libs/tinymce/tinymce.min.js)'></script>

<!-- init js -->
<script src='@static(Weline_Admin::assets/js/pages/form-editor.init.js)'></script>

<!-- Responsive Table js -->
<script src='@static(Weline_Admin::assets/libs/admin-resources/rwd-table/rwd-table.min.js)'></script>

<!-- Init js -->
<script src='@static(Weline_Admin::assets/js/pages/table-responsive.init.js)'></script>

<!--页脚-->
@template(Weline_Admin::common/footer.phtml)

<!-- jquery.vectormap map -->
<script src="@static(Weline_Admin::assets/libs/jqvmap/jquery.vmap.min.js)"></script>
<script src="@static(Weline_Admin::assets/libs/jqvmap/maps/jquery.vmap.usa.js)"></script>
</body>
</html>

