<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<?php echo framework_view_process_block([
    0 => 'Weline\\Backend\\Block\\Header\\Base',
]);?>
<!--加载require常用js模块-->
<!--<script src='/Weline/Frontend/view/statics/base/require.configs.js?v=73516'></script>-->
<script>
    window.site = {
        themeConfig:<?=json_encode($themeConfig->getThemeConfig()) ?? '{}';?>
    }
</script>