<?php
/**@var \Weline\Framework\View\Template $this*/
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $this->getData('title'); ?></title>
    <link rel="Shortcut Icon" href="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("Weline_Backend::img/favicon.png"));// 读取资源文件 ?>">
    <link rel="Shortcut Icon" href="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("Weline_Backend::img/favicon.png"));// 读取资源文件 ?>">
    <link rel="Bookmark" href="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("Weline_Backend::img/favicon.png"));// 读取资源文件 ?>">
    <!--css-->
    <link rel="stylesheet" href="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("Weline_Backend::backend/lib/bootstrap-4.6.0-dist/css/bootstrap.min.css"));// 读取资源文件 ?>">
    <link rel="stylesheet" href="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("Weline_Backend::backend/lib/font-awesome-4.7.0/css/font-awesome.min.css"));// 读取资源文件 ?>">
    <!--加载requirejs-->
    <?php if (DEV) : ?>
        <script src="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("Weline_Backend::backend/lib/requirejs/2.3.6/requirejs.js"));// 读取资源文件 ?>"></script>
    <?php
    else:
    ?>
        <script src="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("Weline_Backend::backend/lib/requirejs/2.3.6/requirejs.min.js"));// 读取资源文件 ?>"></script>
    <?php
    endif;
    ?>
    <!--加载require常用js模块-->
    <script src="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("Weline_Backend::base/require.configs.js"));// 读取资源文件 ?>"></script>
    <?php
    echo $this->getHeader()->getHtml();
    ?>
</head>

