<?php
/**
 * @var \Weline\Framework\View\Template $this
 */
?>
@template(Weline_Backend::public/header.phtml)
<link rel="stylesheet" href="@static(Weline_Admin::/css/login_type1.css)">
</head>
<body>
<div class="login">
    <h1>Login</h1>
    <form method="post">
        <input type="text" name="u" placeholder="Username" required="required"/>
        <input type="password" name="p" placeholder="Password" required="required"/>
        <button type="submit" class="btn btn-primary btn-block btn-large">Let me in.</button>
    </form>
</div>
</body>
@template(Weline_Backend::public/footer.phtml)