<?php
/**
 * @var $this \Weline\Framework\View\Template
 */
?>
<?php $this->getViewFile('templates/public/header.phtml'); ?>
    <link rel="stylesheet" href="@static/css/login_type1.css">
    </head>
    <body>
    <div class="login">
        <h1>Login</h1>
        <form method="post">
            <input type="text" name="u" placeholder="Username" required="required"/>
            <input type="password" name="p" placeholder="Password" required="required"/>
            <button type="submit" class="btn btn-primary btn-block btn-large">Let me in.</button>
        </form>
    </div>
    </body>
<?php $this->getViewFile('templates/public/footer.phtml'); ?>