<?php
/**
 * @var $this \M\Framework\View\Template
 */?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="Shortcut Icon" href="__STATIC__/img/favicon.png">
    <link rel="Shortcut Icon" href="__STATIC__/img/favicon.png">
    <link rel="Bookmark" href="__STATIC__/img/favicon.png">
    <link href="__STATIC__/css/header.css" type="text/css" rel="stylesheet">
    <title>欢迎加入 M Framework 的世界! 发现不一样的世界！</title>
    <?php
    /**
     * @var $this \M\Framework\View\Template
     */
    ?>
    <link href="__STATIC__/css/get.css" type="text/css" rel="stylesheet">
    <script src="__STATIC__/js/demo.js"></script>
</head>
<div class="header">
    我是头部
</div>