<!--
====================================================================================================== 
模板文件：D:\wwwroot\dev-bbs.aiweline.com\app\code\Weline\Backend\view\blocks\version.phtml START
======================================================================================================
 -->
<?php

/*
 * 本文件由 秋枫雁飞 编写，所有解释权归Aiweline所有。
 * 邮箱：aiweline@qq.com
 * 网址：aiweline.com
 * 论坛：https://bbs.aiweline.com
 */
/**@var \Weline\Backend\Block\Version $block */
$block = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\Version::class);
?>
<?php echo $block->getVersion() ?>
<!--
========================================================================================================================
模板文件：D:\wwwroot\dev-bbs.aiweline.com\app\code\Weline\Backend\view\tpl\\zh_Hans_CN\blocks\com_version.phtml END
========================================================================================================================
-->