<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!--加载require常用js模块-->
<!--<script src='/Weline/Frontend/view/statics/base/require.configs.js?v=64937'></script>-->
<script>
    window.site = {
        host: '<?=$this->_request->getBaseHost()?>',
        base_host: '<?=$this->_request->getPrePath()?>',
        base_router: '<?=$this->_request->getRouterData('router')?>',
        i18n: <?= json_encode(Weline\Framework\Phrase\Parser::getI18nWords())?>,
        buildUrl: (path) => {
            return window.site.host + path;
        },
        themeConfig: <?=json_encode($themeConfig->getThemeConfig()) ?? '{}';?>,
        selectLanguage: (lang) => {
            setCookie('WELINE-USER-LANG', lang);
            window.location.reload();
        },
    }

    /**
     * 设置Cookie
     * @param cname
     * @param cvalue
     * @param exdays
     */
    function setCookie(cname, cvalue, exdays) {
        let d = new Date();
        d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
        let expires = 'expires=' + d.toGMTString();
        document.cookie = cname + '=' + cvalue + '; ' + expires;
    }

    /**
     * 获取Cookie
     * @param cname
     * @returns {string}
     */
    function getCookie(cname) {
        let name = cname + '=';
        let ca = document.cookie.split(';');
        for (let i = 0; i < ca.length; i++) {
            let c = ca[i].trim();
            if (c.indexOf(name) === 0) return c.substring(name.length, c.length);
        }
        return '';
    }
    /**
     * 通用打印函数
     * @param data
     */
    function p(data) {
        console.log(data)
    }

    /**
     * 翻译函数
     * @param phrase
     * @returns {*}
     * @private
     */
    function __(phrase) {
        if (window.site.i18n[phrase] !== undefined) {
            phrase = window.site.i18n[phrase]
        }
        return phrase
    }
</script>