<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang="en" <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    <?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<meta charset="UTF-8">
<title><?php echo $this->getData('title'); ?></title>
<!--元数据-->
<meta content="<?php echo $this->getData('description'); ?>" name="description"/>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, shrink-to-fit=no'>
<meta content="<?php echo $this->getData('title'); ?>" name='author'/>
<meta content="<?php echo $this->getData('description'); ?>" name='description'/>
<link rel="Shortcut Icon" href="/Weline/Backend/view/statics/img/favicon.png?v=17282">
<link rel="Shortcut Icon" href="/Weline/Backend/view/statics/img/favicon.png?v=17282">
<link rel="Bookmark" href="/Weline/Backend/view/statics/img/favicon.png?v=17282">
<!--加载requirejs-->
<?php if (DEV) : ?>
    <!--        <script src="/Weline/Backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.js?v=22302"></script>-->
<?php
else:
    ?>
    <!--        <script src="/Weline/Backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.min.js?v=76615"></script>-->
<?php
endif;
?>
<!--加载require常用js模块-->
<!--<script src="/Weline/Backend/view/statics/base/require.configs.js?v=50702"></script>-->
<?php echo framework_view_process_block([
    'class' => 'Weline\\Backend\\Block\\Header\\Base',
    'template' => 'Weline_Admin::blocks/header/base.phtml',
]);?>

<!--css-->
<!--loading-->
<link  href='/Weline/Admin/view/statics/libs/loading/loading.css?v=44853' rel="stylesheet" type="text/css"/>
<link  href='/Weline/Admin/view/statics/backend/lib/bootstrap-5.1.3-dist/css/bootstrap.min.css?v=90744' rel="stylesheet" type="text/css"/>
<link  href='/Weline/Admin/view/statics/backend/lib/font-awesome-4.7.0/css/font-awesome.min.css?v=64250' rel="stylesheet" type="text/css"/>
<!-- Bootstrap Css -->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/bootstrap' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet"
      type="text/css"/>
<!-- Icons Css -->
<link  href='/Weline/Admin/view/statics/assets/css/icons.min.css?v=68955' rel="stylesheet" type="text/css"/>
<!-- App Css-->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/app' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet" type="text/css"/>
<!--JS-->
<script  src='/Weline/Backend/view/statics/backend/lib/jquery/3.6.0/jquery.js?v=79788'></script>
<?php if (DEV): ?>
    <!--    <script src="/Weline/Backend/view/statics/backend/lib/jquery/3.6.0/jquery.map?v=70630"></script>-->
<?php endif; ?>
<!--加载配置页头-->
<?php
echo $this->getHeader()->getHtml();
?>

    <!-- jvectormap -->
    <link href="/Weline/Admin/view/statics/assets/libs/jqvmap/jqvmap.min.css?v=46176" rel="stylesheet"/>
    <title>Weline Admin 管理面板</title>
</head>

<!--<body data-sidebar="dark" data-topbar='colored' data-layout='horizontal'>-->
<body <?= $themeConfig->getLayouts() ?? ''; ?>>

<!-- <body data-layout="horizontal" data-topbar="dark"> -->
<!--加载中组件 开始-->
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<!--Loading-->
<section id="loading">
    <div class='loader loader-1'>
        <div class='loader-outter'></div>
        <div class='loader-inner'></div>
    </div>
</section>
<script>
    function showLoading() {
        $('#loading').show()
    }

    function hideLoading() {
        $('#loading').hide()
    }

    $(function () {
        $('#loading').hide()
    })
</script>
<!-- 开始 页面 -->
<div id="layout-wrapper">

    <!--页头工具条 开始-->
    <?php echo framework_view_process_block([
    'class' => 'Weline\\Admin\\Block\\Backend\\Page\\Topbar',
    'cache' => '300',
]);?>
    <!--页头工具条 结束-->

    <!-- ========== Topnav Start ========== -->
    <!--页头菜单栏 开始-->
    <?php echo framework_view_process_block([
    'class' => 'Weline\\Admin\\Block\\Backend\\Page\\Topnav',
    'cache' => '300',
]);?>
    <!--页头菜单栏 结束-->

    <!-- ========== Left Sidebar Start ========== -->
    <!--左侧菜单栏 开始-->
    <?php
/**@var \Weline\Framework\View\Template $this */

use Weline\Framework\Manager\ObjectManager;

?>
<?php
$themeConfig = ObjectManager::getInstance('\Weline\Backend\Block\ThemeConfig');
if (!$themeConfig->getThemeConfig('topnav')):
?>
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <?php
                /**@var \Weline\Backend\Model\Menu $menuModel */
                $menuModel = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Model\Menu::class);
                $menus     = $menuModel->getMenuTree();
                /**@var \Weline\Backend\Model\Menu $menu */
                foreach ($menus as $menu) {
                    if (empty($menu->getAction()) && empty($menu->getParentSource()) && empty($menu->getPid())) {
                        ?>
                        <li class="menu-title"><i
                                    class="<?= $menu->getIcon() ?>"></i><span><?= __($menu->getTitle()) ?></span></li>
                        <?php
                    }
                    $submenus = $menu->getSubMenu();
                    /**@var \Weline\Backend\Model\Menu $submenu */
                    foreach ($submenus as $submenu) {
                        $level_3_menus = $submenu->getSubMenu();
                        if (empty($level_3_menus)) {
                            if ('/' === $submenu->getAction()) {
                                ?>
                                <li>
                                    <a href="<?= $submenu->getUrl() ?>" class="waves-effect">
                                        <i class="<?= $submenu->getIcon() ?>"></i><span
                                                class="badge rounded-pill bg-primary float-end">3</span>
                                        <span><?= $submenu->getTitle() ?></span>
                                    </a>
                                </li>
                                <?php
                            } else {
                                ?>
                                <li>
                                    <a href="<?= $submenu->getUrl() ?>" class=" waves-effect">
                                        <i class="<?= $submenu->getIcon() ?>"></i>
                                        <span><?= $submenu->getTitle() ?></span>
                                    </a>
                                </li>
                                <?php
                            }
                        } else {
                            if ('/' === $submenu->getAction()) {
                                ?>
                                <li>
                                    <a href="<?= $submenu->getUrl() ?>" class="waves-effect">
                                        <i class="<?= $submenu->getIcon() ?>"></i><span
                                                class="badge rounded-pill bg-primary float-end">3</span>
                                        <span><?= $submenu->getTitle() ?></span>
                                    </a>
                                </li>
                                <?php
                            } else {
                                ?>
                                <li>
                                    <a href="javascript: void(0);"
                                       class="has-arrow waves-effect">
                                        <i class="<?= $submenu->getIcon() ?>"></i>
                                        <span><?= $submenu->getTitle() ?></span>
                                    </a>
                                    <ul class="sub-menu" aria-expanded="false">
                                        <?php
                                        /**@var \Weline\Backend\Model\Menu $level_3_menu */
                                        foreach ($level_3_menus as $level_3_menu) {
                                            ?>
                                            <li>
                                                <a href="<?= $level_3_menu->getUrl() ?>"><i
                                                            class="<?= $level_3_menu->getIcon() ?>"></i><?= $level_3_menu->getTitle() ?>
                                                </a>
                                            </li>
                                            <?php
                                        }
                                        ?>
                                    </ul>
                                </li>
                                <?php
                            }
                        }
                    }
                }
                ?>
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<?php endif; ?>
    <!--左侧菜单栏 结束-->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->