<?php
/**@var \Weline\Framework\View\Template $this */
?>
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id='sidebar-menu'>
            <!-- Left Menu Start -->
            <ul class='metismenu list-unstyled mm-show' id='side-menu'>
                <foreach name="catalogs" item="v">
                    <li class='menu-title'>
                        <var>$v['name']</var>
                    </li>
                    <php>$nodes = $v['nodes'];</php>
                    <if condition="$nodes">
                        <foreach name='nodes' item='node'>
                            <li>
                                <a href="@php{if(3===$node['level']):echo 'javascript: void(0);';else:echo $node['href'];endif;}"
                                   class='@if{3===$node["level"]=>has-arrow} waves-effect'>
                                <i class='mdi mdi-file-document-box-outline'></i>
                                <span><var>$node['name']</var></span>
                                </a>
                                <php>
                                    $sub_level = $node['level'];
                                    $sub_nodes = $node['nodes'];
                                </php>
                                <if condition="3===$sub_level and $sub_nodes">
                                    <ul class='sub-menu' aria-expanded='false'>
                                        <foreach name='sub_nodes' item='sub_node'>
                                            <li>
                                                <a href="@var{$sub_node['href']}"><var>$sub_node['name']</var></a>
                                            </li>
                                        </foreach>
                                    </ul>
                                </if>
                            </li>
                        </foreach>
                    </if>
                </foreach>
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>