<?php
/**@var \Weline\Framework\View\Template $this */
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang="en">
<head>
    @template(Weline_Admin::common/head.phtml)
    <!-- jvectormap -->
    <link href="@static(Weline_Admin::assets/libs/jqvmap/jqvmap.min.css)" rel="stylesheet"/>
    <!-- jquery.mCustomScrollbar 插件 -->
    <link href="@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.css)" rel="stylesheet"/>
    <title><?= __('Weline Admin 管理面板') ?></title>
</head>

<body data-sidebar="dark">

<!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- 开始 页面 -->
<div id="layout-wrapper">

    <!--页头工具条 开始-->
    @template(Weline_Admin::common/page/topbar.phtml)
    <!--页头工具条 结束-->

    <!-- ========== Left Sidebar Start ========== -->
    <!--左侧菜单栏 开始-->
    @template(Weline_Admin::common/left-sidebar.phtml)
    <!--左侧菜单栏 结束-->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class="page-content">
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <h4 class="mb-sm-0"><?= __('菜单管理') ?></h4>

                            <div class="page-title-right">
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="javascript: void(0);"><?= __('系统') ?></a></li>
                                    <li class="breadcrumb-item active"><?= __('菜单管理') ?></li>
                                </ol>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- end page title -->

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                <h4 class="card-title"><?= __('菜单编辑器') ?></h4>

                                <div class="table-responsive mCustomScrollbar" data-mcs-axis="yx" data-mcs-theme='light' style="height: 800px">
                                    <table class="table table-editable table-nowrap align-middle table-edits">
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th><?= __('菜单名') ?></th>
                                            <th><?= __('标题') ?></th>
                                            <th><?= __('资源') ?></th>
                                            <th><?= __('父资源') ?></th>
                                            <th><?= __('动作') ?></th>
                                            <th><?= __('模组') ?></th>
                                            <th><?= __('Icon图标') ?></th>
                                            <th><?= __('排序') ?></th>
                                            <th><?= __('创建时间') ?></th>
                                            <th><?= __('更新时间') ?></th>
                                            <th><?= __('操作') ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        /**@var \Weline\Backend\Model\Menu $menu */
                                        foreach ($this->getData('menus') as $menu) {
                                            ?>
                                            <tr data-id='<?= $menu->getId() ?>'>
                                                <td data-field='id' style='width: 80px'><?= $menu->getId() ?></td>
                                                <td data-field='name'><?= $menu->getName() ?></td>
                                                <td data-field='title'><?= $menu->getTitle() ?></td>
                                                <td data-field='source'><?= $menu->getSource() ?></td>
                                                <td data-field='parent_source'><?= $menu->getParentSource() ?></td>
                                                <td data-field='action'><?= $menu->getAction() ?></td>
                                                <td data-field='module'><?= $menu->getModule() ?></td>
                                                <td data-field='icon'><i class='<?= $menu->getIcon() ?>'></i>&nbsp;&nbsp;&nbsp;&nbsp;<span><?= $menu->getIcon() ?></span></td>
                                                <td data-field='order'><?= $menu->getOrder() ?></td>
                                                <td data-field='order'><?= $menu->getCreateTime() ?></td>
                                                <td data-field='order'><?= $menu->getUpdateTime() ?></td>
                                                <td style='width: 100px'>
                                                    <a class='btn btn-outline-secondary btn-sm edit' title='<?= __('编辑') ?>'>
                                                        <i class='fas fa-pencil-alt'></i>
                                                    </a>
                                                    <a class='btn btn-outline-secondary btn-sm delete' title='<?= __('删除') ?>'>
                                                        <i class='mdi mdi-delete' data-action="delete"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            <?php
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <nav aria-label='...'>
                            <ul class='pagination pagination-lg'>
                                <li class='page-item disabled'>
                                    <a class='page-link' href='#' tabindex='-1'>Previous</a>
                                </li>
                                <li class='page-item'><a class='page-link' href='#'>1</a></li>
                                <li class='page-item'><a class='page-link' href='#'>2</a></li>
                                <li class='page-item'><a class='page-link' href='#'>3</a></li>
                                <li class='page-item'>
                                    <a class='page-link' href='#'>Next</a>
                                </li>
                            </ul>
                        </nav>
                    </div> <!-- end col -->
                </div> <!-- end row -->

            </div> <!-- container-fluid -->
        </div>
        <!-- End Page-content -->

        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <script>document.write(new Date().getFullYear())</script>
                        © Weline.
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end d-none d-sm-block">
                            Crafted with <i class="mdi mdi-heart text-danger"></i> By <a
                                    href="https://www.aiweline.com/">秋枫雁飞(aiweline)</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>
    <!-- end main content-->

</div>
<!-- END layout-wrapper -->
<!--右边栏-->
@template(Weline_Admin::common/right-sidebar.phtml)

<!-- Table Editable plugin -->
<script src="@static(Weline_Admin::assets/libs/table-edits/build/table-edits.min.js)"></script>
<script src="@static(Weline_Admin::assets/js/pages/menus-table-editable.init.js)"></script>
<script src='@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js)'></script>
@template(Weline_Admin::common/footer.phtml)
</body>
</html>
