<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<meta charset="UTF-8">
<title><?php echo $this->getData('title'); ?></title>
<!--元数据-->
<meta content="<?php echo $this->getData('description'); ?>" name="description"/>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, shrink-to-fit=no'>
<meta content="<?php echo $this->getData('title'); ?>" name='author'/>
<meta content="<?php echo $this->getData('description'); ?>" name='description'/>
<link rel="Shortcut Icon" href="/Weline/Backend/view/statics/img/favicon.png?v=32879">
<link rel="Shortcut Icon" href="/Weline/Backend/view/statics/img/favicon.png?v=32879">
<link rel="Bookmark" href="/Weline/Backend/view/statics/img/favicon.png?v=32879">
<!--加载requirejs-->
<?php if (DEV) : ?>
    <!--        <script src="/Weline/Backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.js?v=56658"></script>-->
<?php
else:
    ?>
    <!--        <script src="/Weline/Backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.min.js?v=97444"></script>-->
<?php
endif;
?>
<!--加载require常用js模块-->
<!--<script src="/Weline/Backend/view/statics/base/require.configs.js?v=16418"></script>-->
<?php echo framework_view_process_block([
    'class' => 'Weline\\Backend\\Block\\Header\\Base',
    'template' => 'Weline_Admin::header/base.phtml',
]);?>

<!--css-->
<!--loading-->
<link  href='/Weline/Admin/view/statics/libs/loading/loading.css?v=80482' rel="stylesheet" type="text/css"/>
<link  href='/Weline/Admin/view/statics/backend/lib/bootstrap-5.1.3-dist/css/bootstrap.min.css?v=84638' rel="stylesheet" type="text/css"/>
<link  href='/Weline/Admin/view/statics/backend/lib/font-awesome-4.7.0/css/font-awesome.min.css?v=18824' rel="stylesheet" type="text/css"/>
<!-- Bootstrap Css -->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/bootstrap' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet"
      type="text/css"/>
<!-- Icons Css -->
<link  href='/Weline/Admin/view/statics/assets/css/icons.min.css?v=65275' rel="stylesheet" type="text/css"/>
<!-- App Css-->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/app' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet" type="text/css"/>
<!--JS-->
<script  src='/Weline/Backend/view/statics/backend/lib/jquery/3.6.0/jquery.js?v=74331'></script>
<?php if (DEV): ?>
    <!--    <script src="/Weline/Backend/view/statics/backend/lib/jquery/3.6.0/jquery.map?v=97290"></script>-->
<?php endif; ?>
<!--加载配置页头-->
<?php
echo $this->getHeader()->getHtml();
?>
