<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang='en' <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    <?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<meta charset="UTF-8">
<title><?php echo $this->getData('title'); ?></title>
<!--元数据-->
<meta content="<?php echo $this->getData('description'); ?>" name="description"/>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, shrink-to-fit=no'>
<meta content="<?php echo $this->getData('title'); ?>" name='author'/>
<meta content="<?php echo $this->getData('description'); ?>" name='description'/>
<link rel="Shortcut Icon" href="/Weline/Backend/view/statics/img/favicon.png?v=20377">
<link rel="Shortcut Icon" href="/Weline/Backend/view/statics/img/favicon.png?v=20377">
<link rel="Bookmark" href="/Weline/Backend/view/statics/img/favicon.png?v=20377">
<!--加载requirejs-->
<?php if (DEV) : ?>
    <!--        <script src="/Weline/Backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.js?v=65699"></script>-->
<?php
else:
    ?>
    <!--        <script src="/Weline/Backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.min.js?v=16128"></script>-->
<?php
endif;
?>
<!--加载require常用js模块-->
<!--<script src="/Weline/Backend/view/statics/base/require.configs.js?v=65361"></script>-->
<?php echo framework_view_process_block([
    'class' => 'Weline\\Backend\\Block\\Header\\Base',
    'template' => 'Weline_Admin::header/base.phtml',
]);?>

<!--css-->
<!--loading-->
<link  href='/Weline/Admin/view/statics/libs/loading/loading.css?v=96132' rel="stylesheet" type="text/css"/>
<link  href='/Weline/Admin/view/statics/backend/lib/bootstrap-5.1.3-dist/css/bootstrap.min.css?v=39489' rel="stylesheet" type="text/css"/>
<link  href='/Weline/Admin/view/statics/backend/lib/font-awesome-4.7.0/css/font-awesome.min.css?v=92279' rel="stylesheet" type="text/css"/>
<!-- Bootstrap Css -->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/bootstrap' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet"
      type="text/css"/>
<!-- Icons Css -->
<link  href='/Weline/Admin/view/statics/assets/css/icons.min.css?v=51544' rel="stylesheet" type="text/css"/>
<!-- App Css-->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/app' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet" type="text/css"/>
<!--JS-->
<script  src='/Weline/Backend/view/statics/backend/lib/jquery/3.6.0/jquery.js?v=61437'></script>
<?php if (DEV): ?>
    <!--    <script src="/Weline/Backend/view/statics/backend/lib/jquery/3.6.0/jquery.map?v=49653"></script>-->
<?php endif; ?>
<!--加载配置页头-->
<?php
echo $this->getHeader()->getHtml();
?>

    <!-- jvectormap -->
    <link href="/Weline/Admin/view/statics/assets/libs/jqvmap/jqvmap.min.css?v=72688" rel="stylesheet"/>
    <!-- jquery.mCustomScrollbar 插件 -->
    <link href="/Weline/Admin/view/statics/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.css?v=19859" rel="stylesheet"/>
    <!-- Sweet Alert-->
    <link href='/Weline/Admin/view/statics/assets/libs/sweetalert2/sweetalert2.min.css?v=77305' rel='stylesheet' type='text/css'/>
    <title><?= __('Weline Admin 管理面板') ?></title>
</head>

<body <?= $themeConfig->getLayouts() ?? ''; ?>>

<!--页头工具条 开始-->
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<!--Loading-->
<section id="loading">
    <div class='loader loader-1'>
        <div class='loader-outter'></div>
        <div class='loader-inner'></div>
    </div>
</section>
<script>
    function showLoading() {
        $('#loading').show()
    }

    function hideLoading() {
        $('#loading').hide()
    }

    $(function () {
        $('#loading').hide()
    })
</script>
<!--页头工具条 结束-->

<!-- 开始 页面 -->
<div id="layout-wrapper">


    <!--页头工具条 开始-->
    <?php echo framework_view_process_block([
    'class' => 'Weline\\Admin\\Block\\Backend\\Page\\Topbar',
    'cache' => '300',
]);?>
    <!--页头工具条 结束-->

    <!-- ========== Topnav Start ========== -->
    <!--页头菜单栏 开始-->
    <?php echo framework_view_process_block([
    'class' => 'Weline\\Admin\\Block\\Backend\\Page\\Topnav',
    'cache' => '300',
]);?>
    <!--页头菜单栏 结束-->

    <!-- ========== Left Sidebar Start ========== -->
    <!--左侧菜单栏 开始-->
    <?php
/**@var \Weline\Framework\View\Template $this */

use Weline\Framework\Manager\ObjectManager;

?>
<?php
$themeConfig = ObjectManager::getInstance('\Weline\Backend\Block\ThemeConfig');
if (!$themeConfig->getThemeConfig('topnav')):
    ?>
    <div class="vertical-menu">

        <div data-simplebar class="h-100">

            <!--- Sidemenu -->
            <div id="sidebar-menu">
                <!-- Left Menu Start -->
                <ul class="metismenu list-unstyled" id="side-menu">
                    <?php
                    /**@var \Weline\Backend\Model\Menu $menuModel */
                    $menuModel = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Model\Menu::class);
                    $menus     = $menuModel->getMenuTree();
                    /**@var \Weline\Backend\Model\Menu $menu */
                    foreach ($menus as $menu) {
                        if (empty($menu->getAction()) && empty($menu->getParentSource()) && empty($menu->getPid())) {
                            ?>
                            <li class="menu-title"><i class="<?= $menu->getIcon() ?>"></i><span><?= __($menu->getTitle()) ?></span></li>
                            <?php
                        }
                        $submenus = $menu->getSubMenu();
                        /**@var \Weline\Backend\Model\Menu $submenu */
                        foreach ($submenus as $submenu) {
                            $level_3_menus = $submenu->getSubMenu();
                            if (empty($level_3_menus)) {
                                if ('/' === $submenu->getAction()) {
                                    ?>
                                    <li>
                                        <a href="<?= $submenu->getUrl() ?>" class="waves-effect">
                                            <i class="<?= $submenu->getIcon() ?>"></i><span
                                                    class="badge rounded-pill bg-primary float-end">3</span>
                                            <span><?= $submenu->getTitle() ?></span>
                                        </a>
                                    </li>
                                    <?php
                                } else {
                                    ?>
                                    <li>
                                        <a href="<?= $submenu->getUrl() ?>" class=" waves-effect">
                                            <i class="<?= $submenu->getIcon() ?>"></i>
                                            <span><?= $submenu->getTitle() ?></span>
                                        </a>
                                    </li>
                                    <?php
                                }
                            } else {
                                if ('/' === $submenu->getAction()) {
                                    ?>
                                    <li>
                                        <a href="<?= $submenu->getUrl() ?>" class="waves-effect">
                                            <i class="<?= $submenu->getIcon() ?>"></i><span
                                                    class="badge rounded-pill bg-primary float-end">3</span>
                                            <span><?= $submenu->getTitle() ?></span>
                                        </a>
                                    </li>
                                    <?php
                                } else {
                                    ?>
                                    <li>
                                        <a href="javascript: void(0);"
                                           class="has-arrow waves-effect">
                                            <i class="<?= $submenu->getIcon() ?>"></i>
                                            <span><?= $submenu->getTitle() ?></span>
                                        </a>
                                        <ul class="sub-menu" aria-expanded="false">
                                            <?php
                                            /**@var \Weline\Backend\Model\Menu $level_3_menu */
                                            foreach ($level_3_menus as $level_3_menu) {
                                                ?>
                                                <li>
                                                    <a href="<?= $level_3_menu->getUrl() ?>"><i
                                                                class="<?= $level_3_menu->getIcon() ?>"></i><?= $level_3_menu->getTitle() ?>
                                                    </a>
                                                </li>
                                                <?php
                                            }
                                            ?>
                                        </ul>
                                    </li>
                                    <?php
                                }
                            }
                        }
                    }
                    ?>
                </ul>
            </div>
            <!-- Sidebar -->
        </div>
    </div>
<?php endif; ?>
    <!--左侧菜单栏 结束-->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class='main-content'>

        <div class='page-content'>
            <div class='container-fluid'>
                <!-- start page title -->
                <div class='row'>
                    <div class='col-12'>
                        <div class='page-title-box d-sm-flex align-items-center justify-content-between'>
                            <h4 class='mb-sm-0'><?= __('URL管理') ?></h4>

                            <div class="page-title-right">
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="javascript: void(0);"><?= __('系统配置') ?></a></li>
                                    <li class="breadcrumb-item"><a href="javascript: void(0);"><?= __('URL管理器') ?></a></li>
                                    <li class="breadcrumb-item active"><?= __('URL管理') ?></li>
                                </ol>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- end page title -->
                <div class='row'>
                    <!--消息-->
                    <?php
echo \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Framework\Manager\MessageManager::class);
?>
                </div>
                <!--end row-->
                <div class="row">
                    <div class='col-lg-12'>
                        <div class='card'>
                            <div class='card-body'>
                                <h4 class='card-title'>
                                    路由表
                                </h4>
                                <p class='card-title-desc'>
                                    静态路由管理：可定制属于自己的静态url来提升seo。
                                    <a class="btn btn-primary pull-right" href="<?=$this->getAdminUrl('url-manager/backend/rewriter/form')?>">
                                        添加
                                    </a>
                                </p>
                                <div class='table-responsive'>
                                    <table class='table mb-0'>
                                        <thead>
                                        <tr>
                                            <th>#ID</th>
                                            <th>
                                                URL ID
                                            </th>
                                            <th>
                                                路径
                                            </th>
                                            <th>
                                                指纹
                                            </th>
                                            <th>
                                                重写路径
                                            </th>
                                            <th>
                                                类型
                                            </th>
                                            <th>
                                                创建时间
                                            </th>
                                            <th>
                                                更新时间
                                            </th>
                                            <th>
                                                是否已删除
                                            </th>
                                            <th>
                                                操作
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php foreach($rewrites  as $v):?>
                                            <tr>
                                                <td scope='row'><?=($v['rewrite_id']??'') ??'';?></td>
                                                <td scope='row'>
                                                    <?php if(($v['url_id']??'') ):?>
                                                        <?=($v['url_id']??'') ??'';?>
                                                        <?php else:?>
                                                        自定义
                                                    <?php endif;?>
                                                </td>
                                                <td scope='row'><?=($v['rewrite_path']??'') ??'';?></td>
                                                <td scope='row'><?=($v['url_identify']??'') ??'';?></td>
                                                <td scope='row'><?=($v['rewrite']??'') ??'';?></td>
                                                <td scope='row'>
                                                    <?php if(($v['type']??'') ):?>
                                                        <?=($v['type']??'') ??'';?>
                                                        <?php else:?>
                                                        前台
                                                    <?php endif;?>
                                                </td>
                                                <td scope='row'><?=($v['create_time']??'') ??'';?></td>
                                                <td scope='row'><?=($v['update_time']??'') ??'';?></td>
                                                <td scope='row'>
                                                    <?php if(($v['is_deleted']??'') ):?>
                                                        是
                                                        <?php else:?>
                                                        否
                                                    <?php endif;?>
                                                </td>
                                                <td scope='row'>
                                                    <a href="<?=$this->getAdminUrl('url-manager/backend/rewriter/form')?>?rewrite_id=<?=($v['rewrite_id']??'') ??'';?>">
                                                        编辑
                                                    </a>
                                                    <a href="<?=$this->getAdminUrl('url-manager/backend/rewriter/delete')?>?rewrite_id=<?=($v['rewrite_id']??'') ??'';?>">
                                                        删除
                                                    </a>
                                                </td>
                                            </tr>
                                        <?php endforeach;?>
                                        </tbody>
                                    </table>
                                    <?=$pagination ??'';?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- container-fluid -->
        </div>
        <!-- End Page-content -->

        <footer class='footer'>
            <div class='container-fluid'>
                <div class='row'>
                    <div class='col-sm-6'>
                        <script>document.write(new Date().getFullYear())</script>
                        © Weline.
                    </div>
                    <div class='col-sm-6'>
                        <div class='text-sm-end d-none d-sm-block'>
                            Crafted with <i class='mdi mdi-heart text-danger'></i> By <a
                                    href='https://www.aiweline.com/'>秋枫雁飞(aiweline)</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>

</div>
<!-- END layout-wrapper -->
<!--右边栏-->
<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!-- Right Sidebar -->
<div class='right-bar'>
    <div data-simplebar class='h-100'>
        <div class='rightbar-title d-flex align-items-center px-3 py-4'>

            <h5 class='m-0 me-2'><?= __('设置') ?></h5>

            <a href="javascript:void(0);" class="right-bar-toggle ms-auto">
                <i class="mdi mdi-close noti-icon"></i>
            </a>
        </div>

        <!-- Settings -->
        <hr class='mt-0'/>
        <h6 class='text-center mb-0'><?= __('布局元素') ?></h6>
        <div class='p-4'>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        导航栏
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='data-topbar-light'
                               value='light' <?= ($themeConfig->getThemeConfig('data-topbar') === 'light') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-light'>
                            明亮
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='data-topbar-colored'
                               value='colored' <?= ($themeConfig->getThemeConfig('data-topbar') === 'colored') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-colored'>
                            有色
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='data-topbar-dark'
                               value='dark' <?= ($themeConfig->getThemeConfig('data-topbar') === 'dark') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-dark'>
                            暗黑
                        </label>
                    </div>
                </div>
            </div>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        侧边栏
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar'
                               id='data-sidebar-light'
                               value='light' <?= ($themeConfig->getThemeConfig('data-sidebar') === 'light') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-light'>
                            明亮
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar'
                               id='data-sidebar-dark'
                               value='dark' <?= ($themeConfig->getThemeConfig('data-sidebar') === 'dark') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-dark'>
                            暗黑
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar-size'
                               id='data-sidebar-size-default'
                               value='' <?= ($themeConfig->getThemeConfig('data-sidebar-size') === '') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-size-default'>
                            默认尺寸
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar-size'
                               id='data-sidebar-size-small'
                               value='small' <?= ($themeConfig->getThemeConfig('data-sidebar-size') === 'small') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-size-small'>
                            小尺寸
                        </label>
                    </div>
                </div>
            </div>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        布局尺寸
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-layout-size'
                               id='data-layout-size-default'
                               value='' <?= ($themeConfig->getThemeConfig('data-layout-size') === '') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-layout-size-default'>
                            默认
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-layout-size'
                               id='data-layout-size-boxed'
                               value='boxed' <?= ($themeConfig->getThemeConfig('data-layout-size') === 'boxed') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-layout-size-boxed'>
                            盒子
                        </label>
                    </div>
                </div>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='data-layout'
                    <?= $themeConfig->getThemeConfig('data-layout') ? 'checked' : '' ?>>
                <label class="form-check-label" for="data-layout"
                       title='"默认无布局：开启后，设置水平布局，关闭后，设置垂直布局"'><?= __('水平布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='data-keep-enlarged'
                    <?= $themeConfig->getThemeConfig('data-keep-enlarged') ? 'checked' : '' ?>>
                <label class="form-check-label" for="data-keep-enlarged"
                       title='"开启后，保持内容最大化"'><?= __('保持最大化') ?></label>
            </div>

            <div class='mb-3'>
                <h5 class='font-size-14 mb-3'>
                    布局类
                </h5>
                <div class='form-check form-check-inline'>
                    <input class='form-check-input' type='radio' name='layout-class'
                           id='layout-class-default'
                           value='' <?= ($themeConfig->getThemeConfig('layout-class') === '') ? 'checked' : '' ?>>
                    <label class='form-check-label' for='layout-class-default'>
                        默认
                    </label>
                </div>
                <div class='form-check form-check-inline'>
                    <input class='form-check-input' type='radio' name='layout-class'
                           id='layout-class-vertical-collpsed'
                           value='vertical-collpsed' <?= ($themeConfig->getThemeConfig('layout-class') === 'vertical-collpsed') ? 'checked' : '' ?>>
                    <label class='form-check-label' for='layout-class-vertical-collpsed'>
                        垂直塌陷
                    </label>
                </div>
            </div>
        </div>
        <hr class="mt-0"/>
        <h6 class='text-center mb-0'><?= __('菜单布局') ?></h6>
        <div class='p-4'>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='light-sidebar'
                    <?= $themeConfig->getThemeConfig('light-sidebar') ? 'checked' : '' ?>>
                <label class="form-check-label" for="light-sidebar"><?= __('菜单明亮') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='topnav'
                    <?= $themeConfig->getThemeConfig('topnav') ? 'checked' : '' ?>>
                <label class="form-check-label" for="topnav"><?= __('页顶菜单') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='icon-sidebar'
                    <?= $themeConfig->getThemeConfig('icon-sidebar') ? 'checked' : '' ?>>
                <label class="form-check-label" for="icon-sidebar"><?= __('图标菜单') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='layouts-compact-sidebar'
                    <?= $themeConfig->getThemeConfig('layouts-compact-sidebar') ? 'checked' : '' ?>>
                <label class="form-check-label" for="layouts-compact-sidebar"><?= __('图文菜单') ?></label>
            </div>
        </div>

        <hr class="mt-0"/>
        <h6 class='text-center mb-0'><?= __('主题布局') ?></h6>
        <div class='p-4'>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='horizontal_menu_top'
                    <?= $themeConfig->getThemeConfig('horizontal_menu_top') ? 'checked' : '' ?>>
                <label class="form-check-label" for="horizontal_menu_top"><?= __('水平菜单置顶') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='boxed'
                    <?= $themeConfig->getThemeConfig('boxed') ? 'checked' : '' ?>>
                <label class="form-check-label" for="boxed"><?= __('紧凑布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='horizontal-boxed'
                    <?= $themeConfig->getThemeConfig('horizontal-boxed') ? 'checked' : '' ?>>
                <label class="form-check-label" for="horizontal-boxed"><?= __('水平紧凑布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='horizontal'
                    <?= $themeConfig->getThemeConfig('horizontal') ? 'checked' : '' ?>>
                <label class="form-check-label" for="horizontal"><?= __('水平布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='layouts-hori-topbar-dark'
                    <?= $themeConfig->getThemeConfig('layouts-hori-topbar-dark') ? 'checked' : '' ?>>
                <label class="form-check-label" for="layouts-hori-topbar-dark"><?= __('水平顶黑') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='layouts-hori-boxed-width'
                    <?= $themeConfig->getThemeConfig('layouts-hori-boxed-width') ? 'checked' : '' ?>>
                <label class="form-check-label" for="layouts-hori-boxed-width"><?= __('水平盒子') ?></label>
            </div>
        </div>
        <hr class="mt-0"/>
        <h6 class="text-center mb-0"><?= __('主题颜色') ?></h6>

        <div class="p-4">
            <div class="mb-2">
                <img src="/Weline/Admin/view/statics/assets/images/layouts/layout-1.png?v=34715" class="img-thumbnail"
                     alt="layout-1">
            </div>
            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="checkbox" id="light-mode-switch"
                    <?= $themeConfig->getThemeConfig('light-mode-switch') ? 'checked' : '' ?>>
                <label class="form-check-label" for="light-mode-switch"><?= __('明亮模式') ?></label>
            </div>

            <div class="mb-2">
                <img src="/Weline/Admin/view/statics/assets/images/layouts/layout-2.png?v=47348" class="img-thumbnail"
                     alt="layout-2">
            </div>
            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="checkbox"
                       id="dark-mode-switch" <?= $themeConfig->getThemeConfig('dark-mode-switch') ? 'checked' : '' ?>>
                <label class="form-check-label" for="dark-mode-switch"><?= __('暗黑模式') ?></label>
            </div>

            <div class="mb-2">
                <img src="/Weline/Admin/view/statics/assets/images/layouts/layout-3.png?v=88760" class="img-thumbnail"
                     alt="layout-3">
            </div>
            <div class="form-check form-switch mb-5">
                <input class="form-check-input theme-choice" type="checkbox"
                       id="rtl-mode-switch" <?= $themeConfig->getThemeConfig('rtl-mode-switch') ? 'checked' : '' ?>>
                <label class="form-check-label" for="rtl-mode-switch"><?= __('RTL模式') ?></label>
            </div>
        </div>

    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>

<!-- Table Editable plugin -->
<script src='/Weline/Admin/view/statics/assets/libs/table-edits/build/table-edits.min.js?v=72472'></script>
<script src='/Weline/Admin/view/statics/assets/js/pages/menus/table-editable.init.js?v=88749'></script>
<script src='/Weline/Admin/view/statics/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js?v=92784'></script>
<!-- Sweet Alerts js -->
<script src='/Weline/Admin/view/statics/assets/libs/sweetalert2/sweetalert2.min.js?v=19944'></script>

<!-- Sweet alert init js-->
<script src='/Weline/Admin/view/statics/assets/js/pages/menus/sweet-alerts.init.js?v=20854'></script>
<?php
/**@var \Weline\Framework\View\Template $this*/
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="footer-wapper">
                <?php echo framework_view_process_block([
    0 => 'Weline\\Backend\\Block\\Version',
]);?>
            </div>
        </div>
    </div>
</div>
<!-- end Account pages -->

<!-- JAVASCRIPT -->
<!--<script src="/Weline/Admin/view/statics/assets/libs/jquery/jquery.min.js?v=58868"></script>-->
<script src="/Weline/Admin/view/statics/assets/libs/bootstrap/js/bootstrap.bundle.min.js?v=27040"></script>
<script src="/Weline/Admin/view/statics/assets/libs/metismenu/metisMenu.min.js?v=45768"></script>
<script src="/Weline/Admin/view/statics/assets/libs/simplebar/simplebar.min.js?v=91143"></script>
<script src="/Weline/Admin/view/statics/assets/libs/node-waves/waves.min.js?v=99030"></script>

<script src="/Weline/Admin/view/statics/assets/js/app.js?v=60186"></script>
<!--加载配置页脚-->
<?php
/**@var \Weline\Framework\View\Template $this */
echo $this->getFooter()->getHtml();
?>
</body>
</html>
