<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang='en' <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    @template(Weline_Admin::common/head.phtml)
    <!-- jvectormap -->
    <link href="@static(Weline_Admin::assets/libs/jqvmap/jqvmap.min.css)" rel="stylesheet"/>
    <!-- jquery.mCustomScrollbar 插件 -->
    <link href="@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.css)" rel="stylesheet"/>
    <!-- Sweet Alert-->
    <link href='@static(Weline_Admin::assets/libs/sweetalert2/sweetalert2.min.css)' rel='stylesheet' type='text/css'/>
    <title><?= __('Weline Admin 管理面板') ?></title>
</head>

<body <?= $themeConfig->getLayouts() ?? ''; ?>>

<!--页头工具条 开始-->
@template(Weline_Admin::common/page/loading.phtml)
<!--页头工具条 结束-->

<!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- 开始 页面 -->
<div id="layout-wrapper">


    <!--页头工具条 开始-->
    <w:block class='Weline\Admin\Block\Backend\Page\Topbar' />
    <!--页头工具条 结束-->

    <!-- ========== Topnav Start ========== -->
    <!--页头菜单栏 开始-->
    <w:block class='Weline\Admin\Block\Backend\Page\Topnav' />
    <!--页头菜单栏 结束-->

    <!--左侧菜单栏 开始-->
    @template(Weline_Admin::common/left-sidebar.phtml)
    <!--左侧菜单栏 结束-->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class="page-content">
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <h4 class="mb-sm-0"><?= __('邮件发送记录管理器') ?></h4>

                            <div class="page-title-right">
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="javascript: void(0);"><?= __('系统') ?></a></li>
                                    <li class="breadcrumb-item active"><?= __('邮件发送记录管理器') ?></li>
                                </ol>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- end page title -->

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <template>Weline_Component::message.phtml</template>
                                <h4 class="card-title"><?= __('邮件发送记录管理器') ?>:
                                    <lang>一共有</lang>
                                    <var>total</var>
                                    <lang>条数据</lang>
                                </h4>

                                <!--<div class="table-responsive mCustomScrollbar" data-mcs-axis="yx" data-mcs-theme='dark'
                                     style="height: 800px">-->
                                <div class='table-responsive mCustomScrollbar' data-mcs-axis='x'
                                     data-mcs-theme='dark'>
                                    <table class="table table-editable table-nowrap align-middle table-edits">
                                        <thead>
                                        <tr>
                                            <th>
                                                <lang>ID</lang>
                                            </th>
                                            <th>
                                                <lang>模组</lang>
                                            </th>
                                            <th>
                                                <lang>发送邮箱</lang>
                                            </th>
                                            <th>
                                                <lang>发送者名称</lang>
                                            </th>
                                            <th>
                                                <lang>接收者数据</lang>
                                            </th>
                                            <th>
                                                <lang>主题</lang>
                                            </th>
                                            <th>
                                                <lang>内容</lang>
                                            </th>
                                            <th>
                                                <lang>是否HTML</lang>
                                            </th>
                                            <th>
                                                <lang>签名</lang>
                                            </th>
                                            <th>
                                                <lang>抄送数据</lang>
                                            </th>
                                            <th>
                                                <lang>密送数据</lang>
                                            </th>
                                            <th>
                                                <lang>创建时间</lang>
                                            </th>
                                            <th>
                                                <lang>更新时间</lang>
                                            </th>
                                            <th><?= __('操作') ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <foreach name="logs" item="log">
                                            <tr>
                                                <td>{{log.id}}</td>
                                                <td>{{log.module}}</td>
                                                <td>{{log.from}}</td>
                                                <td>{{log.sender_name}}</td>
                                                <td>{{log.to}}</td>
                                                <td>{{log.subject}}</td>
                                                <td>{{log.content}}</td>
                                                <td>{{log.is_html}}</td>
                                                <td>{{log.alt}}</td>
                                                <td>{{log.cc}}</td>
                                                <td>{{log.bcc}}</td>
                                                <td>{{log.create_time}}</td>
                                                <td>{{log.update_time}}</td>
                                                <td>
                                                    <form action="@backend-url('*/backend/log/delete')" method='post'>
                                                        <input type='hidden' name='log_id' value='{{log.id}}'>
                                                        <button class='btn btn-danger'>
                                                            <lang>删除</lang>
                                                        </button>
                                                    </form>
                                                    <form action="@backend-url('*/backend/log')" method='get'>
                                                        <input type='hidden' name='log_id' value='{{log.id}}'>
                                                        <button class='btn btn-primary'>
                                                            <lang>阅读</lang>
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        </foreach>
                                        </tbody>
                                    </table>
                                    <div>
                                        <var>pagination</var>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> <!-- end col -->
                </div> <!-- end row -->
            </div> <!-- container-fluid -->
        </div>
        <!-- End Page-content -->

        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <script>document.write(new Date().getFullYear())</script>
                        © Weline.
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end d-none d-sm-block">
                            Crafted with <i class="mdi mdi-heart text-danger"></i> By <a
                                    href="https://www.aiweline.com/">秋枫雁飞(aiweline)</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>
    <!-- end main content-->

</div>
<!-- END layout-wrapper -->
<!--右边栏-->
@template(Weline_Admin::common/right-sidebar.phtml)

<!-- Table Editable plugin -->
<script src="@static(Weline_Admin::assets/libs/table-edits/build/table-edits.min.js)"></script>
<script src="@static(Weline_Admin::assets/js/pages/menus/table-editable.init.js)"></script>
<script src='@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js)'></script>
<!-- Sweet Alerts js -->
<script src='@static(Weline_Admin::assets/libs/sweetalert2/sweetalert2.min.js)'></script>

<!-- Sweet alert init js-->
<js>Weline_Admin::assets/js/pages/menus/sweet-alerts.init.js</js>
@template(Weline_Admin::common/footer.phtml)
</body>
</html>
