<form class='app-search d-none d-lg-block' onkeydown='searchKeyDown(event)' method='{{method}}' action='{{action}}'>
    <div class='position-relative'>
        <input type='text' id='{{id}}' name='{{keyword}}' class='form-control' placeholder='{{placeholder}}' value='{{value}}'>
        <span class='ri-search-line'></span>
    </div>
</form>
<script type='text/javascript'>
    function searchKeyDown(ev) {
        ev = ev || window.event;
        if (ev.keyCode === 13) {
            $('#{{id}}').submit()
        }
    }
</script>