<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Admin\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Admin\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang='en' <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    @template(Weline_Admin::common/head.phtml)
    <!-- jvectormap -->
    <link href="@static(Weline_Admin::assets/libs/jqvmap/jqvmap.min.css)" rel="stylesheet"/>
    <!-- jquery.mCustomScrollbar 插件 -->
    <link href="@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.css)" rel="stylesheet"/>
    <!-- Sweet Alert-->
    <link href='@static(Weline_Admin::assets/libs/sweetalert2/sweetalert2.min.css)' rel='stylesheet' type='text/css'/>
    <title><?= __('Weline Admin 管理面板') ?></title>
</head>

<body <?= $themeConfig->getLayouts() ?? ''; ?>>

<!--页头工具条 开始-->
@template(Weline_Admin::common/page/loading.phtml)
<!--页头工具条 结束-->

<!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- 开始 页面 -->
<div id="layout-wrapper">

    <!--页头工具条 开始-->
    @template(Weline_Admin::common/page/topbar.phtml)
    <!--页头工具条 结束-->

    <!-- ========== Left Sidebar Start ========== -->
    <!--左侧菜单栏 开始-->
    @template(Weline_Admin::common/left-sidebar.phtml)
    <!--左侧菜单栏 结束-->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class="page-content">
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <h4 class="mb-sm-0"><?= __('缓存管理') ?></h4>

                            <div class="page-title-right">
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="javascript: void(0);"><?= __('系统') ?></a></li>
                                    <li class="breadcrumb-item active"><?= __('缓存管理') ?></li>
                                </ol>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- end page title -->

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                <h4 class="card-title"><?= __('缓存控制器') ?></h4>

                                <!--<div class="table-responsive mCustomScrollbar" data-mcs-axis="yx" data-mcs-theme='dark'
                                     style="height: 800px">-->
                                <div class='table-responsive mCustomScrollbar' data-mcs-axis='x'
                                     data-mcs-theme='dark'>
                                    <table class="table table-editable table-nowrap align-middle table-edits">
                                        <thead>
                                        <tr>
                                            <th>
                                                <lang>类型</lang>
                                            </th>
                                            <th>
                                                <lang>类</lang>
                                            </th>
                                            <th>
                                                <lang>文件</lang>
                                            </th>
                                            <th>
                                                <lang>备注</lang>
                                            </th>
                                            <th>
                                                <lang>是否持久化</lang>
                                            </th>
                                            <th><?= __('操作') ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach ($this->getData('caches') as $type => $caches) {
                                            ?>
                                            <tr>
                                                <td colspan="3" class="h-25"><var>$type</var></td>
                                            </tr>
                                            <?php
                                            /**@var \Weline\Framework\Cache\CacheInterface $cacheObject */
                                            foreach ($caches as $key => $cache) {
                                                $cacheObject    = \Weline\Framework\Manager\ObjectManager::make($cache['class']);
                                                $status_checked = $cacheObject->getStatus() ? 'checked' : '';
                                                $switch_id      = "switch$key";
                                                ?>
                                                <tr>
                                                    <td></td>
                                                    <td><var>$cacheObject::class</var></td>
                                                    <td><var>$cache['path']</var></td>
                                                    <td><var>$cacheObject->getTip()</var></td>
                                                    <td><var>$cacheObject->isKeep()?__('是'):__("否")</var></td>
                                                    <td style='width: 100px'>
                                                        <input class='form-check form-switch' type='checkbox' alt="@php{echo $cacheObject->isKeep()?__('系统持久缓存无法操作'):'状态开关'}"

                                                                @php{echo $cacheObject->isKeep()?"disabled":""}
                                                        id='@var($switch_id)' switch='bool' @var($status_checked )>
                                                        <label class='form-label' for='@var($switch_id)'
                                                               data-on-label='<?= __('开启') ?>'
                                                               data-off-label='<?= __('关闭') ?>'></label>
                                                    </td>
                                                </tr>
                                                <?php
                                            }
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                    <script>
                                        $('.form-switch').bind('input propertychange', (e) => {
                                            console.log(e)
                                        })
                                    </script>
                                </div>
                            </div>
                        </div>
                    </div> <!-- end col -->
                </div> <!-- end row -->
            </div> <!-- container-fluid -->
        </div>
        <!-- End Page-content -->

        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <script>document.write(new Date().getFullYear())</script>
                        © Weline.
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end d-none d-sm-block">
                            Crafted with <i class="mdi mdi-heart text-danger"></i> By <a
                                    href="https://www.aiweline.com/">秋枫雁飞(aiweline)</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>
    <!-- end main content-->

</div>
<!-- END layout-wrapper -->
<!--右边栏-->
@template(Weline_Admin::common/right-sidebar.phtml)

<!-- Table Editable plugin -->
<script src="@static(Weline_Admin::assets/libs/table-edits/build/table-edits.min.js)"></script>
<script src="@static(Weline_Admin::assets/js/pages/menus/table-editable.init.js)"></script>
<script src='@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js)'></script>
<!-- Sweet Alerts js -->
<script src='@static(Weline_Admin::assets/libs/sweetalert2/sweetalert2.min.js)'></script>

<!-- Sweet alert init js-->
<js>Weline_Admin::assets/js/pages/menus/sweet-alerts.init.js</js>
@template(Weline_Admin::common/footer.phtml)
</body>
</html>
