<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>欢迎加入 M Framework 的世界! 发现不一样的世界！</title>
    <link rel="Shortcut Icon" href="\design\default1\Aiweline\Index\view\statics\/img/favicon.png">
    <?php
    /**
     * @var $this \Weline\Framework\View\Template
     */
    ?>
    <link href="\design\default1\Aiweline\Index\view\statics\/css/index.css" type="text/css" rel="stylesheet">
    <script src="\design\default1\Aiweline\Index\view\statics\/js/demo.js"></script>
</head>
<body>
<div class="header">
    <h1>欢迎加入 Weline Framework 的世界! 真挚邀请你，我们共筑一个不一样的世界！</h1>
    <div class="img-box"><img src="\design\default1\Aiweline\Index\view\statics\/img/logo.png" alt=""></div>
    <p class="official-p-sign">人生总要做点有意义的事儿，非是一定要成功，却是一定是在做，方可安心。</p>
    <p class="official-p">开发者：<a href="https://www.baidu.com/s?wd=%E7%A7%8B%E6%9E%AB%E9%9B%81%E9%A3%9E&rsv_spt=1&rsv_iqid=0xc9e7de650008e85c&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&rqlang=cn&tn=baiduhome_pg&rsv_enter=0&rsv_dl=tb&oq=%25E7%25A7%258B%25E9%25A3%258E%25E9%259B%2581%25E9%25A3%259E&rsv_btype=t&inputT=4314&rsv_t=61f3seQPG9m%2ForkDXbd7xxktyscr%2BUJZgQsaFj7Y9bIVVhR8C%2FyqdamWeYcWcYY7ody9&rsv_pq=b8515c4e001013e3&rsv_sug3=43&rsv_sug1=30&rsv_sug7=100&prefixsug=%25E7%25A7%258B%25E6%259E%25AB%25E9%259B%2581%25E9%25A3%259E&rsp=0&rsv_sug4=4935">秋枫雁飞</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;论坛：<a href="http://bbs.aiweline.com" target="_blank">bbs.aiweline.com</a></p>
</div>
<div class="feature">
    <div class="feature-detail">
        <h3>特色：</h3>
        <p>1、功能代码可移植安装。</p>
        <p>2、一个需求一个App应用，一个应用涵盖前后端源码。</p>
        <p>3、无插件等复杂影响性能构建，源码可直接修改。</p>
        <p>4、使用国内TP6 ORM无缝封装，更加符合国人数据库操作习惯。</p>
        <p>5、更加灵活严谨的API开发体验。</p>
        <p>码云地址：<a href="https://gitee.com/Aiweline_admin/WelineFramework.git">https://gitee.com/Aiweline_admin/WelineFramework.git</a>。</p>
        <p>正式版本：<a href="http://m.aiweline.com">http://m.aiweline.com</a>。</p>
    </div>
</div>
<div class="sample">
    <div class="debug">
        <a href="<?=$this->getUrl('/hello/helloworld/p')?>" target="_blank" onclick="openWindow(this.href,this.text)">调试样式</a>
        <a href="/hello/helloworld/ex" target="_blank" onclick="openWindow(this.href,'异常调试')">异常调试</a>
        <a href="/hello/helloworld/demo" target="_blank" onclick="openWindow(this.href,'Demo')">Demo</a>
        <a href="/hello/helloworld/model" target="_blank" onclick="openWindow(this.href,'model')">model</a>
        <a href="/hello/helloworld/cache" target="_blank" onclick="openWindow(this.href,'Cache')">Cache</a>
        <a href="/hello/helloworld/session" target="_blank" onclick="openWindow(this.href,'Session')">Session</a>
        <a href="/hello/helloworld/plugin" target="_blank" onclick="openWindow(this.href,'Plugin')">Plugin</a>
        <a href="/hello/helloworld/observer" target="_blank" onclick="openWindow(this.href,'Observer')">Observer</a>
        <a href="/<?php echo \Weline\Framework\App\Env::getInstance()->getConfig('admin','admin');?>/" target="_blank" onclick="openWindow(this.href,this.text)">后台</a>
        <a href="/<?php echo \Weline\Framework\App\Env::getInstance()->getConfig('api_admin','api_admin');?>/rest/V1/index" target="_blank" onclick="openWindow(this.href,this.text)">后台api</a>
        <a href="hello/rest/v1/index/index" target="_blank" onclick="openWindow(this.href,'前台api')">前台api</a>
    </div>
</div>
</body>
</html>
