<!--
===================================================================================================================== 
模板文件：E:\WelineFramework\DEV-workspace\app\code\Weline\Eav\view\templates\Backend\Attribute\form.phtml START
=====================================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang='en' <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    <!--
================================================================================================================= 
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\templates\common\head.phtml START
=================================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<meta charset="UTF-8">
<title><?php echo $this->getData('title'); ?></title>
<!--元数据-->
<meta content="<?php echo $this->getData('description'); ?>" name="description"/>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, shrink-to-fit=no'>
<meta content="<?php echo $this->getData('title'); ?>" name='author'/>
<meta content="<?php echo $this->getData('description'); ?>" name='description'/>
<link rel="Shortcut Icon" href="/weline/module-backend/view/statics/img/favicon.png?v=29975">
<link rel="Shortcut Icon" href="/weline/module-backend/view/statics/img/favicon.png?v=29975">
<link rel="Bookmark" href="/weline/module-backend/view/statics/img/favicon.png?v=29975">
<!--加载requirejs-->
<?php if (DEV) : ?>
    <!--        <script src="/weline/module-backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.js?v=68361"></script>-->
<?php
else:
    ?>
    <!--        <script src="/weline/module-backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.min.js?v=16606"></script>-->
<?php
endif;
?>
<!--加载require常用js模块-->
<!--<script src="/weline/module-backend/view/statics/base/require.configs.js?v=60856"></script>-->
<?php echo framework_view_process_block([
    'class' => 'Weline\\Backend\\Block\\Header\\Base',
    'template' => 'Weline_Admin::header/base.phtml',
]);?>

<!--css-->
<!--loading-->
<link  href='/weline/module-admin/view/statics/libs/loading/loading.css?v=86780' rel="stylesheet" type="text/css"/>
<link  href='/weline/module-admin/view/statics/backend/lib/bootstrap-5.1.3-dist/css/bootstrap.min.css?v=65607' rel="stylesheet" type="text/css"/>
<link  href='/weline/module-admin/view/statics/backend/lib/font-awesome-4.7.0/css/font-awesome.min.css?v=38753' rel="stylesheet" type="text/css"/>
<!-- Bootstrap Css -->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/bootstrap' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet"
      type="text/css"/>
<!-- Icons Css -->
<link  href='/weline/module-admin/view/statics/assets/css/icons.min.css?v=75848' rel="stylesheet" type="text/css"/>
<!-- App Css-->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/app' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet" type="text/css"/>
<!--JS-->
<script  src='/weline/module-backend/view/statics/backend/lib/jquery/3.6.0/jquery.js?v=36812'></script>
<?php if (DEV): ?>
    <!--    <script src="/weline/module-backend/view/statics/backend/lib/jquery/3.6.0/jquery.map?v=23069"></script>-->
<?php endif; ?>
<!--加载配置页头-->
<?php
echo $this->getHeader()->getHtml();
?>

<!--
==============================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\tpl\\en_US\templates\common\com_head.phtml END
==============================================================================================================================
-->
    <title><?= __('Weline Admin 管理面板') ?></title>
    <!-- twitter-bootstrap-wizard css -->
    <link rel='stylesheet' href='/weline/module-admin/view/statics/assets/libs/twitter-bootstrap-wizard/prettify.css?v=46883'>
    <link rel='stylesheet' href='/Weline/Eav/view/statics/libs/bootstrap-select-1.13.14/dist/css/bootstrap-select.min.css?v=24392'>
    <script  src='/Weline/Eav/view/statics/libs/bootstrap-select-1.13.14/dist/js/bootstrap-select.min.js?v=95476'></script>
    <script  src='/Weline/Eav/view/statics/libs/bootstrap-select-1.13.14/dist/js/i18n/defaults-<?=($local['lang']??'') ??'';?>.min.js?v=74600'></script>
</head>

<body <?= $themeConfig->getLayouts() ?? ''; ?>>

<!--页头工具条 开始-->
<!--
========================================================================================================================= 
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\templates\common\page\loading.phtml START
=========================================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<!--Loading-->
<section id="loading">
    <div class='loader loader-1'>
        <div class='loader-outter'></div>
        <div class='loader-inner'></div>
    </div>
</section>
<script>
    function showLoading() {
        $('#loading').show()
    }

    function hideLoading() {
        $('#loading').hide()
    }

    $(function () {
        $('#loading').hide()
    })
</script>
<!--
======================================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\tpl\\en_US\templates\common\page\com_loading.phtml END
======================================================================================================================================
-->
<!--页头工具条 结束-->

<!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- 开始 页面 -->
<div id="layout-wrapper">


    <!--页头工具条 开始-->
    <?php echo framework_view_process_block([
    'class' => 'Weline\\Admin\\Block\\Backend\\Page\\Topbar',
]);?>
    <!--页头工具条 结束-->

    <!-- ========== Topnav Start ========== -->
    <!--页头菜单栏 开始-->
    <?php echo framework_view_process_block([
    'class' => 'Weline\\Admin\\Block\\Backend\\Page\\Topnav',
]);?>
    <!--页头菜单栏 结束-->

    <!-- ========== Left Sidebar Start ========== -->
    <!--左侧菜单栏 开始-->
    <!--
========================================================================================================================= 
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\templates\common\left-sidebar.phtml START
=========================================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */

use Weline\Framework\Manager\ObjectManager;

?>
<?php
$themeConfig = ObjectManager::getInstance('\Weline\Backend\Block\ThemeConfig');
if (!$themeConfig->getThemeConfig('topnav')):
    ?>
    <div class="vertical-menu">

        <div data-simplebar class="h-100">

            <!--- Sidemenu -->
            <div id="sidebar-menu">
                <!-- Left Menu Start -->
                <ul class="metismenu list-unstyled" id="side-menu">
                    <?php
                    /**@var \Weline\Backend\Model\Menu $menuModel */
                    $menuModel = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Model\Menu::class);
                    // 获取菜单类型的角色资源
                    /**@var \Weline\Backend\Session\BackendSession $session */
                    $session = ObjectManager::getInstance(\Weline\Backend\Session\BackendSession::class);
                    /**@var \Weline\Backend\Model\BackendUser $user */
                    $user = $session->getLoginUser();
                    $role = $user->getRoleModel();

                    /**@var \Weline\Acl\Model\RoleAccess $roleAccessModel */
                    $roleAccessModel = ObjectManager::getInstance(\Weline\Acl\Model\RoleAccess::class);
                    $roleAccessMenus = $menuModel->getMenuTreeByRole($role);
                    /**@var \Weline\Acl\Model\Acl $menu */
                    foreach ($roleAccessMenus as $menu) {
                        if (!$menu->getData('is_enable')) {
                            continue;
                        }
                        if (empty($menu->getParentSource())) {
                            ?>
                            <li class="menu-title" data-source='<?=($menu['source']??'') ??'';?>'><i
                                        class="<?= $menu->getIcon() ?>"></i><span><?= __($menu->getSourceName()) ?></span>
                            </li>
                            <?php
                        }
                        $subacls = $menu->getSub();
                        /**@var \Weline\Acl\Model\Acl $subacl */
                        foreach ($subacls as $subacl) {
                            if ($subacl->getType() !== 'menus') {
                                continue;
                            }
                            $level_3_acls = $subacl->getSub();
                            if (empty($level_3_acls)) {
                                if ('/' === $subacl->getAction()) {
                                    ?>
                                    <li data-source='<?=($subacl['source']??'') ??'';?>'>
                                        <a href="<?= $subacl->getUrl() ?>" data-source="<?=($subacl['source']??'') ??'';?>"
                                           class="waves-effect">
                                            <i class="<?= $subacl->getIcon() ?>"></i><span
                                                    class="badge rounded-pill bg-primary float-end">3</span>
                                            <span><?= __($subacl->getSourceName()) ?></span>
                                        </a>
                                    </li>
                                    <?php
                                } else {
                                    ?>
                                    <li data-source='<?=($subacl['source']??'') ??'';?>'>
                                        <a href="<?= $subacl->getUrl() ?>" data-source='<?=($subacl['source']??'') ??'';?>'
                                           class=" waves-effect">
                                            <i class="<?= $subacl->getIcon() ?>"></i>
                                            <span><?= __($subacl->getSourceName()) ?></span>
                                        </a>
                                    </li>
                                    <?php
                                }
                            } else {
                                if ('/' === $subacl->getAction()) {
                                    ?>
                                    <li data-source='<?=($subacl['source']??'') ??'';?>'>
                                        <a href="<?= $subacl->getUrl() ?>" data-source='<?=($subacl['source']??'') ??'';?>'
                                           class="waves-effect">
                                            <i class="<?= $subacl->getIcon() ?>"></i><span
                                                    class="badge rounded-pill bg-primary float-end">3</span>
                                            <span><?= __($subacl->getSourceName()) ?></span>
                                        </a>
                                    </li>
                                    <?php
                                } else {
                                    ?>
                                    <li data-source='<?=($subacl['source']??'') ??'';?>'>
                                        <a href="javascript: void(0);" data-source='<?=($subacl['source']??'') ??'';?>'
                                           class="has-arrow waves-effect">
                                            <i class="<?= $subacl->getIcon() ?>"></i>
                                            <span><?= __($subacl->getSourceName()) ?></span>
                                        </a>
                                        <ul class="sub-acl" aria-expanded="false">
                                            <?php
                                            /**@var \Weline\Backend\Model\acl $level_3_acl */
                                            foreach ($level_3_acls as $level_3_acl) {
                                                if ($level_3_acl->getType() !== 'menus') {
                                                    continue;
                                                }
                                                ?>
                                                <li data-source='<?=($level_3_acl['source']??'') ??'';?>'>
                                                    <a href="<?= $level_3_acl->getUrl() ?>"
                                                       data-source='<?=($level_3_acl['source']??'') ??'';?>'><i
                                                                class="<?= $level_3_acl->getIcon() ?>"></i>
                                                        <?= __($level_3_acl->getSourceName()) ?>
                                                    </a>
                                                </li>
                                                <?php
                                            }
                                            ?>
                                        </ul>
                                    </li>
                                    <?php
                                }
                            }
                        }
                    }
                    ?>
                </ul>
            </div>
            <!-- Sidebar -->
        </div>
    </div>
<?php endif; ?>
<!--
======================================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\tpl\\en_US\templates\common\com_left-sidebar.phtml END
======================================================================================================================================
-->
    <!--左侧菜单栏 结束-->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class='page-content'>
            <div class='container-fluid'>
                <!-- start page title -->
                <div class='row'>
                    <div class='col-12'>
                        <div class='page-title-box d-sm-flex align-items-center justify-content-between'>
                            <h4 class='mb-sm-0'>
                                Eav
                                >
                                属性
                            </h4>

                            <div class='page-title-right'>
                                <ol class='breadcrumb m-0'>
                                    <li class='breadcrumb-item'><a href='javascript: void(0);'>
                                            Eav
                                        </a></li>
                                    <li class='breadcrumb-item'>
                                        <a href="<?=$this->getBackendUrl('*/backend/attribute')?>">
                                            属性
                                        </a>
                                    </li>
                                </ol>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- end page title -->
                <!-- start page message -->
                <div class='row'>
                    <!--
================================================================================================================= 
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-component\view\templates\message.phtml START
=================================================================================================================
 -->
<?php
echo \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Framework\Manager\MessageManager::class);
?>
<!--
==============================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-component\view\tpl\\en_US\templates\com_message.phtml END
==============================================================================================================================
-->
                </div> <!-- end message -->
                <div class='row'>
                    <div class='col-12'>
                        <div class='card'>
                            <div class='card-body'>
                                <h4 class='card-title'>
                                    属性
                                    <?php if(($attribute['attribute_id']??'') ):?>编辑
                                        <?php else:?>
                                        添加
                                    <?php endif;?>
                                </h4>
                                <p class='card-title-desc'>
                                    属性表单
                                </p>
                                <p class="card-title-desc">
                                                                            属性信息编辑,属性修改时某些信息是不能修改的，否则数据结构会异常。但是你可以删除这个属性然后使用相同的属性代码（code）创建其他类型的属性。                                    
                                </p>
                                <form class='needs-validation' novalidate='' action="<?=$action ??'';?>" method="post">
                                    <!--基础信息-->
                                    <div class='row'>
                                        <!--代码-->
                                        <div class='col-md-4'>
                                            <div class='mb-3'>
                                                <label class='form-label' for='validationCode'>
                                                    属性代码
                                                </label>
                                                <input type='text' class='form-control' maxlength='60' data-parsley-minlength='3'
                                                       id='validationCode' placeholder='属性代码' name="code"
                                                       value='<?=($attribute['code']??'') ??'';?>'
                                                       required='' <?php if(($attribute['attribute_id']??'') ):echo "disabled";endif;?>>
                                                <div class='valid-feedback'>
                                                    填写正确！
                                                </div>
                                            </div>
                                        </div>
                                        <!--属性名-->
                                        <div class='col-md-4'>
                                            <div class='mb-3'>
                                                <label class='form-label' for='validationName'>
                                                    属性名
                                                </label>
                                                <input type='text' class='form-control' maxlength='60' data-parsley-minlength='3' id='validationName'
                                                       placeholder='属性名(最短三个字符)' required='' name="name" value='<?=($attribute['name']??'') ??'';?>'>
                                                <div class='invalid-feedback'>
                                                    请正确填写属性名！(最短三个字符)
                                                </div>
                                            </div>
                                        </div>
                                        <!--实体-->
                                        <div class='col-md-4'>
                                            <div class='mb-3'>
                                                <label class='form-label' for='validationEntity'>
                                                    关联实体
                                                </label>
                                                <select type='text' class='form-control' maxlength='60' data-parsley-minlength='3'
                                                        id='validationEntity' placeholder='关联实体' name='entity_code'
                                                        value='<?=($attribute['entity']??'') ??'';?>'
                                                        required='' <?php if(($attribute['attribute_id']??'') ):echo 'disabled';endif;?>>
                                                    <?php foreach($entities  as $v):?>
                                                        <option value='<?=($v['code']??'') ??'';?>' <?php if(($attribute['entity_code']??'') ==  ($v['code']??'') ):echo 'selected';endif;?>><?=($v['name']??'') ??'';?>
                                                        </option>
                                                    <?php endforeach;?>
                                                </select>
                                                <div class='valid-feedback'>
                                                    填写正确！
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class='row'>
                                        <div class='col-md-4'>
                                            <div class='mb-3'>
                                                <label class='form-label' for='validationType'>
                                                    属性类型
                                                </label>
                                                <select class='form-control' id='validationType' name='type' required='' <?php if(($attribute['attribute_id']??'') ):echo 'disabled';endif;?>>
                                                    <?php foreach($types  as $type):?>
                                                        <option value="<?=($type['code']??'') ??'';?>" <?php if(($attribute['type']??'') ==  ($type['code']??'') ):echo 'selected';endif;?>>
                                                            <?=($type['name']??'') ??'';?>
                                                        </option>
                                                    <?php endforeach;?>
                                                </select>
                                                <div class='invalid-feedback'>
                                                    必须选择一个类型
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!--高级信息-->
                                    <div class='accordion mb-3' id='accordionAdvanced'>
                                        <div class='accordion-item'>
                                            <h2 class='accordion-header' id='headingOne'>
                                                <button class='accordion-button' type='button' data-bs-toggle='collapse'
                                                        data-bs-target='#collapseAdvanced'
                                                        aria-expanded='true' aria-controls='collapseAdvanced'>
                                                    高级设置
                                                </button>
                                            </h2>
                                            <div id='collapseAdvanced' class='accordion-collapse collapse show' aria-labelledby='headingAdvanced'
                                                 data-bs-parent='#accordionAdvanced'>
                                                <div class='accordion-body'>
                                                    <div class='row'>
                                                        <div class='col-md-4'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='validationType'>
                                                                    是否多值
                                                                </label>
                                                                <select class='form-control' id='validationType' required='' name="multiple_valued"
                                                                        <?php if(($attribute['attribute_id']??'') ):echo 'disabled';endif;?>>
                                                                    <option value="0" <?php if(($attribute['multiple_valued']??'') ==  0 ):echo 'selected';endif;?>>单值</option>
                                                                    <option value="1" <?php if(($attribute['multiple_valued']??'') ==  1 ):echo 'selected';endif;?>>多值</option>
                                                                </select>
                                                                <div class='invalid-feedback'>
                                                                    必须选择一个多值类型
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class='col-md-4'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='validationGroup'>
                                                                    分组
                                                                </label>
                                                                <select class='form-control' id='validationGroup' required='' name="group_code">
                                                                    <?php foreach($groups  as $group):?>
                                                                        <option value='<?=($group['code']??'') ??'';?>'
                                                                                <?php if(($attribute['group_code']??'') == ($group['code']??'')  &&                                                                                 ($attribute['entity_code']??'') == ($group['entity_code']??'') ):echo 'selected';endif;?>>
                                                                            <?=($group['name']??'') ??'';?>（实体：<?=($group['entity_name']??'') ??'';?>）
                                                                        </option>
                                                                    <?php endforeach;?>
                                                                </select>
                                                                <div class='invalid-feedback'>
                                                                    必须选择一个组
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class='col-md-4'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='validationOption'>
                                                                    是否有配置项
                                                                </label>
                                                                <select class='form-control' id='validationOption' required='' name="has_option"
                                                                        <?php if(($attribute['attribute_id']??'') ):echo 'disabled';endif;?>>
                                                                    <option value='0'
                                                                            <?php if(($attribute['has_option']??'') ==  0 ):echo 'selected';endif;?>>
                                                                        没有特定配置项
                                                                    </option>
                                                                    <option value='1'
                                                                            <?php if(($attribute['has_option']??'') ==  1 ):echo 'selected';endif;?>>
                                                                        有特定配置项
                                                                    </option>
                                                                </select>
                                                                <span class="help-block">有配置项则只能选择配置项内设置的值，没有配置项可以输入任意值。</span>
                                                            </div>
                                                        </div>
                                                        <div class='col-md-4'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='validationSystem'>
                                                                    是否是系统生成
                                                                </label>
                                                                <select class='form-control' id='validationSystem' required='' name='is_system'
                                                                        disabled>
                                                                    <option value='0'
                                                                            <?php if(($attribute['is_system']??'') ==  0 ):echo 'selected';endif;?>>
                                                                        非系统属性
                                                                    </option>
                                                                    <option value='1'
                                                                            <?php if(($attribute['is_system']??'') ==  1 ):echo 'selected';endif;?>>
                                                                        系统属性
                                                                    </option>
                                                                </select>
                                                                <span class='help-block'>仅做标记是否由系统生成，或者非系统生成（用户自定义）。</span>
                                                            </div>
                                                        </div>
                                                        <div class='col-md-4'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='validationEnable'>
                                                                    是否启用
                                                                </label>
                                                                <select class='form-control' id='validationEnable' required='' name='is_enable'>
                                                                    <option value='0'
                                                                            <?php if(($attribute['is_enable']??'') ==  0 ):echo 'selected';endif;?>>
                                                                        禁用
                                                                    </option>
                                                                    <option value='1'
                                                                            <?php if(($attribute['is_enable']??'') ==  1 ):echo 'selected';endif;?>>
                                                                        启用
                                                                    </option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <button class='btn btn-primary' type='submit'>
                                        <?php if(empty($attribute )): ?>
                                            添加
                                            <?php else:?>
                                            编辑
                                        <?php endif; ?>
                                    </button>
                                    <?php if(!empty($attribute ) ): ?>
                                        <a class='btn btn-info' href="<?=$this->getBackendUrl('*/backend/attribute/add')?>">
                                            继续新增
                                        </a>
                                    <?php endif; ?>
                                </form>
                            </div>
                        </div>
                    </div> <!-- end col -->
                </div> <!-- end row -->
                <div class='row'>
                    <div class='col-lg-12'>
                        <div class='card'>
                            <div class='card-body'>
                                <h4 class='card-title mb-4'>创建属性进度</h4>

                                <div id='progrss-wizard' class='twitter-bs-wizard'>
                                    <ul class='twitter-bs-wizard-nav nav-justified'>
                                        <li class='nav-item'>
                                            <a href='#progress-select-entity' class='nav-link' data-toggle='tab'>
                                                <span class='step-number'>01</span>
                                                <span class='step-title'>选择实体</span>
                                            </a>
                                        </li>
                                        <li class='nav-item'>
                                            <a href='#progress-select-set' class='nav-link' data-toggle='tab'>
                                                <span class='step-number'>02</span>
                                                <span class='step-title'>选择属性集</span>
                                            </a>
                                        </li>
                                        <li class='nav-item'>
                                            <a href='#progress-select-group' class='nav-link' data-toggle='tab'>
                                                <span class='step-number'>03</span>
                                                <span class='step-title'>选择属性组</span>
                                            </a>
                                        </li>
                                        <li class='nav-item'>
                                            <a href='#progress-attribute-details' class='nav-link' data-toggle='tab'>
                                                <span class='step-number'>04</span>
                                                <span class='step-title'>创建属性</span>
                                            </a>
                                        </li>
                                        <!--如果有配置属性配置项-->
                                        <li class='nav-item'>
                                            <a href='#progress-attribute-option' class='nav-link' data-toggle='tab'>
                                                <span class='step-number'>05</span>
                                                <span class='step-title'>配置项</span>
                                            </a>
                                        </li>
                                    </ul>

                                    <div id='bar' class='progress mt-5'>
                                        <div class='progress-bar bg-success progress-bar-striped progress-bar-animated'></div>
                                    </div>
                                    <div class='tab-content twitter-bs-wizard-tab-content'>
                                        <div class='tab-pane' id='progress-select-entity'>
                                            <div class="row">
                                                <div class="mx-auto col-lg-6 mt-2 mb-4">
                                                    <div class='input-group'>
                                                        <input type='search' class='form-control rounded' id='search-entity'
                                                               placeholder='请输入要查找的实体名或者实体代码'
                                                               aria-label='请输入要查找的实体名或者实体代码'
                                                               aria-describedby='search-addon'/>
                                                        <button type='button' class='btn btn-outline-primary'
                                                                onclick='renderSearchEntities(event)'>
                                                            搜索实体
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class='mx-auto col-lg-6 mt-2 mb-4'>
                                                    <div class='input-group'>
                                                        <select id='search-entity-result' class='selectpicker form-control rounded'
                                                                data-style='btn-primary' data-width='fit'
                                                                aria-label='搜索实体结果'
                                                                aria-describedby='search-addon'>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class='tab-pane' id='progress-attribute-details'>
                                            <form class='needs-validation' novalidate='' action='<?=$action ??'';?>' method='post'>
                                                <div class='row'>
                                                    <div class='col-lg-6'>
                                                        <div class='mb-3'>
                                                            <label class='form-label' for='progress-code'>
                                                                属性代码
                                                            </label>
                                                            <input type='text' class='form-control' id='progress-code' name="code"
                                                                   maxlength='60' data-parsley-minlength='3' placeholder="属性代码">
                                                            <div class='valid-feedback'>
                                                                填写正确！
                                                            </div>
                                                            <div class='valid-feedback'>
                                                                请正确填写正确属性代码，最小长度3个字符，最大长度60个字符
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class='col-lg-6'>
                                                        <div class='mb-3'>
                                                            <label class='form-label' for='progress-name'>
                                                                属性名
                                                            </label>
                                                            <input type='text' class='form-control' id='progress-name' name='name'
                                                                   maxlength='128' data-parsley-minlength='3' placeholder='属性名'>
                                                            <div class='valid-feedback'>
                                                                填写正确！
                                                            </div>
                                                            <div class='valid-feedback'>
                                                                请正确填写正确属性代码，最小长度3个字符，最大长度128个字符
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        <div class='tab-pane' id='progress-company-document'>
                                            <div>
                                                <form>
                                                    <div class='row'>
                                                        <div class='col-lg-6'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='progress-basicpill-pancard-input'>PAN Card</label>
                                                                <input type='text' class='form-control' id='progress-basicpill-pancard-input'>
                                                            </div>
                                                        </div>

                                                        <div class='col-lg-6'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='progress-basicpill-vatno-input'>VAT/TIN No.</label>
                                                                <input type='text' class='form-control' id='progress-basicpill-vatno-input'>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class='row'>
                                                        <div class='col-lg-6'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='progress-basicpill-cstno-input'>CST No.</label>
                                                                <input type='text' class='form-control' id='progress-basicpill-cstno-input'>
                                                            </div>
                                                        </div>

                                                        <div class='col-lg-6'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='progress-basicpill-servicetax-input'>Service Tax
                                                                    No.</label>
                                                                <input type='text' class='form-control' id='progress-basicpill-servicetax-input'>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class='row'>
                                                        <div class='col-lg-6'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='progress-basicpill-companyuin-input'>Company
                                                                    UIN</label>
                                                                <input type='text' class='form-control' id='progress-basicpill-companyuin-input'>
                                                            </div>
                                                        </div>

                                                        <div class='col-lg-6'>
                                                            <div class='mb-3'>
                                                                <label class='form-label'
                                                                       for='progress-basicpill-declaration-input'>Declaration</label>
                                                                <input type='text' class='form-control' id='progress-basicpill-declaration-input'>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                        <div class='tab-pane' id='progress-bank-detail'>
                                            <div>
                                                <form>
                                                    <div class='row'>
                                                        <div class='col-lg-6'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='progress-basicpill-namecard-input'>Name on Card</label>
                                                                <input type='text' class='form-control' id='progress-basicpill-namecard-input'>
                                                            </div>
                                                        </div>

                                                        <div class='col-lg-6'>
                                                            <div class='mb-3'>
                                                                <label>Credit Card Type</label>
                                                                <select class='form-select'>
                                                                    <option selected>Select Card Type</option>
                                                                    <option value='AE'>American Express</option>
                                                                    <option value='VI'>Visa</option>
                                                                    <option value='MC'>MasterCard</option>
                                                                    <option value='DI'>Discover</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class='row'>
                                                        <div class='col-lg-6'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='progress-basicpill-cardno-input'>Credit Card
                                                                    Number</label>
                                                                <input type='text' class='form-control' id='progress-basicpill-cardno-input'>
                                                            </div>
                                                        </div>

                                                        <div class='col-lg-6'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='progress-basicpill-card-verification-input'>Card
                                                                    Verification Number</label>
                                                                <input type='text' class='form-control'
                                                                       id='progress-basicpill-card-verification-input'>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class='row'>
                                                        <div class='col-lg-6'>
                                                            <div class='mb-3'>
                                                                <label class='form-label' for='progress-basicpill-expiration-input'>Expiration
                                                                    Date</label>
                                                                <input type='text' class='form-control' id='progress-basicpill-expiration-input'>
                                                            </div>
                                                        </div>

                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                        <div class='tab-pane' id='progress-confirm-detail'>
                                            <div class='row justify-content-center'>
                                                <div class='col-lg-6'>
                                                    <div class='text-center'>
                                                        <div class='mb-4'>
                                                            <i class='mdi mdi-check-circle-outline text-success display-4'></i>
                                                        </div>
                                                        <div>
                                                            <h5>Confirm Detail</h5>
                                                            <p class='text-muted'>If several languages coalesce, the grammar of the resulting</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <ul class='pager wizard twitter-bs-wizard-pager-link'>
                                        <li class='previous'><a href='javascript: void(0);'>Previous</a></li>
                                        <li class='next'><a href='javascript: void(0);'>Next</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->

            </div> <!-- container-fluid -->
        </div>
        <!-- End Page-content -->

        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <script>document.write(new Date().getFullYear())</script>
                        © Weline.
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end d-none d-sm-block">
                            Crafted with <i class="mdi mdi-heart text-danger"></i> By <a
                                    href="https://www.aiweline.com/">秋枫雁飞(aiweline)</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>
    <!-- end main content-->

</div>
<!-- END layout-wrapper -->
<!--右边栏-->
<!--
========================================================================================================================== 
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\templates\common\right-sidebar.phtml START
==========================================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!-- Right Sidebar -->
<div class='right-bar'>
    <div data-simplebar class='h-100'>
        <div class='rightbar-title d-flex align-items-center px-3 py-4'>

            <h5 class='m-0 me-2'><?= __('设置') ?></h5>

            <a href="javascript:void(0);" class="right-bar-toggle ms-auto">
                <i class="mdi mdi-close noti-icon"></i>
            </a>
        </div>

        <!-- Settings -->
        <hr class='mt-0'/>
        <h6 class='text-center mb-0'>系统配置</h6>
        <div class='p-4'>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        全局 默认/还原
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='reset-theme'
                               value=''>
                        <label class='form-check-label' for='data-topbar-light'>
                            还原
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='light-mode-switch'
                               id='light-mode-radio'
                               value='light' <?= $themeConfig->getThemeConfig('light-mode-switch') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-light'>
                            明亮
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='dark-mode-radio'
                               value='dark' <?= $themeConfig->getThemeConfig('dark-mode-switch') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-light'>
                            暗黑
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <hr class='mt-0'/>
        <h6 class='text-center mb-0'><?= __('布局元素') ?></h6>
        <div class='p-4'>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        导航栏
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='data-topbar-light'
                               value='light' <?= ($themeConfig->getThemeConfig('data-topbar') === 'light') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-light'>
                            明亮
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='data-topbar-colored'
                               value='colored' <?= ($themeConfig->getThemeConfig('data-topbar') === 'colored') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-colored'>
                            有色
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='data-topbar-dark'
                               value='dark' <?= ($themeConfig->getThemeConfig('data-topbar') === 'dark') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-dark'>
                            暗黑
                        </label>
                    </div>
                </div>
            </div>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        侧边栏
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar'
                               id='data-sidebar-light'
                               value='light' <?= ($themeConfig->getThemeConfig('data-sidebar') === 'light') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-light'>
                            明亮
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar'
                               id='data-sidebar-dark'
                               value='dark' <?= ($themeConfig->getThemeConfig('data-sidebar') === 'dark') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-dark'>
                            暗黑
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar-size'
                               id='data-sidebar-size-default'
                               value='' <?= ($themeConfig->getThemeConfig('data-sidebar-size') === '') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-size-default'>
                            默认尺寸
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar-size'
                               id='data-sidebar-size-small'
                               value='small' <?= ($themeConfig->getThemeConfig('data-sidebar-size') === 'small') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-size-small'>
                            小尺寸
                        </label>
                    </div>
                </div>
            </div>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        布局尺寸
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-layout-size'
                               id='data-layout-size-default'
                               value='' <?= ($themeConfig->getThemeConfig('data-layout-size') === '') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-layout-size-default'>
                            默认
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-layout-size'
                               id='data-layout-size-boxed'
                               value='boxed' <?= ($themeConfig->getThemeConfig('data-layout-size') === 'boxed') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-layout-size-boxed'>
                            盒子
                        </label>
                    </div>
                </div>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='data-layout'
                    <?= $themeConfig->getThemeConfig('data-layout') ? 'checked' : '' ?>>
                <label class="form-check-label" for="data-layout"
                       title='"默认无布局：开启后，设置水平布局，关闭后，设置垂直布局"'><?= __('水平布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='data-keep-enlarged'
                    <?= $themeConfig->getThemeConfig('data-keep-enlarged') ? 'checked' : '' ?>>
                <label class="form-check-label" for="data-keep-enlarged"
                       title='"开启后，保持内容最大化"'><?= __('保持最大化') ?></label>
            </div>

            <div class='mb-3'>
                <h5 class='font-size-14 mb-3'>
                    布局类
                </h5>
                <div class='form-check form-check-inline'>
                    <input class='form-check-input' type='radio' name='layout-class'
                           id='layout-class-default'
                           value='' <?= ($themeConfig->getThemeConfig('layout-class') === '') ? 'checked' : '' ?>>
                    <label class='form-check-label' for='layout-class-default'>
                        默认
                    </label>
                </div>
                <div class='form-check form-check-inline'>
                    <input class='form-check-input' type='radio' name='layout-class'
                           id='layout-class-vertical-collpsed'
                           value='vertical-collpsed' <?= ($themeConfig->getThemeConfig('layout-class') === 'vertical-collpsed') ? 'checked' : '' ?>>
                    <label class='form-check-label' for='layout-class-vertical-collpsed'>
                        垂直塌陷
                    </label>
                </div>
            </div>
        </div>
        <hr class="mt-0"/>
        <h6 class='text-center mb-0'><?= __('菜单布局') ?></h6>
        <div class='p-4'>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='light-sidebar'
                    <?= $themeConfig->getThemeConfig('light-sidebar') ? 'checked' : '' ?>>
                <label class="form-check-label" for="light-sidebar"><?= __('菜单明亮') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='topnav'
                    <?= $themeConfig->getThemeConfig('topnav') ? 'checked' : '' ?>>
                <label class="form-check-label" for="topnav"><?= __('页顶菜单') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='icon-sidebar'
                    <?= $themeConfig->getThemeConfig('icon-sidebar') ? 'checked' : '' ?>>
                <label class="form-check-label" for="icon-sidebar"><?= __('图标菜单') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='layouts-compact-sidebar'
                    <?= $themeConfig->getThemeConfig('layouts-compact-sidebar') ? 'checked' : '' ?>>
                <label class="form-check-label" for="layouts-compact-sidebar"><?= __('图文菜单') ?></label>
            </div>
        </div>

        <hr class="mt-0"/>
        <h6 class='text-center mb-0'><?= __('主题布局') ?></h6>
        <div class='p-4'>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='horizontal_menu_top'
                    <?= $themeConfig->getThemeConfig('horizontal_menu_top') ? 'checked' : '' ?>>
                <label class="form-check-label" for="horizontal_menu_top"><?= __('水平菜单置顶') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='boxed'
                    <?= $themeConfig->getThemeConfig('boxed') ? 'checked' : '' ?>>
                <label class="form-check-label" for="boxed"><?= __('紧凑布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='horizontal-boxed'
                    <?= $themeConfig->getThemeConfig('horizontal-boxed') ? 'checked' : '' ?>>
                <label class="form-check-label" for="horizontal-boxed"><?= __('水平紧凑布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='horizontal'
                    <?= $themeConfig->getThemeConfig('horizontal') ? 'checked' : '' ?>>
                <label class="form-check-label" for="horizontal"><?= __('水平布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='layouts-hori-topbar-dark'
                    <?= $themeConfig->getThemeConfig('layouts-hori-topbar-dark') ? 'checked' : '' ?>>
                <label class="form-check-label" for="layouts-hori-topbar-dark"><?= __('水平顶黑') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='layouts-hori-boxed-width'
                    <?= $themeConfig->getThemeConfig('layouts-hori-boxed-width') ? 'checked' : '' ?>>
                <label class="form-check-label" for="layouts-hori-boxed-width"><?= __('水平盒子') ?></label>
            </div>
        </div>
        <hr class="mt-0"/>
        <h6 class="text-center mb-0"><?= __('主题颜色') ?></h6>

        <div class="p-4">
            <div class="mb-2">
                <img src="/weline/module-admin/view/statics/assets/images/layouts/layout-1.png?v=25114" class="img-thumbnail"
                     alt="layout-1">
            </div>
            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="checkbox" id="light-mode-switch"
                    <?= $themeConfig->getThemeConfig('light-mode-switch') ? 'checked' : '' ?>>
                <label class="form-check-label" for="light-mode-switch"><?= __('明亮模式') ?></label>
            </div>

            <div class="mb-2">
                <img src="/weline/module-admin/view/statics/assets/images/layouts/layout-2.png?v=32472" class="img-thumbnail"
                     alt="layout-2">
            </div>
            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="checkbox"
                       id="dark-mode-switch" <?= $themeConfig->getThemeConfig('dark-mode-switch') ? 'checked' : '' ?>>
                <label class="form-check-label" for="dark-mode-switch"><?= __('暗黑模式') ?></label>
            </div>

            <div class="mb-2">
                <img src="/weline/module-admin/view/statics/assets/images/layouts/layout-3.png?v=88185" class="img-thumbnail"
                     alt="layout-3">
            </div>
            <div class="form-check form-switch mb-5">
                <input class="form-check-input theme-choice" type="checkbox"
                       id="rtl-mode-switch" <?= $themeConfig->getThemeConfig('rtl-mode-switch') ? 'checked' : '' ?>>
                <label class="form-check-label" for="rtl-mode-switch"><?= __('RTL模式') ?></label>
            </div>
        </div>
    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>
<!--
=======================================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\tpl\\en_US\templates\common\com_right-sidebar.phtml END
=======================================================================================================================================
-->

<!-- twitter-bootstrap-wizard js -->
<script src='/weline/module-admin/view/statics/assets/libs/twitter-bootstrap-wizard/jquery.bootstrap.wizard.min.js?v=65997'></script>

<script src='/weline/module-admin/view/statics/assets/libs/twitter-bootstrap-wizard/prettify.js?v=99511'></script>

<!-- form wizard init -->
<script src='/weline/module-admin/view/statics/assets/js/pages/form-wizard.init.js?v=49796'></script>
<script>
    function renderSearchEntities(e) {
        let search_entity = $(e.target)
        let search = search_entity.val()
        $.ajax({
            url: '<?=$this->getBackendUrl("*/backend/entity/search")?>?search=' + search,
            success: function (res) {
                let items = res['items']
                let search_entity_result = $('#search-entity-result')
                search_entity_result.empty()
                for (const item of items) {
                    search_entity_result.append(`<option value="${item.code}">${item.name}</option>`)
                }
            }
        })
    }
</script>
<!--
=================================================================================================================== 
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\templates\common\footer.phtml START
===================================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="footer-wapper">
                <?php echo framework_view_process_block([
    0 => 'Weline\\Backend\\Block\\Version',
]);?>
            </div>
        </div>
    </div>
</div>
<!-- end Account pages -->

<!-- JAVASCRIPT -->
<!--<script src="/weline/module-admin/view/statics/assets/libs/jquery/jquery.min.js?v=32562"></script>-->
<script src="/weline/module-admin/view/statics/assets/libs/bootstrap/js/bootstrap.bundle.min.js?v=59746"></script>
<script src="/weline/module-admin/view/statics/assets/libs/metismenu/metisMenu.min.js?v=21945"></script>
<script src="/weline/module-admin/view/statics/assets/libs/simplebar/simplebar.min.js?v=75777"></script>
<script src="/weline/module-admin/view/statics/assets/libs/node-waves/waves.min.js?v=75608"></script>

<script src="/weline/module-admin/view/statics/assets/js/app.js?v=41238"></script>
<!--
===================================================================================================================== 
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-backend\view\templates\public\footer.phtml START
=====================================================================================================================
 -->
<?php echo framework_view_process_block([
    0 => 'Weline\\Backend\\Block\\Footer\\Base',
]);?>
<!--加载配置页脚-->
<?php
/**@var \Weline\Framework\View\Template $this */
if($this->getFooter()){
    echo $this->getFooter()->getHtml();
}
?>
<!--
==================================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-backend\view\tpl\\en_US\templates\public\com_footer.phtml END
==================================================================================================================================
-->
<!--
================================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\vendor\weline\module-admin\view\tpl\\en_US\templates\common\com_footer.phtml END
================================================================================================================================
-->
</body>
</html>

<!--
==================================================================================================================================
模板文件：E:\WelineFramework\DEV-workspace\app\code\Weline\Eav\view\tpl\\en_US\templates\Backend\Attribute\com_form.phtml END
==================================================================================================================================
-->