<!-- 版块放在第二级别显示 -->
<div class="hidden-sm hidden-md" id="nav_pc_2">
    <div class="container">
        <ul class="nav" style="float:left">
            <?php
            /**@var \Aiweline\Bbs\Model\Forum $datum */
            foreach ($this->getData('forum') as $datum) {
                ?>
                <li class="nav-item" data-fid="<?= $datum->getData('fid') ?>"
                    data-active="fid-<?= $datum->getData('fid') ?>?>">
                    <a class="nav-link" href="<?= $datum->getUrl() ?>"><?= $datum->getName() ?></a>
                </li>
                <?php
            }
            ?>
        </ul>
        <a role="button" class="btn btn-primary ft" href="https://bbs.aiweline.com/thread-create.htm"
           style="float:right;margin:0px;color:white;padding:7px 20px;width:100px"><?php echo __('发新帖'); ?></a>

        <div class="top-search" style="width:250px;float:right;margin-right:10px;">
            <div class="form-group" style="margin-bottom:0px;">
                <form action="https://bbs.aiweline.com/search.htm" id="search_form">
                    <div class="input-group" style="height:36px;">
                        <input type="text" class="form-control" name="keyword" placeholder="search...">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit"><i class="icon-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>