<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!--加载require常用js模块-->
<!--<script src='@static(Weline_Backend::base/require.configs.js)'></script>-->
<?php
$host                               = $this->request->getBaseHost() . '/';
$base_host                          = $this->request->getPrePath();
$base_router                        = $this->request->getRouterData('router');
$current_module                     = $this->request->getModuleName();
$base_backend_url_host              = $this->request->getBaseHost() . '/' . \Weline\Framework\App\Env::getInstance()->getConfig('admin') . '/';
$base_backend_api_host              = $this->request->getBaseHost() . '/' . \Weline\Framework\App\Env::getInstance()->getConfig('api_admin') . '/';
$env_model                          = \Weline\Framework\App\Env::getInstance()->getConfig('deploy');
$theme_path                         = \Weline\Framework\App\Env::getInstance()->getTheme()['path'];
$env_model_media_base_path_template = $host . (DEV ? '/{module}/view/statics/{path}' : '/static/' . $theme_path . '/{module}/view/statics/{path}');
?>
<script>
    window.site = {
        host: '{{host}}',
        base_host: '{{base_host}}',
        env_model: '{{env_model}}',
        env_model_media_base_path_template: '{{env_model_media_base_path_template}}',
        base_backend_api_host: '{{base_backend_api_host}}',
        base_backend_url_host: '{{ base_backend_url_host }}',
        base_router: '{{base_router}}',
        i18n: <?= json_encode(Weline\Framework\Phrase\Parser::getI18nWords())?>,
        themeConfig: <?=json_encode($themeConfig->getThemeConfig()) ?? '{}';?>
    }
    window.media = (path, module = '{{current_module}}') => {
        module = module.replace('_', '/')
        return '{{env_model_media_base_path_template}}'.replace('{path}', path).replace('{module}', module)
    }
    window.path = (path) => {
        path = path.replace('*', '{{base_router}}')
        if (path.indexOf('//') === 0) {
            path = path.slice(2)
        }
        if (path.indexOf('/') === 0) {
            path = path.slice(1)
        }
        return path;
    }
    window.lang = (lang) => {
        setCookie('WELINE-USER-LANG', lang);
        window.location.reload();
    }
    window.url = (path) => {
        return window.backend_url(path);
    }
    window.frontend_url = (path) => {
        return '{{host}}' + window.path(path);
    }
    window.backend_url = (path) => {
        return '{{base_backend_url_host}}' + window.path(path);
    }
    window.api = (path) => {
        return '{{base_backend_api_host}}' + window.path(path);
    }
    window.frontend_api = (path) => {
        return '{{host}}' + window.path(path);
    }
    window.backend_api = (path) => {
        return '{{base_backend_api_host}}' + window.path(path);
    }

    /**
     * 通用打印函数
     * @param data
     */
    function p(data) {
        console.log(data)
    }

    /**
     * 设置Cookie
     * @param cname
     * @param cvalue
     * @param exdays
     */
    function setCookie(cname, cvalue, exdays) {
        let d = new Date();
        d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
        let expires = 'expires=' + d.toGMTString();
        document.cookie = cname + '=' + cvalue + '; ' + expires;
    }

    /**
     * 获取Cookie
     * @param cname
     * @returns {string}
     */
    function getCookie(cname) {
        let name = cname + '=';
        let ca = document.cookie.split(';');
        for (let i = 0; i < ca.length; i++) {
            let c = ca[i].trim();
            if (c.indexOf(name) === 0) return c.substring(name.length, c.length);
        }
        return '';
    }

    /**
     * 通用打印函数
     * @param data
     */
    function d(data) {
        console.log(data)
    }

    /**
     * 翻译函数
     * @param phrase
     * @returns {*}
     * @private
     */
    function __(phrase) {
        if (window.site.i18n[phrase] !== undefined) {
            phrase = window.site.i18n[phrase]
        }
        return phrase
    }
</script>