@template(Aiweline_Bbs::public/header.phtml)
</head>
<body>

<script src="@static(Aiweline_Bbs::push.js)"></script>
<script>
    (function () {
        var bp = document.createElement('script');
        var curProtocol = window.location.protocol.split(':')[0];
        if (curProtocol === 'https') {
            bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
        } else {
            bp.src = 'http://push.zhanzhang.baidu.com/push.js';
        }
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(bp, s);
    })();
</script>


<!--
    轻论坛导航：默认头部
    Bootstrap 4.0 推荐的 PC/Mobile 公共写法
    优点：公用性强
    缺点：结构稍微有点复杂
-->

@template(Aiweline_Bbs::public/header/header.phtml)
<!-- 版块放在第二级别显示 -->
<div class="hidden-sm hidden-md" id="nav_pc_2">
    <div class="container">
        <ul class="nav" style="float:left">
            @foreach(forum as k=>v):
                <li class="nav-item" data-fid="{v.fid}" data-active="fid-{v.fid}">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-{v.fid}.htm">{v.name}</a>
                </li>
            foreach;
        </ul>
        <a role="button" class="btn btn-primary ft" href="https://bbs.aiweline.com/thread-create-0.htm"
           style="float:right;margin:0px;color:white;padding:7px 20px;width:100px">发新帖</a>

        <div class="top-search" style="width:250px;float:right;margin-right:10px;">
            <div class="form-group" style="margin-bottom:0px;">
                <form action="https://bbs.aiweline.com/search.htm" id="search_form">
                    <div class="input-group" style="height:36px;">
                        <input type="text" class="form-control" name="keyword" placeholder="search...">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit"><i class="icon-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

<style>
    .personal li {
        float: left;
        margin: 0px;
    }

    #nav_pc_2 {
        background: white;
        padding: 10px 0px;
    }

    #nav_pc_2 a {
        color: #8590a6;
        margin-right: 5px;
        border-radius: 3px;
    }

    #nav_pc_2 a:hover {
        color: #000;
    }

    #nav_pc_2 .active a {
        color: white;
        font-weight: 600;
        background: #0084ff;
    }
</style>

<main id="body">
    <div class="container">


        <nav class="navbar shrink" role="navigation">
            <ul class="a">
                <li class="user" id="user">
                    <a href="https://bbs.aiweline.com/my.htm"><img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)"></a>
                </li>
                <li class="search">
                    <a href="https://bbs.aiweline.com/?search.htm">
                        <div></div>
                    </a>
                </li>
                <li class="add">
                    <a class="navbar-brand hidden-lg" href="https://bbs.aiweline.com/thread-create-0.htm"
                       aria-label="发表主题"><i class="icon-plus icon"></i></a>
                </li>
            </ul>
            <ul class="b">

                <li class="nav-item home active" fid="0" data-active="fid-0"><a class="nav-link"
                                                                                href="https://bbs.aiweline.com/"><i
                                class="icon-home d-md-none"></i> 首页</a></li>


                <li class="nav-item" fid="1" data-active="fid-1">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-1.htm"><i
                                class="icon-circle-o d-md-none"></i>
                        Python</a>
                </li>


                <li class="nav-item" fid="2" data-active="fid-2">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-2.htm"><i
                                class="icon-circle-o d-md-none"></i>
                        PHP</a>
                </li>


                <li class="nav-item" fid="3" data-active="fid-3">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-3.htm"><i
                                class="icon-circle-o d-md-none"></i>
                        Java</a>
                </li>


                <li class="nav-item" fid="4" data-active="fid-4">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-4.htm"><i
                                class="icon-circle-o d-md-none"></i>
                        Go</a>
                </li>


                <li class="nav-item" fid="8" data-active="fid-8">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-8.htm"><i
                                class="icon-circle-o d-md-none"></i>
                        JS</a>
                </li>


                <li class="nav-item" fid="6" data-active="fid-6">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-6.htm"><i
                                class="icon-circle-o d-md-none"></i>
                        Linux</a>
                </li>


                <li class="nav-item" fid="9" data-active="fid-9">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-9.htm"><i
                                class="icon-circle-o d-md-none"></i>
                        数据库</a>
                </li>


                <li class="nav-item" fid="7" data-active="fid-7">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-7.htm"><i
                                class="icon-circle-o d-md-none"></i>
                        下载</a>
                </li>


                <li class="nav-item" fid="10" data-active="fid-10">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-10.htm"><i
                                class="icon-circle-o d-md-none"></i>
                        新闻</a>
                </li>


                <li class="nav-item" fid="13" data-active="fid-13">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-13.htm"><i
                                class="icon-circle-o d-md-none"></i>
                        测试</a>
                </li>


                <li class="nav-item" fid="11" data-active="fid-11">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-11.htm"><i
                                class="icon-circle-o d-md-none"></i>
                        闲谈</a>
                </li>


                <li class="nav-item" fid="12" data-active="fid-12">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-12.htm"><i
                                class="icon-circle-o d-md-none"></i>
                        经验</a>
                </li>


            </ul>
        </nav>

        <div class="row">
            <div class="col-lg-9 main">
                <div id="demo" class="carousel slide mb-3" data-ride="carousel">

                    <!-- 指示符 -->
                    <ul class="carousel-indicators">
                        <li data-target="#demo" data-slide-to="0" class="active"></li>
                        <li data-target="#demo" data-slide-to="1"></li>
                        <li data-target="#demo" data-slide-to="2"></li>
                    </ul>

                    <!-- 轮播图片 -->
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <a href="https://book.aiweline.com/" target="_blank"><img
                                        src="@static(Aiweline_Bbs::/1_DYVUT272GWD4GC4.png)"></a>
                        </div>

                    </div>

                    <!-- 左右切换按钮 -->
                    <a class="carousel-control-prev" href="https://bbs.aiweline.com/#demo" data-slide="prev">
                        <span class="carousel-control-prev-icon"></span>
                    </a>
                    <a class="carousel-control-next" href="https://bbs.aiweline.com/#demo" data-slide="next">
                        <span class="carousel-control-next-icon"></span>
                    </a>

                </div>
                <div class="card card-threadlist">
                    <div class="card-header">
                        <ul class="nav nav-tabs card-header-tabs">
                            <li class="nav-item">
                                <a class="nav-link active" href="https://bbs.aiweline.com/index.htm">最新</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link  " href="https://bbs.aiweline.com/index-0-1.htm">精华</a>
                            </li>
                        </ul>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled threadlist mb-0">


                            <style>.haya-post-info-break-normal {
                                    word-break: normal;
                                }</style>


                            <li class="media thread tap top_3 " data-href="thread-1.htm" data-tid="1">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="1">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <i class="icon-top-3"></i>


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-1.htm"><span
                                                    class="huux_thread_hlight_style1">[hot] Magento安装部署：宝塔面板Nginx服务器安装部署magento2.3网站流程|Magento2 deployment on Nginx server</span></a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=78"
                                           class="badge badge-pill badge-secondary">Magento2.3.2</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=90"
                                           class="badge badge-pill badge-secondary">Nginx</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=76"
                                           class="badge badge-pill badge-secondary">安装</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=89"
                                           class="badge badge-pill badge-secondary">部署</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=82"
                                           class="badge badge-pill badge-secondary">命令行</a>


                                        <i class="icon-digest-1 icon-1x" aria-hidden="true" title="一级精华"></i>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1  " uid="1">admin</span>
									<span class="date text-grey hidden-sm">2019-6-24</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 4402</span>


                                            <span>
										<span class="text-grey mx-2"><i class="icon-reply"></i></span>
										<span class="text-grey">7月前</span>
									</span>
                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">1</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			1		</span>

                                            <span class="ml-2" title="1 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	1</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap top_3 " data-href="thread-8800.htm" data-tid="8800">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="8800">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <i class="icon-top-3"></i>


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-8800.htm"><span
                                                    class="huux_thread_hlight_style1">[hot] 国内首个个人Magento插件定制开发工作室上线啦！</span></a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=78"
                                           class="badge badge-pill badge-secondary">Magento2.3.2</a>


                                        <i class="icon-digest-3 icon-1x" aria-hidden="true" title="三级精华"></i>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">2019-9-1</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 1498</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap top_3 " data-href="thread-21318.htm" data-tid="21318">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="21318">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <i class="icon-top-3"></i>


                                        <a href="https://bbs.aiweline.com/forum-11.htm" target="_blank" title="闲谈"
                                           class="text-grey haya-post-info-home-thread-forum">[闲谈]</a>
                                        <a href="https://bbs.aiweline.com/thread-21318.htm"><span
                                                    style="color:#ff0000;">奇云小说-百万免费小说资源</span></a>
                                        <a href="https://bbs.aiweline.com/forum-11-1.htm?tagids=26"
                                           class="badge badge-pill badge-secondary">生活</a>
                                        <a href="https://bbs.aiweline.com/forum-11-1.htm?tagids=33"
                                           class="badge badge-pill badge-secondary">推荐</a>


                                        <i class="icon-digest-3 icon-1x" aria-hidden="true" title="三级精华"></i>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-11.htm" target="_blank" title="闲谈"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                闲谈 </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">10月前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 837</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap top_3 " data-href="thread-62347.htm" data-tid="62347">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="62347">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <i class="icon-top-3"></i>


                                        <a href="https://bbs.aiweline.com/forum-7.htm" target="_blank" title="下载"
                                           class="text-grey haya-post-info-home-thread-forum">[下载]</a>
                                        <a href="https://bbs.aiweline.com/thread-62347.htm"><span
                                                    class="huux_thread_hlight_style5">[] 良心国产SSH工具软件|SSH链接工具|SSH软件</span></a>
                                        <a href="https://bbs.aiweline.com/forum-7-1.htm?tagids=53"
                                           class="badge badge-pill badge-secondary">软件</a>
                                        <a href="https://bbs.aiweline.com/forum-7-1.htm?tagids=129"
                                           class="badge badge-pill badge-secondary">下载</a>


                                        <i class="icon small filetype other"></i>
                                        <i class="icon-digest-1 icon-1x" aria-hidden="true" title="一级精华"></i>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-7.htm" target="_blank" title="下载"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                下载 </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">7月前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 822</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap top_3 " data-href="thread-108503.htm" data-tid="108503">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="108503">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <i class="icon-top-3"></i>


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-108503.htm"><span
                                                    style="color:#ff0000;">【M框架】框架开发之控制器：PHP类反射去除父类方法取得控制器方法</span></a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=168"
                                           class="badge badge-pill badge-secondary">M框架</a>


                                        <i class="icon-digest-3 icon-1x" aria-hidden="true" title="三级精华"></i>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">4月前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 233</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap top_3 " data-href="thread-108547.htm" data-tid="108547">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="108547">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <i class="icon-top-3"></i>


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-108547.htm">【M框架】框架开发之模板引擎：PHP追踪debug_backtrace获得调用当前方法的父方法</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=168"
                                           class="badge badge-pill badge-secondary">M框架</a>


                                        <i class="icon-digest-3 icon-1x" aria-hidden="true" title="三级精华"></i>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">4月前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 228</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			1		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap top_3 " data-href="thread-115422.htm" data-tid="115422">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="115422">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <i class="icon-top-3"></i>


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-115422.htm"><span
                                                    style="color:#ff0000;"><span class="huux_thread_hlight_style1">[hot] 【M】MFramework框架 正在开发中，我一个人的力量太小了，真诚期待你的加入！</span></span></a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=168"
                                           class="badge badge-pill badge-secondary">M框架</a>


                                        <i class="icon-digest-3 icon-1x" aria-hidden="true" title="三级精华"></i>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">4月前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 224</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap top_3 " data-href="thread-120645.htm" data-tid="120645">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120645">


                                <a href="https://bbs.aiweline.com/user-20.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/20.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <i class="icon-top-3"></i>


                                        <a href="https://bbs.aiweline.com/forum-8.htm" target="_blank" title="JS"
                                           class="text-grey haya-post-info-home-thread-forum">[JS]</a>
                                        <a href="https://bbs.aiweline.com/thread-120645.htm"><span
                                                    style="color:#ff0000;">用canvas实现写毛笔字功能，根据停留时间改变笔画粗细</span></a>


                                        <i class="icon-digest-3 icon-1x" aria-hidden="true" title="三级精华"></i>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-8.htm" target="_blank" title="JS"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                JS </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v101" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1  " uid="20">귀하다 하지 않</span>
									<span class="date text-grey hidden-sm">2月前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 181</span>


                                            <span>
										<span class="text-grey mx-2"><i class="icon-reply"></i></span>
										<span class="text-grey">2月前</span>
									</span>
                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">2</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap top_3 " data-href="thread-120678.htm" data-tid="120678">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120678">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <i class="icon-top-3"></i>


                                        <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                           class="text-grey haya-post-info-home-thread-forum">[Linux]</a>
                                        <a href="https://bbs.aiweline.com/thread-120678.htm"><span
                                                    style="color:#ff0000;">Magento2.4 从安装到配置Varnish</span></a>
                                        <a href="https://bbs.aiweline.com/forum-6-1.htm?tagids=9"
                                           class="badge badge-pill badge-secondary">命令</a>
                                        <a href="https://bbs.aiweline.com/forum-6-1.htm?tagids=159"
                                           class="badge badge-pill badge-secondary">安装</a>
                                        <a href="https://bbs.aiweline.com/forum-6-1.htm?tagids=167"
                                           class="badge badge-pill badge-secondary">部署</a>


                                        <i class="icon-digest-3 icon-1x" aria-hidden="true" title="三级精华"></i>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                Linux </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">2月前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 187</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap top_3 " data-href="thread-120691.htm" data-tid="120691">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120691">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <i class="icon-top-3"></i>


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-120691.htm"> Magento2.4.0安装</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=1"
                                           class="badge badge-pill badge-secondary">Magento</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">2月前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 98</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120791.htm" data-tid="120791">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120791">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-120791.htm">Magento2
                                            db_schema.xml,int,varchar,decimal,text</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">3天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 23</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120790.htm" data-tid="120790">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120790">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-120790.htm">Magento2
                                            共享cookies,代理保持登录，跨域共享cookies,Store Cookies Setting</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=1"
                                           class="badge badge-pill badge-secondary">Magento</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">4天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 16</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120789.htm" data-tid="120789">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120789">


                                <a href="https://bbs.aiweline.com/user-63.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/63.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-120789.htm">国内知名Wchat团队荣誉出品顶级IM通讯聊天系统</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=4"
                                           class="badge badge-pill badge-secondary">ThinkPHP</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v101" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="63">rfedew</span>
									<span class="date text-grey">4天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 18</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120788.htm" data-tid="120788">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120788">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-120788.htm">Magento2 无法保存属性|can't save
                                            product attribute values|can't update product value</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">5天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 45</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120787.htm" data-tid="120787">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120787">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-120787.htm">Magento2 无法保存（修改）产品属性|Can't
                                            update product attribute</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=1"
                                           class="badge badge-pill badge-secondary">Magento</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">7天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 28</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120786.htm" data-tid="120786">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120786">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-9.htm" target="_blank" title="数据库"
                                           class="text-grey haya-post-info-home-thread-forum">[数据库]</a>
                                        <a href="https://bbs.aiweline.com/thread-120786.htm">RDS for
                                            MySQL权限问题（错误代码：1227，1725）|Access denied; you need (at least one of) the
                                            SUPER privilege(s) for this operation</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-9.htm" target="_blank" title="数据库"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                数据库 </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">7天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 29</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120785.htm" data-tid="120785">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120785">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                           class="text-grey haya-post-info-home-thread-forum">[Linux]</a>
                                        <a href="https://bbs.aiweline.com/thread-120785.htm">Elasticsearch 运行状态检查</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                Linux </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">7天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 35</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120784.htm" data-tid="120784">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120784">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                           class="text-grey haya-post-info-home-thread-forum">[Linux]</a>
                                        <a href="https://bbs.aiweline.com/thread-120784.htm">RabbitMq 查看版本号</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                Linux </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">7天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 35</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120783.htm" data-tid="120783">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120783">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-120783.htm">Magento2.4 elasticsearch
                                            清除影响性能的索引</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=1"
                                           class="badge badge-pill badge-secondary">Magento</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">7天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 45</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120781.htm" data-tid="120781">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120781">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-7.htm" target="_blank" title="下载"
                                           class="text-grey haya-post-info-home-thread-forum">[下载]</a>
                                        <a href="https://bbs.aiweline.com/thread-120781.htm">【工具】Navicat Premium 15
                                            破解安装</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-7.htm" target="_blank" title="下载"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                下载 </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">8天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 42</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120780.htm" data-tid="120780">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120780">


                                <a href="https://bbs.aiweline.com/user-17.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/17.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                           class="text-grey haya-post-info-home-thread-forum">[Linux]</a>
                                        <a href="https://bbs.aiweline.com/thread-120780.htm">国内知名Wchat团队荣誉出品顶级IM通讯聊天系统</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                Linux </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v101" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="17">daima</span>
									<span class="date text-grey">10天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 33</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120779.htm" data-tid="120779">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120779">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-120779.htm">Magento2 产品属性修复记录表</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=1"
                                           class="badge badge-pill badge-secondary">Magento</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">13天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 26</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120778.htm" data-tid="120778">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120778">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-120778.htm">Magento2 更新升级代码</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=1"
                                           class="badge badge-pill badge-secondary">Magento</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">14天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 42</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120777.htm" data-tid="120777">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120777">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                           class="text-grey haya-post-info-home-thread-forum">[Linux]</a>
                                        <a href="https://bbs.aiweline.com/thread-120777.htm">TCP加速方案BBR</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                Linux </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">15天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 43</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120776.htm" data-tid="120776">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120776">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                           class="text-grey haya-post-info-home-thread-forum">[Linux]</a>
                                        <a href="https://bbs.aiweline.com/thread-120776.htm">Linux CentOS8安装python</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                Linux </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">17天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 43</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120775.htm" data-tid="120775">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120775">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                           class="text-grey haya-post-info-home-thread-forum">[Linux]</a>
                                        <a href="https://bbs.aiweline.com/thread-120775.htm">Linux清空用户邮件|You have new
                                            mail in /var/spool/mail/root</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                Linux </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">17天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 50</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120774.htm" data-tid="120774">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120774">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                           class="text-grey haya-post-info-home-thread-forum">[Linux]</a>
                                        <a href="https://bbs.aiweline.com/thread-120774.htm">Linux清空当前用户的crontab任务计划</a>
                                        <a href="https://bbs.aiweline.com/forum-6-1.htm?tagids=9"
                                           class="badge badge-pill badge-secondary">命令</a>
                                        <a href="https://bbs.aiweline.com/forum-6-1.htm?tagids=121"
                                           class="badge badge-pill badge-secondary">服务器</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                Linux </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">17天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 46</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120773.htm" data-tid="120773">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120773">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                           class="text-grey haya-post-info-home-thread-forum">[Linux]</a>
                                        <a href="https://bbs.aiweline.com/thread-120773.htm">elasticsearch配置文件详解（转）</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                Linux </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">17天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 64</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120772.htm" data-tid="120772">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120772">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                           class="text-grey haya-post-info-home-thread-forum">[Linux]</a>
                                        <a href="https://bbs.aiweline.com/thread-120772.htm">【飞机】搭建飞机搭建一键搞定|科学上网</a>
                                        <a href="https://bbs.aiweline.com/forum-6-1.htm?tagids=9"
                                           class="badge badge-pill badge-secondary">命令</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-6.htm" target="_blank" title="Linux"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                Linux </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">17天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 69</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="media thread tap  " data-href="thread-120771.htm" data-tid="120771">
                                <input type="checkbox" name="modtid" class="mt-3 mr-2" value="120771">


                                <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">

                                    <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                                </a>


                                <div class="media-body">
                                    <div class="subject break-all">


                                        <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                           class="text-grey haya-post-info-home-thread-forum">[PHP]</a>
                                        <a href="https://bbs.aiweline.com/thread-120771.htm">PHP7.4双循环引用内存地址Bug</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=136"
                                           class="badge badge-pill badge-secondary">bug</a>
                                        <a href="https://bbs.aiweline.com/forum-2-1.htm?tagids=84"
                                           class="badge badge-pill badge-secondary">报错</a>


                                    </div>
                                    <div class="d-flex justify-content-between small mt-1">
                                        <div>
                                            <a href="https://bbs.aiweline.com/forum-2.htm" target="_blank" title="PHP"
                                               class="badge badge-secondary small mr-2 haya-post-info-home-thread-forum-username-before">
                                                PHP </a>

                                            <span class="haya-post-info-username ">

<span style="padding-bottom:0;margin-bottom:0;color:	#FFD700; ">

	<i class="iconfont icon-v1" style="font-size:10 !important;"></i>
	
</span>
									<span class="username text-grey mr-1 " uid="1">admin</span>
									<span class="date text-grey">17天前</span>
									</span>


                                        </div>
                                        <div class="text-muted small">


                                            <span class="ml-2"><i class="icon-eye"></i> 73</span>


                                            <span class="ml-2"
                                                  style="background: #aab0c6;color:#fff;padding: 2px 10px 2px 10px;border-radius: 12px;">0</span>
                                            <span class="ml-2">
			<i class="icon-thumbs-o-up" aria-hidden="true"></i> 
			0		</span>

                                            <span class="ml-2" title="0 收藏">
	<i class="icon-star-o" aria-hidden="true"></i> 
	0</span>
                                        </div>
                                    </div>
                                </div>
                            </li>

                        </ul>
                    </div>
                </div>

                <div class="text-center">
                    <label class="mr-3">
                        <input type="checkbox" data-target="input[name=&quot;modtid&quot;]" class="checkall mt-2 mr-2"
                               value="" aria-label="全选">全选 </label>

                    <div class="btn-group mod-button my-3" role="group" aria-label="">

                        <button class="btn btn-secondary delete" data-modal-url="mod-delete.htm" data-modal-title="删除"
                                data-modal-arg=".threadlist" data-modal-size="md">删除
                        </button>

                        <button class="btn btn-secondary move" data-modal-url="mod-move.htm" data-modal-title="移动"
                                data-modal-arg=".threadlist" data-modal-size="md">移动
                        </button>
                        <button type="button" class="btn btn-secondary sg_highlight">高亮</button>
                        <button class="btn btn-secondary top" data-modal-url="mod-top.htm" data-modal-title="置顶"
                                data-modal-arg=".threadlist" data-modal-size="md">置顶
                        </button>
                        <button type="button" class="btn btn-secondary hlight">高亮</button>
                        <button class="btn btn-secondary _close" data-modal-url="mod-close.htm" data-modal-title="关闭"
                                data-modal-arg=".threadlist" data-modal-size="md">关闭
                        </button>
                        <a href="https://bbs.aiweline.com/admin/attachlite-attachs.htm" target="_blank"
                           class="btn btn-secondary">
                            附件管理
                        </a>
                        <button class="btn btn-secondary digest" data-modal-url="mod-digest.htm" data-modal-title="精华"
                                data-modal-arg=".threadlist" data-modal-size="md">精华
                        </button>
                    </div>
                </div>


                <nav class="my-3">
                    <ul class="pagination justify-content-center flex-wrap">
                        <li class="page-item active"><a href="https://bbs.aiweline.com/index-1.htm"
                                                        class="page-link">1</a></li>
                        <li class="page-item"><a href="https://bbs.aiweline.com/index-2.htm" class="page-link">2</a>
                        </li>
                        <li class="page-item"><a href="https://bbs.aiweline.com/index-3.htm" class="page-link">3</a>
                        </li>
                        <li class="page-item"><a href="https://bbs.aiweline.com/index-4.htm" class="page-link">4</a>
                        </li>
                        <li class="page-item"><a href="https://bbs.aiweline.com/index-5.htm" class="page-link">5</a>
                        </li>
                        <li class="page-item"><a href="https://bbs.aiweline.com/index-6.htm" class="page-link">6</a>
                        </li>
                        <li class="page-item"><a href="https://bbs.aiweline.com/index-7.htm" class="page-link">7</a>
                        </li>
                        <li class="page-item"><a href="https://bbs.aiweline.com/index-8.htm" class="page-link">8</a>
                        </li>
                        <li class="page-item"><a href="https://bbs.aiweline.com/index-9.htm" class="page-link">9</a>
                        </li>
                        <li class="page-item"><a href="https://bbs.aiweline.com/index-10.htm" class="page-link">10</a>
                        </li>
                        <li class="page-item"><a href="https://bbs.aiweline.com/index-53.htm"
                                                 class="page-link">...53</a></li>
                        <li class="page-item"><a href="https://bbs.aiweline.com/index-2.htm" class="page-link">▶</a>
                        </li>
                    </ul>
                </nav>

            </div>
            <div class="col-lg-3 d-none d-lg-block aside">


                <div class="card card-site-info">

                    <div class="m-3">
                        <h5 class="text-center">微蓝网际编程论坛</h5>
                        <div class="small line-height-3">欢迎来到网际技术论坛(bbs.aiweline.com),这里有你想要的一切助力,助你尽快成为coder界大神!
                            注意:请发布教程时尽量跟随版本更新,不要让教程版本落后,让未来新秀躺坑！
                        </div>
                    </div>
                    <div class="card-footer p-2">
                        <table class="w-100 small">
                            <tbody>
                            <tr align="center">
                                <td>
                                    <span class="text-muted">主题数</span><br>
                                    <b>1074</b>
                                </td>
                                <td>
                                    <span class="text-muted">帖子数</span><br>
                                    <b>97143</b>
                                </td>
                                <td>
                                    <span class="text-muted">用户数</span><br>
                                    <b>64</b>
                                </td>

                            </tr>
                            </tbody>
                        </table>
                    </div>

                </div>
                <div class="form-group">
                    <form action="https://bbs.aiweline.com/search.htm" id="search_form">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="关键词" name="keyword">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">搜索</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card">
                    <div class="card-header text-bold">总排行</div>
                    <div class="card-body small" style="padding: 0.5rem;">
                        <div class="site-top">
                            <ul class="site-list-ul">
                                <li><span class="top_span_red">1</span><a href="https://bbs.aiweline.com/?thread-1.htm">Magento安装部署：宝塔面板Nginx服务器安装部署magento2.3网站流程|Magento2
                                        deployment on Nginx server</a></li>
                                <li><span class="top_span_red">2</span><a
                                            href="https://bbs.aiweline.com/?thread-86.htm">putenv() has been disabled
                                        for security reasons|Composer 异常</a></li>
                                <li><span class="top_span_red">3</span><a
                                            href="https://bbs.aiweline.com/?thread-87.htm">Outline科学上网搭建教程|翻-墙教程</a>
                                </li>
                                <li><span class="top_span_gray">4</span><a
                                            href="https://bbs.aiweline.com/?thread-50.htm">PhpStorm2019.3|下载-Download-phpstorm2019.3激活教程</a>
                                </li>
                                <li><span class="top_span_gray">5</span><a
                                            href="https://bbs.aiweline.com/?thread-45.htm">PHP-fpm启动/停止/重启/重载</a></li>
                                <li><span class="top_span_gray">6</span><a
                                            href="https://bbs.aiweline.com/?thread-60.htm">如何修改MySQL数据库root密码【转自：java_张金胜】|How
                                        to Modify MySQL Database Root Password</a></li>
                                <li><span class="top_span_gray">7</span><a
                                            href="https://bbs.aiweline.com/?thread-18227.htm">pcntl_signal() has been
                                        disabled for security reasons|网际编程论坛-aiweline-微蓝网</a></li>
                                <li><span class="top_span_gray">8</span><a
                                            href="https://bbs.aiweline.com/?thread-8800.htm">国内首个个人Magento插件定制开发工作室上线啦！</a>
                                </li>
                                <li><span class="top_span_gray">9</span><a
                                            href="https://bbs.aiweline.com/?thread-81.htm">Linux 开放端口号</a></li>
                                <li><span class="top_span_gray">10</span><a
                                            href="https://bbs.aiweline.com/?thread-2120.htm">Magento2
                                        后台session过期时间设置|Magento 2 backend session timeout</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header text-bold">新会员</div>
                    <div class="card-body small" style="padding: 0.5rem;">
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-63.htm" data-toggle="tooltip"
                               title="rfed">
                                <img src="@static(Aiweline_Bbs::/63.png)" alt="rfed" width="39" height="39" class="img-circle"><br>
                                rfed </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-62.htm" data-toggle="tooltip" title="通讯">
                                <img src="@static(Aiweline_Bbs::/62.png)" alt="通讯" width="39" height="39" class="img-circle"><br>
                                通讯 </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-61.htm" data-toggle="tooltip"
                               title="西瓜啦啦">
                                <img src="@static(Aiweline_Bbs::/61.png)" alt="西瓜啦啦" width="39" height="39" class="img-circle"><br>
                                西瓜啦啦 </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-60.htm" data-toggle="tooltip"
                               title="Meet">
                                <img src="@static(Aiweline_Bbs::/60.png)" alt="Meet" width="39" height="39" class="img-circle"><br>
                                Meet </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-59.htm" data-toggle="tooltip"
                               title="lunt">
                                <img src="@static(Aiweline_Bbs::/59.png)" alt="lunt" width="39" height="39" class="img-circle"><br>
                                lunt </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-58.htm" data-toggle="tooltip"
                               title="zoro">
                                <img src="@static(Aiweline_Bbs::/58.png)" alt="zoro" width="39" height="39" class="img-circle"><br>
                                zoro </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-57.htm" data-toggle="tooltip"
                               title="ding">
                                <img src="@static(Aiweline_Bbs::/57.png)" alt="ding" width="39" height="39" class="img-circle"><br>
                                ding </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-56.htm" data-toggle="tooltip"
                               title="tong">
                                <img src="@static(Aiweline_Bbs::/56.png)" alt="tong" width="39" height="39" class="img-circle"><br>
                                tong </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-55.htm" data-toggle="tooltip"
                               title="不懂球的">
                                <img src="@static(Aiweline_Bbs::/55.png)" alt="不懂球的" width="39" height="39" class="img-circle"><br>
                                不懂球的 </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-54.htm" data-toggle="tooltip" title="ABC">
                                <img src="@static(Aiweline_Bbs::/54.png)" alt="ABC" width="39" height="39" class="img-circle"><br>
                                ABC </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-53.htm" data-toggle="tooltip"
                               title="兰兰的天">
                                <img src="@static(Aiweline_Bbs::/53.png)" alt="兰兰的天" width="39" height="39" class="img-circle"><br>
                                兰兰的天 </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-52.htm" data-toggle="tooltip"
                               title="三河讲P">
                                <img src="@static(Aiweline_Bbs::/52.png)" alt="三河讲P" width="39" height="39" class="img-circle"><br>
                                三河讲P </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-51.htm" data-toggle="tooltip"
                               title="Qfyf">
                                <img src="@static(Aiweline_Bbs::/51.png)" alt="Qfyf" width="39" height="39" class="img-circle"><br>
                                Qfyf </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-50.htm" data-toggle="tooltip"
                               title="天道酬勤">
                                <img src="@static(Aiweline_Bbs::/50.png)" alt="天道酬勤" width="39" height="39" class="img-circle"><br>
                                天道酬勤 </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-49.htm" data-toggle="tooltip"
                               title="uydg">
                                <img src="@static(Aiweline_Bbs::/49.png)" alt="uydg" width="39" height="39" class="img-circle"><br>
                                uydg </a>
                        </div>
                        <div class="col-xs-4 text-center mb-3">
                            <a class="tt" href="https://bbs.aiweline.com/user-48.htm" data-toggle="tooltip" title="　">
                                <img src="@static(Aiweline_Bbs::/48.png)" alt="　" width="39" height="39" class="img-circle"><br>
                                　 </a>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <ul class="nav">
                            <li class="nav-item">
                                最新评论
                            </li>
                        </ul>
                    </div>
                    <ul class="list-unstyled threadlist mb-0">
                        <li class="media thread tap " data-href="thread-50988.htm">
                            <a href="https://bbs.aiweline.com/user-61.htm" tabindex="-1" class="ml-1 mt-1 mr-3">
                                <img class="avatar-3" src="@static(Aiweline_Bbs::/61.png)">
                            </a>
                            <div class="media-body">
                                <div class="subject">
                                    <a href="https://bbs.aiweline.com/thread-50988.htm"><p><br><span
                                                    style="col&lt;/a&gt;
							&lt;/div&gt;
							&lt;div class=" d-flex="" justify-content-between="" small="" mt-1"="">
                                            </span></p>
                                        <div>
                                            <span class="username text-grey mr-1">西瓜啦啦</span>
                                            <span class="date text-grey">24天前</span>
                                        </div>
                                    </a></div>
                                <a href="https://bbs.aiweline.com/thread-50988.htm">
                                </a></div>
                            <a href="https://bbs.aiweline.com/thread-50988.htm">
                            </a></li>
                        <a href="https://bbs.aiweline.com/thread-50988.htm">
                        </a>
                        <li class="media thread tap " data-href="thread-46282.htm"><a
                                    href="https://bbs.aiweline.com/thread-50988.htm">
                            </a><a href="https://bbs.aiweline.com/user-61.htm" tabindex="-1" class="ml-1 mt-1 mr-3">
                                <img class="avatar-3" src="@static(Aiweline_Bbs::/61.png)">
                            </a>
                            <div class="media-body">
                                <div class="subject">
                                    <a href="https://bbs.aiweline.com/thread-46282.htm"><p><br><span
                                                    style="col&lt;/a&gt;
							&lt;/div&gt;
							&lt;div class=" d-flex="" justify-content-between="" small="" mt-1"="">
                                            </span></p>
                                        <div>
                                            <span class="username text-grey mr-1">西瓜啦啦</span>
                                            <span class="date text-grey">24天前</span>
                                        </div>
                                    </a></div>
                                <a href="https://bbs.aiweline.com/thread-46282.htm">
                                </a></div>
                            <a href="https://bbs.aiweline.com/thread-46282.htm">
                            </a></li>
                        <a href="https://bbs.aiweline.com/thread-46282.htm">
                        </a>
                        <li class="media thread tap " data-href="thread-120645.htm"><a
                                    href="https://bbs.aiweline.com/thread-46282.htm">
                            </a><a href="https://bbs.aiweline.com/user-20.htm" tabindex="-1" class="ml-1 mt-1 mr-3">
                                <img class="avatar-3" src="@static(Aiweline_Bbs::/20.png)">
                            </a>
                            <div class="media-body">
                                <div class="subject">
                                    <a href="https://bbs.aiweline.com/thread-120645.htm">(≧▽≦)/&nbsp;(•̀へ•╮)&nbsp;</a>
                                </div>
                                <div class="d-flex justify-content-between small mt-1">
                                    <div>
                                        <span class="username text-grey mr-1">귀하다 하지 않</span>
                                        <span class="date text-grey">2月前</span>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="media thread tap " data-href="thread-120645.htm">
                            <a href="https://bbs.aiweline.com/user-1.htm" tabindex="-1" class="ml-1 mt-1 mr-3">
                                <img class="avatar-3" src="@static(Aiweline_Bbs::/1.png)">
                            </a>
                            <div class="media-body">
                                <div class="subject">
                                    <a href="https://bbs.aiweline.com/thread-120645.htm"><p><br><img
                                                    src="@static(Aiweline_Bbs::/div__div class=)" d-flex="" justify-content-between=""
                                                    small="" mt-1"="">
                                        </p>
                                        <div>
                                            <span class="username text-grey mr-1">admin</span>
                                            <span class="date text-grey">2月前</span>
                                        </div>
                                    </a></div>
                                <a href="https://bbs.aiweline.com/thread-120645.htm">
                                </a></div>
                            <a href="https://bbs.aiweline.com/thread-120645.htm">
                            </a></li>
                        <a href="https://bbs.aiweline.com/thread-120645.htm">
                        </a>
                        <li class="media thread tap " data-href="thread-120627.htm"><a
                                    href="https://bbs.aiweline.com/thread-120645.htm">
                            </a><a href="https://bbs.aiweline.com/user-51.htm" tabindex="-1" class="ml-1 mt-1 mr-3">
                                <img class="avatar-3" src="@static(Aiweline_Bbs::/51.png)">
                            </a>
                            <div class="media-body">
                                <div class="subject">
                                    <a href="https://bbs.aiweline.com/thread-120627.htm">牛逼！</a>
                                </div>
                                <div class="d-flex justify-content-between small mt-1">
                                    <div>
                                        <span class="username text-grey mr-1">Qfyf0078</span>
                                        <span class="date text-grey">3月前</span>
                                    </div>
                                </div>
                            </div>
                        </li>

                    </ul>
                </div><!-- 主页右侧 -->
                <div id="taghot" class="card">
                    <h5><span class="icon-tags"></span>TAG</h5>
                    <ul>
                        <li><a href="https://bbs.aiweline.com/tag-2.htm">Magento2</a></li>
                        <li><a href="https://bbs.aiweline.com/tag-5.htm">Magento</a></li>
                        <li><a href="https://bbs.aiweline.com/tag-1.htm">PHP</a></li>
                        <li><a href="https://bbs.aiweline.com/tag-3.htm">varnish</a></li>
                        <li><a href="https://bbs.aiweline.com/tag-4.htm">服务器</a></li>
                        <li><a href="https://bbs.aiweline.com/tag-6.htm">服务器压测</a></li>
                    </ul>
                </div>

                <div class="card">
                    <div class="card-header">
                        热门收藏（10）
                    </div>

                    <div class="card-body py-3">

                        <ul class="list-unstyled postlist m-0">
                            <li class="media py-1">
                                <div class="text-center text-muted">还没有发现热门收藏~</div>
                            </li>
                        </ul>
                    </div>
                </div>
                <!--【自丢网www.zidiu.com 技术维护QQ：515138】主页右侧 -->
                <!--【自丢网www.zidiu.com 技术维护QQ：515138】 -->
                <div class="card">
                    <div class="card-header">宠物小龟龟</div>
                    <div class="card-body pt-0 pb-0">
                        <div class="row pt-3">
                            <center>
                                <object type="application/x-shockwave-flash" style="outline:none;"
                                        data="@static(Aiweline_Bbs::/turtle.swf)" width="264" height="198">
                                    <param name="movie" value="plugin/zidiu_guigui/imgs/turtle.swf">
                                    <param name="AllowScriptAccess" value="always">
                                    <param name="wmode" value="opaque">
                                    <param name="scale" value="noscale">
                                    <param name="salign" value="tl">
                                </object>
                            </center>
                        </div>
                    </div>


                </div><!--【自丢网www.zidiu.com 技术维护QQ：515138】主页右侧 -->
                <!--【自丢网www.zidiu.com 技术维护QQ：515138】 -->
                <div class="card">
                    <div class="card-header">可爱的企鹅</div>
                    <div class="card-body pt-0 pb-0">
                        <div class="row pt-3">
                            <center>
                                <object type="application/x-shockwave-flash" style="outline:none;"
                                        data="@static(Aiweline_Bbs::/zidiu_penguins.swf)" width="264" height="198">
                                    <param name="movie" value="plugin/zidiu_penguins/imgs/zidiu_penguins.swf">
                                    <param name="AllowScriptAccess" value="always">
                                    <param name="wmode" value="opaque">
                                    <param name="scale" value="noscale">
                                    <param name="salign" value="tl">
                                </object>
                            </center>
                        </div>
                    </div>


                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-friendlink link-bottom">
                        <div class="card-header">在线用户--0</div>
                        <div class="card-body p-a-sm p-b-xs">
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</main>

<!--zidiu.com/技术维护QQ：515138-->

<div class="Tp1"
     style="font-size: 12px; font-family: Verdana; color: rgb(153, 153, 153); margin: 24px 0px 20px; padding: 4px; line-height: 20px; border-top-width: 1px; border-top-style: dashed; border-bottom-width: 1px; border-bottom-style: dashed; text-align:center;">
    免责声明：本站部分内容来源于网络，若有侵权请及时通知（aiweline@qq.com），我们会及时处理。
</div>


<footer class="text-muted small bg-dark py-4 mt-3" id="footer">
    <div class="container">
        <div class="row">
            <div class="col">

                Powered by <a href="http://bbs.xiuno.com/" target="_blank" class="text-muted"><b>Xiuno BBS
                        <span>4.0.4</span></b></a>
                <!--插件模板开发修改/网站维护以及建站过程中如有任何问题请联系【技术维护】QQ：1198845956-->
                您是第<b>7141318</b>位访客!欢迎您的到来，请注册发帖支持下噢！<!--插件模板开发修改/网站维护以及建站过程中如有任何问题请联系【技术维护】QQ：515138-->
                本站已安全运行了<font color="red">603</font>天。<!--aiweline.com-->
                <a href="http://www.aiweline.com/" target="_blank" style="color:#868e96;text-decoration:none;">
                </a>网际在线
            </div>
            <div class="col text-right">

                Processed: <b>0.024</b>, SQL: <b>31</b>
                <!--zidiu.com/技术维护QQ：515138-->
                <a href="http://www.miitbeian.gov.cn/" target="_blank" style="color:#868e96;text-decoration:none;">
                </a>滇ICP备18002102号
            </div>
        </div>
    </div>
</footer>


<!--[if ltg IE 9]>
<script>window.location = 'browser.htm';</script>
<![endif]-->


<script src="@static(Aiweline_Bbs::/bbs.js)"></script>
<script src="@static(Aiweline_Bbs::/jquery-3.1.0.js)"></script>
<script src="@static(Aiweline_Bbs::/popper.js)"></script>
<script src="@static(Aiweline_Bbs::/bootstrap.js)"></script>
<script src="@static(Aiweline_Bbs::/xiuno.js)"></script>
<script src="@static(Aiweline_Bbs::/bootstrap-plugin.js)"></script>
<script src="@static(Aiweline_Bbs::/async.js)"></script>
<script src="@static(Aiweline_Bbs::/form.js)"></script>
<script>
    var debug = DEBUG = 0;
    var url_rewrite_on = 1;
    var forumarr = {
        "1": "Python",
        "2": "PHP",
        "3": "Java",
        "4": "Go",
        "8": "JS",
        "6": "Linux",
        "9": "数据库",
        "7": "下载",
        "10": "新闻",
        "13": "测试",
        "11": "闲谈",
        "12": "经验"
    };
    var fid = 0;
    var uid = 1;
    var gid = 1;
    xn.options.water_image_url = 'view/img/water-small.png';	// 水印图片 / watermark image
</script>
<script src="@static(Aiweline_Bbs::/bbs.js(1))"></script>
<script>
    // 监听滚动事件，判断滚动方向
    var Before_scollH = 0
    var header_phone = $("header.header_phone")
    var header_phonex = $("header.header_phone ul:first-child")
    $(window).on('scroll', function () {
        var After_scollH = $(window).scrollTop()
        var differH = After_scollH - Before_scollH
        if (differH == 0) {
            return false
        }
        if (differH > 0) {
            if ($(document).scrollTop() < 50) {
                return false
            }
            $('nav').removeClass('shrink');
        } else {
            //if (document.documentElement.scrollHeight-document.documentElement.scrollTop-document.documentElement.clientHeight < 50) { return false }
            if ($(document).height() - $(document).scrollTop() - $(window).height() < 50) {
                return false
            }
            $('nav').addClass('shrink');
        }
        Before_scollH = After_scollH
    })
</script>
<script src="@static(Aiweline_Bbs::/user.js)" type="text/javascript"></script>
<script>
    // 主题高亮
    $('.mod-button button.hlight').on('click', function () {
        var modtid = $('input[name="modtid"]').checked();
        if (modtid.length == 0) return $.alert(lang.please_choose_thread);
        var radios = xn.form_radio('hlight', {
            "0": "<span class=\"huux_thread_hlight_style0\">取消高亮</span>",
            "1": "<span class=\"huux_thread_hlight_style1\">风格一</span>",
            "2": "<span class=\"huux_thread_hlight_style2\">风格二</span>",
            "3": "<span class=\"huux_thread_hlight_style3\">风格三</span>",
            "4": "<span class=\"huux_thread_hlight_style4\">风格四</span>",
            "5": "<span class=\"huux_thread_hlight_style5\">风格五</span>"
        });
        $.confirm("设置主题为高亮", function () {
            var tids = xn.implode('_', modtid);
            var hlight = $('input[name="hlight"]').checked();
            var postdata = {hlight: hlight};
            $.xpost(xn.url('mod-hlight-' + tids), postdata, function (code, message) {
                if (code != 0) return $.alert(message);
                $.alert(message).delay(1000).location('');
            });
        }, {'body': '<p>' + "高亮风格" + '：' + radios + '</p>'});
    })
</script>

<script>
    // 版主管理：高亮
    $('.mod-button button.sg_highlight').on('click', function () {
        var modtid = $('input[name="modtid"]').checked();
        if (modtid.length == 0) return $.alert(lang.please_choose_thread);
        var radios = xn.form_radio('sg_highlight', {
            "0": "取消高亮",
            "1": "<span style=\"color:#ff0000;\">高亮一</span>",
            "2": "<span style=\"color:#0e990b;\">高亮二</span>",
            "3": "<span style=\"color:#007ef7;\">高亮三</span>",
            "4": "<span style=\"color:#f900ff;\">高亮四</span>",
            "5": "<span style=\"color:#fff000;\">高亮五</span>"
        });
        $.confirm("设置主题为高亮", function () {
            var tids = xn.implode('_', modtid);
            var sg_highlight = $('input[name="sg_highlight"]').checked();
            var postdata = {sg_highlight: sg_highlight};
            $.xpost(xn.url('mod-sg_highlight-' + tids), postdata, function (code, message) {
                if (code != 0) return $.alert(message);
                $.alert(message).delay(1000).location('');
            });
        }, {'body': '<p>选择高亮：' + radios + '</p>'});
    })
</script>
<script>
    //前端设置cookie
    if (!$.cookie('_wish_accesscount_visited')) {
        $.cookie('_wish_accesscount_visited', 1, 5907, '/');
    }
</script>
<script type="text/javascript">
    $(function () {
////////////////
////////////////
    });
</script>
<script>
    // 版主管理：精华
    /*
    $('.mod-button button.digest').on('click', function() {
        var modtid = $('input[name="modtid"]').checked();
        if(modtid.length == 0) return $.alert(lang.please_choose_thread);
        var radios = xn.form_radio('digest', {"0": "取消精华", "1": "一级精华","2": "二级精华", "3": "三级精华"});
        $.confirm("设置主题为精华", function() {
            var tids = xn.implode('_', modtid);
            var digest = $('input[name="digest"]').checked();
            var postdata = {digest: digest};
            $.xpost(xn.url('mod-digest-'+tids), postdata, function(code, message) {
                if(code != 0) return $.alert(message);
                $.alert(message).delay(1000).location('');
            });
        }, {'body': '<p>'+"精华等级"+'：'+radios+'</p>'});
    })*/
</script>
<script>
    function xn_read_unread(tids, tid) {

        // 当前时间
        var time = xn.time();

        // 多长时间内的主题为最新主题
        var time_range = 86400 * 3;

        // 三天内的 tids
        var recent_tids = $.pdata('recent_tids') || {};

        // 已读的 tids
        var view_tids = $.pdata('view_tids') || {};

        // 提取列表页的 tid
        function fetch_recent_tids(tids) {
            var changed = false;
            $.each(tids, function (tid, last_date) {
                if (time - last_date < time_range) {
                    recent_tids[tid] = last_date;
                    changed = true;
                }
            });
            if (changed) $.pdata('recent_tids', recent_tids);
        }

        // 清理最近的 tid
        function gc_recent_tids() {
            var changed = false;
            $.each(recent_tids, function (tid, last_date) {
                if (time - last_date > time_range) {
                    delete recent_tids[tid];
                    changed = true;
                }
            });
            if (changed) $.pdata('recent_tids', recent_tids);
        }

        function gc_view_tids() {
            var changed = false;
            $.each(view_tids, function (tid, last_date) {
                if (!recent_tids[tid]) {
                    delete view_tids[tid];
                    changed = true;
                }
            });
            if (changed) $.pdata('view_tids', view_tids);
        }

        function save_view_tid(tid) {
            if (!recent_tids[tid]) return;
            view_tids[tid] = time;
            $.pdata('view_tids', view_tids);
        }

        if (tids) {
            fetch_recent_tids(tids);
            gc_recent_tids();
            //gc_view_tids();
        }
        if (tid) save_view_tid(tid);

        // 三天内的主题标记为已读

        // 遍历主题列表，标记最近的，并且未读的为加粗

        $('.thread').each(function () {
            var jthis = $(this);
            var tid = jthis.attr('tid') || jthis.data('tid');
            if (recent_tids[tid] && recent_tids[tid] > xn.intval(view_tids[tid])) {
                jthis.find('.subject').addClass('font-weight-bold');
            }
        });
    }

</script><!-- 平滑滚动 需要依赖JQ-->
<script src="@static(Aiweline_Bbs::/smooth.scroll.min.js)"></script>
<script src="@static(Aiweline_Bbs::/jquery.share.min.js)"></script>


<script>
    (function () {
        var src = "https://jspassport.ssl.qhimg.com/11.0.1.js?d182b3f28525f2db83acfaaf6e696dba";
        document.write('<script src="' + src + '" id="sozz"><\/script>');
    })();
</script>
<script src="@static(Aiweline_Bbs::/11.0.1.js)" id="sozz"></script>
<script charset="utf-8" src="@static(Aiweline_Bbs::/ab77b6ea7f3fbf79.js)"></script>


<script>
    /*
    var jtoggle_more = $('.toggle_more');
    jtoggle_more.append('<li><button class="btn btn-secondary btn-sm toggle_more_button my-3">展开</button</li>');
    var jtoggle_more_button = jtoggle_more.find('.toggle_more_button');
    jtoggle_more_button.on('click', function() {
        if(jtoggle_more.height() > 100) {
            jtoggle_more.css('max-height', '100px');
        } else {
            jtoggle_more.css('max-height', '100000px');
        }
    });
    */

    // 删除日志帖子 / Delete post
    $('body').on('click', '.update_log_delete', function () {
        var jthis = $(this);
        var href = jthis.attr('href');
        var jli = jthis.closest('li');
        var jfieldset = jli.closest('fieldset');
        var jupdates = jfieldset.find('span.updates');
        var logid = jli.data('logid');
        if (window.confirm('确定删除吗？')) {
            $.xpost(href, function (code, message) {
                if (code == 0) {
                    jli.remove();
                    jupdates.html(xn.intval(jupdates.html()) - 1);
                } else {
                    $.alert(message);
                }
            });
        }
        return false;
    });

</script>


<div id="scroll_to_top" class="d-fixed"
     style="position: fixed; _position: absolute; bottom: 80px; right: 10px; width: 70px; height: 70px; display: none;">
    <a href="javascript:void(0);"
       style="width: 70px; height: 70px; display: inline-block; background: url(@static(Aiweline_Bbs::plugin/xn_top/scroll_top.png)) no-repeat; outline: none;"
       title="返回顶部"></a>
</div>

<script>
    // 返回顶部
    var jscroll_to_top = $('#scroll_to_top');
    $(window).scroll(function () {
        if ($(window).scrollTop() >= 500) {
            jscroll_to_top.fadeIn(300);
        } else {
            jscroll_to_top.fadeOut(300);
        }
    });

    jscroll_to_top.on('click', function () {
        $('html,body').animate({scrollTop: '0px'}, 100);
    });
</script>
<script>$.require('https://hm.baidu.com/hm.js?38e521ad5fb62b974841a4e0b774566e');</script>


<script>
    $('li[data-active="fid-0"]').addClass('active');
</script>

<script>
    var tids = {
        "1": "1586967616",
        "8800": "1567339943",
        "21318": "1578115138",
        "62347": "1586178833",
        "108503": "1593765309",
        "108547": "1593768240",
        "115422": "1594904862",
        "120645": "1597904211",
        "120678": "1597976458",
        "120691": "1599121859",
        "120791": "1604987987",
        "120790": "1604916516",
        "120789": "1604907607",
        "120788": "1604829863",
        "120787": "1604646659",
        "120786": "1604643804",
        "120785": "1604628554",
        "120784": "1604628180",
        "120783": "1604628014",
        "120781": "1604546322",
        "120780": "1604366553",
        "120779": "1604127996",
        "120778": "1604020936",
        "120777": "1603940475",
        "120776": "1603794656",
        "120775": "1603793321",
        "120774": "1603793145",
        "120773": "1603790577",
        "120772": "1603789373",
        "120771": "1603787696"
    };
    xn_read_unread(tids, 0);
</script>
<script>
    jsearch_form = $('#search_form');
    jsearch_form.on('submit', function () {
        var keyword = jsearch_form.find('input[name="keyword"]').val();
        var url = xn.url('search-' + xn.urlencode(keyword));
        window.location = url;
        return false;
    });
</script>
<div style="position: absolute; z-index: -10000; top: 0px; left: 0px; right: 0px; height: 2961px;"></div>
<div style="clear: both;"></div>
</body>
<div style="all: initial;">
    <div></div>
</div></html>