<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Frontend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Frontend\Block\ThemeConfig::class);
?>
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<meta charset="UTF-8">
<title><?php echo $this->getData('title')??__('欢迎使用WelineFramework框架！'); ?></title>
<!--元数据-->
<meta content="<?php echo $this->getData('description'); ?>" name="description"/>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, shrink-to-fit=no'>
<meta content="<?php echo $this->getData('title'); ?>" name='author'/>
<meta content="<?php echo $this->getData('description'); ?>" name='description'/>
<link rel="Shortcut Icon" href="/Weline/Frontend/view/statics/img/favicon.png?v=52415">
<link rel="Shortcut Icon" href="/Weline/Frontend/view/statics/img/favicon.png?v=52415">
<link rel="Bookmark" href="/Weline/Frontend/view/statics/img/favicon.png?v=52415">
<!--加载requirejs-->
<?php if (DEV) : ?>
    <!--        <script src="/Weline/Frontend/view/statics/frontend/lib/requirejs/2.3.6/requirejs.js?v=29105"></script>-->
<?php
else:
    ?>
    <!--        <script src="/Weline/Frontend/view/statics/frontend/lib/requirejs/2.3.6/requirejs.min.js?v=64577"></script>-->
<?php
endif;
?>
<!--加载require常用js模块-->
<!--<script src="/Weline/Frontend/view/statics/base/require.configs.js?v=14197"></script>-->
<?php echo framework_view_process_block([
    'class' => 'Weline\\Frontend\\Block\\Header\\Base',
    'template' => 'Weline_Frontend::blocks/header/base.phtml',
]);?>

<!--css-->
<!--loading-->
<link  href='/Weline/Frontend/view/statics/libs/loading/loading.css?v=62032' rel="stylesheet" type="text/css"/>
<link  href='/Weline/Frontend/view/statics/libs/font-awesome-4.7.0/css/font-awesome.min.css?v=69682' rel="stylesheet" type="text/css"/>
<!-- Bootstrap Css -->
<link  href='/Weline/Frontend/view/statics/libs/bootstrap-5.1.3-dist/css/bootstrap.min.css?v=91003' rel="stylesheet" type="text/css"/>
<!--JS-->
<script  src='/Weline/Frontend/view/statics/libs/jquery/3.6.0/jquery.js?v=55538'></script>
<?php if (DEV): ?>
<!--        <script src="/Weline/Frontend/view/statics/libs/jquery/3.6.0/jquery.map?v=86972"></script>-->
<?php endif; ?>
<!--加载配置页头-->
<?php
echo $this->getHeader()->getHtml();
?>
