<div class="footer-wapper">
    @block(Weline\Backend\Block\Version)
</div>
<!--   Core JS Files   -->
<script src="@static(backend/black-dashboard-master/assets/js/core/jquery.min.js)" type="text/javascript"></script>
<script src="@static(backend/black-dashboard-master/assets/js/core/popper.min.js)" type="text/javascript"></script>
<script src="@static(backend/black-dashboard-master/assets/js/core/bootstrap.min.js)" type="text/javascript"></script>
<script src="@static(backend/black-dashboard-master/assets/js/plugins/perfect-scrollbar.jquery.min.js)"></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Chartist JS -->
<script src="@static(backend/black-dashboard-master/assets/js/plugins/chartjs.min.js)"></script>
<!--  Notifications Plugin    -->
<script src="@static(backend/black-dashboard-master/assets/js/plugins/bootstrap-notify.js)"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="@static(backend/black-dashboard-master/assets/js/black-dashboard.js?v=1.0.0)" type="text/javascript"></script>
@template(Weline_Backend::public/footer.phtml)