<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Admin\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Admin\Block\ThemeConfig::class);
?>
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<meta charset="UTF-8">
<title><?php echo $this->getData('title'); ?></title>
<!--元数据-->
<meta content="<?php echo $this->getData('description'); ?>" name="description"/>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, shrink-to-fit=no'>
<meta content="<?php echo $this->getData('title'); ?>" name='author'/>
<meta content="<?php echo $this->getData('description'); ?>" name='description'/>
<link rel="Shortcut Icon" href="@static(Weline_Backend::img/favicon.png)">
<link rel="Shortcut Icon" href="@static(Weline_Backend::img/favicon.png)">
<link rel="Bookmark" href="@static(Weline_Backend::img/favicon.png)">
<!--加载requirejs-->
<?php if (DEV) : ?>
    <!--        <script src="@static(Weline_Backend::backend/lib/requirejs/2.3.6/requirejs.js)"></script>-->
<?php
else:
    ?>
    <!--        <script src="@static(Weline_Backend::backend/lib/requirejs/2.3.6/requirejs.min.js)"></script>-->
<?php
endif;
?>
<!--加载require常用js模块-->
<!--<script src="@static(Weline_Backend::base/require.configs.js)"></script>-->
<script>
    var SITE_DATA = {
        host: '<?=$this->_request->getBaseHost()?>',
        base_host: '<?=$this->_request->isBackend() ? $this->_request->getAdminUrl('/') : $this->_request->getBaseHost()?>',
        base_router: '<?=$this->_request->getRouterData('router')?>',
        //i18n: '<?php //Weline\Framework\Phrase\Parser::getI18nWords()?>//',
        buildUrl: (path) => {
            return SITE_DATA.base_host + '/' + SITE_DATA.base_router + '/' + path;
        },
    };
</script>

<!--css-->
<!--loading-->
<link href='@static(Weline_Admin::/libs/loading/loading.css)' rel='stylesheet' type='text/css'/>
<link rel="stylesheet" href="@static(Weline_Admin::backend/lib/bootstrap-5.1.3-dist/css/bootstrap.min.css)">
<link rel="stylesheet" href="@static(Weline_Admin::backend/lib/font-awesome-4.7.0/css/font-awesome.min.css)">
<!-- Bootstrap Css -->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/bootstrap' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet"
      type="text/css"/>
<!-- Icons Css -->
<link href="@static(Weline_Admin::assets/css/icons.min.css)" rel="stylesheet" type="text/css"/>
<!-- App Css-->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/app' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet" type="text/css"/>
<!--JS-->
<script src="@static(Weline_Backend::/backend/lib/jquery/3.6.0/jquery.js)"></script>
<?php if (DEV): ?>
<!--    <script src="@static(Weline_Backend::/backend/lib/jquery/3.6.0/jquery.map)"></script>-->
<?php endif; ?>
<!--加载配置页头-->
<?php
echo $this->getHeader()->getHtml();
?>
