@template(Weline_Backend::public/head.phtml)
<title><?php echo $this->getData('title'); ?></title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
<meta content="<?php echo $this->getData('title'); ?>" name="author"/>
<meta content="<?php echo $this->getData('description'); ?>" name="description"/>

<!-- Bootstrap Css -->
<link href="@static(Weline_Admin::assets/css/bootstrap.min.css)" id="bootstrap-style" rel="stylesheet" type="text/css"/>
<!-- Icons Css -->
<link href="@static(Weline_Admin::assets/css/icons.min.css)" rel="stylesheet" type="text/css"/>
<!-- App Css-->
<link href="@static(Weline_Admin::assets/css/app.min.css)" id="app-style" rel="stylesheet" type="text/css"/>

<!--css-->
<link rel="stylesheet" href="@static(Weline_Admin::backend/lib/bootstrap-5.1.3-dist/css/bootstrap.min.css)">
<link rel="stylesheet" href="@static(Weline_Admin::backend/lib/font-awesome-4.7.0/css/font-awesome.min.css)">
<!--JS-->
<script src="@static(Weline_Backend::/backend/lib/jquery/3.6.0/jquery.js)"></script>
<php>if(DEV):</php>
<script src="@static(Weline_Backend::/backend/lib/jquery/3.6.0/jquery-3.6.0.min.map)"></script>
<php>endif;</php>
<!--加载配置页头-->
<?php
echo $this->getHeader()->getHtml();
?>
