<?php
/**@var \Weline\Framework\View\Template $this */
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang="en">
<head>
    <title><?php echo $this->getData('title'); ?></title>
    <meta charset="UTF-8">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="Shortcut Icon" href="@static(Weline_Backend::img/favicon.png)">
    <link rel="Shortcut Icon" href="@static(Weline_Backend::img/favicon.png)">
    <link rel="Bookmark" href="@static(Weline_Backend::img/favicon.png)">
    <!--css-->
    <link rel="stylesheet" href="@static(Weline_Admin::backend/lib/bootstrap-5.1.3-dist/css/bootstrap.min.css)">
    <link rel="stylesheet" href="@static(Weline_Admin::backend/lib/font-awesome-4.7.0/css/font-awesome.min.css)">
    <!--JS-->
    <script src="@static(Weline_Backend::/backend/lib/jquery/3.6.0/jquery.js)"></script>
    <php>if(DEV):</php>
    <script src="@static(Weline_Backend::/backend/lib/jquery/3.6.0/jquery-3.6.0.min.map)"></script>
    <php>endif;</php>
    <!--加载配置页头-->
    <?php
    echo $this->getHeader()->getHtml();
    ?>
