<?php
/**@var \Weline\Framework\View\Template $this */
?>
<!-- Right Sidebar -->
<div class='right-bar'>
    <div data-simplebar class='h-100'>
        <div class='rightbar-title d-flex align-items-center px-3 py-4'>

            <h5 class='m-0 me-2'><?= __('设置') ?></h5>

            <a href="javascript:void(0);" class="right-bar-toggle ms-auto">
                <i class="mdi mdi-close noti-icon"></i>
            </a>
        </div>

        <!-- Settings -->
        <hr class="mt-0"/>
        <h6 class="text-center mb-0"><?= __('选择布局') ?></h6>

        <div class="p-4">
            <div class="mb-2">
                <img src="@static(Weline_Admin::assets/images/layouts/layout-1.png)" class="img-thumbnail"
                     alt="layout-1">
            </div>

            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="checkbox" id="light-mode-switch"
                       data-bsStyle="@static(Weline_Admin::assets/css/bootstrap.min.css)"
                       data-appStyle="@static(Weline_Admin::assets/css/app.min.css)">
                <label class="form-check-label" for="light-mode-switch"><?= __('明亮模式') ?></label>
            </div>

            <div class="mb-2">
                <img src="@static(Weline_Admin::assets/images/layouts/layout-2.png)" class="img-thumbnail"
                     alt="layout-2">
            </div>
            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="checkbox" id="dark-mode-switch"
                       data-bsStyle="@static(Weline_Admin::assets/css/bootstrap-dark.min.css)"
                       data-appStyle="@static(Weline_Admin::assets/css/app-dark.min.css)" checked>
                <label class="form-check-label" for="dark-mode-switch"><?= __('暗黑模式') ?></label>
            </div>

            <div class="mb-2">
                <img src="@static(Weline_Admin::assets/images/layouts/layout-3.png)" class="img-thumbnail"
                     alt="layout-3">
            </div>
            <div class="form-check form-switch mb-5">
                <input class="form-check-input theme-choice" type="checkbox" id="rtl-mode-switch"
                       data-bsStyle="@static(Weline_Admin::assets/css/bootstrap-rtl.min.css)"
                       data-appStyle="@static(Weline_Admin::assets/css/app-rtl.min.css)">
                <label class="form-check-label" for="rtl-mode-switch"><?= __('RTL模式') ?></label>
            </div>


        </div>

    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>