<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         描述
-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $this->getData('title'); ?></title>
    <link rel="Shortcut Icon" href="/Weline/Admin/view/statics/img/favicon.png">
    <link rel="Shortcut Icon" href="/Weline/Admin/view/statics/img/favicon.png">
    <link rel="Bookmark" href="/Weline/Admin/view/statics/img/favicon.png">
    <!--加载requirejs-->
    <?php if (DEV) : ?>
        <script src="/Weline/Admin/view/statics/lib/requirejs/2.3.6/requirejs.js"></script>
    <?php
    else:
    ?>
        <script src="/Weline/Admin/view/statics/lib/requirejs/2.3.6/requirejs.min.js"></script>
    <?php endif; ?>
    <!--加载require常用js模块-->
    <script src="/Weline/Admin/view/statics/require.config.js"></script>
    <!--    <script src="/Weline/Admin/view/statics/lib/vue/vue2.6.11.js"></script>-->

