<?php
/**@var \Weline\Framework\View\Template $this */
?>
<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box text-center">
                <a href="<?=$this->getAdminUrl('admin')?>" class="logo logo-dark">
                                <span class="logo-sm">
                                    <img src="/Weline/Admin/view/statics/assets/images/logo-sm.png?v=62043" alt="logo-sm-dark"
                                         height="50">
                                </span>
                    <span class="logo-lg">
                                    <img src="/Weline/Admin/view/statics/assets/images/logo-dark.png?v=72080" alt="logo-dark"
                                         height="70">
                                </span>
                </a>

                <a href="<?=$this->getAdminUrl('admin')?>" class="logo logo-light">
                                <span class="logo-sm">
                                    <img src="/Weline/Admin/view/statics/assets/images/logo-sm.png?v=62043" alt="logo-sm-light"
                                         height="50">
                                </span>
                    <span class="logo-lg">
                                    <img src="/Weline/Admin/view/statics/assets/images/logo-light.png?v=95456" alt="logo-light"
                                         height="70">
                                </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-24 header-item waves-effect" id="vertical-menu-btn">
                <i class="ri-menu-2-line align-middle"></i>
            </button>

            <!-- App Search-->
            <form class="app-search d-none d-lg-block" onkeydown='appSearch(event)'>
                <div class="position-relative">
                    <input type="text" class="form-control" placeholder="<?= __('搜索 ...') ?>">
                    <span class="ri-search-line"></span>
                </div>
            </form>
        </div>

        <div class="d-flex">

            <div class="dropdown d-inline-block d-lg-none ms-2">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="ri-search-line"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
                     aria-labelledby="page-header-search-dropdown">

                    <form class="p-3">
                        <div class="mb-3 m-0">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="<?= __('搜索 ...') ?>">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i class="ri-search-line"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="dropdown d-none d-sm-inline-block">
                <button type="button" class="btn header-item waves-effect"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="" src="/Weline/Admin/view/statics/assets/images/flags/zh_CN.jfif?v=11289" alt="<?= __('头部语言') ?>"
                         height="16">
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <!-- item-->
                    <a href='javascript:void(0);' class='dropdown-item notify-item'>
                        <img src='/Weline/Admin/view/statics/assets/images/flags/zh_CN.jfif?v=11289' alt='user-image' class='me-1'
                             height='12'> <span class='align-middle'><?= __('中国') ?></span>
                    </a>
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="/Weline/Admin/view/statics/assets/images/flags/spain.jpg?v=46269" alt="user-image" class="me-1"
                             height="12"> <span class="align-middle">Spanish</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="/Weline/Admin/view/statics/assets/images/flags/germany.jpg?v=29545" alt="user-image" class="me-1"
                             height="12"> <span class="align-middle">German</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="/Weline/Admin/view/statics/assets/images/flags/italy.jpg?v=11676" alt="user-image" class="me-1"
                             height="12"> <span class="align-middle">Italian</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="/Weline/Admin/view/statics/assets/images/flags/russia.jpg?v=19206" alt="user-image" class="me-1"
                             height="12"> <span class="align-middle">Russian</span>
                    </a>
                </div>
            </div>

            <div class="dropdown d-none d-lg-inline-block ms-1">
                <button type="button" class="btn header-item noti-icon waves-effect"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="ri-apps-2-line"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
                    <div class="px-lg-2">
                        <div class="row g-0">
                            <div class="col">
                                <a class="dropdown-icon-item" href="#">
                                    <img src="/Weline/Admin/view/statics/assets/images/brands/github.png?v=48803" alt="Github">
                                    <span>GitHub</span>
                                </a>
                            </div>
                            <div class="col">
                                <a class="dropdown-icon-item" href="#">
                                    <img src="/Weline/Admin/view/statics/assets/images/brands/bitbucket.png?v=14790"
                                         alt="bitbucket">
                                    <span>Bitbucket</span>
                                </a>
                            </div>
                            <div class="col">
                                <a class="dropdown-icon-item" href="#">
                                    <img src="/Weline/Admin/view/statics/assets/images/brands/dribbble.png?v=13061" alt="dribbble">
                                    <span>Dribbble</span>
                                </a>
                            </div>
                        </div>

                        <div class="row g-0">
                            <div class="col">
                                <a class="dropdown-icon-item" href="#">
                                    <img src="/Weline/Admin/view/statics/assets/images/brands/dropbox.png?v=11985" alt="dropbox">
                                    <span>Dropbox</span>
                                </a>
                            </div>
                            <div class="col">
                                <a class="dropdown-icon-item" href="#">
                                    <img src="/Weline/Admin/view/statics/assets/images/brands/mail_chimp.png?v=91104"
                                         alt="mail_chimp">
                                    <span>Mail Chimp</span>
                                </a>
                            </div>
                            <div class="col">
                                <a class="dropdown-icon-item" href="#">
                                    <img src="/Weline/Admin/view/statics/assets/images/brands/slack.png?v=17990" alt="slack">
                                    <span>Slack</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="dropdown d-none d-lg-inline-block ms-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                    <i class="ri-fullscreen-line"></i>
                </button>
            </div>
            <!--通知 开始-->

            <?php
/**@var \Weline\Framework\View\Template $this */
?>
<div class="dropdown d-inline-block">
    <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-notifications-dropdown"
            data-bs-toggle="dropdown" aria-expanded="false">
        <i class="ri-notification-3-line"></i>
        <span class="noti-dot"></span>
    </button>
    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
         aria-labelledby="page-header-notifications-dropdown">
        <div class="p-3">
            <div class="row align-items-center">
                <div class="col">
                    <h6 class="m-0"> <?= __('通知') ?> </h6>
                </div>
                <div class="col-auto">
                    <a href="#!" class="small"> <?= __('查看全部') ?></a>
                </div>
            </div>
        </div>
        <div data-simplebar style="max-height: 230px;">
            <?php
            /**@var \Weline\Admin\Block\System\Notification $block */
            $block = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Admin\Block\System\Notification::class);
            /**@var \Weline\Admin\Model\System\SystemNotification $notice */
            foreach ($block->getNotices() as $notice) {
                ?>
                <a href="" class="text-reset notification-item">
                    <div class="d-flex">
                        <div class="flex-shrink-0 me-3">
                            <?php
                            if ($notice->getIsIcon()):
                                ?>
                                <div class="avatar-xs">
                                                    <span class="avatar-title bg-primary rounded-circle font-size-16">
                                                        <i class="<?= $notice->getAvatar() ?>"></i>
                                                    </span>
                                </div>
                            <?php
                            else:
                                $avatar = $notice->getAvatar()?$this->fetchTagSourceFile('static', 'Weline_Admin::'.$notice->getAvatar()):'';
                                ?>
                                <img src="<?= $avatar ?>" class="rounded-circle avatar-xs"
                                     alt="user-pic">
                            <?php
                            endif;
                            ?>
                        </div>
                        <div class="flex-grow-1">
                            <h6 class="mb-1"><?= $notice->getTitle() ?></h6>
                            <div class="font-size-12 text-muted">
                                <p class="mb-1"><?= $notice->getContent() ?></p>
                                <p class="mb-0"><i class="mdi mdi-clock-outline"></i> <?= $notice->getCreateTime() ?>
                                </p>
                            </div>
                        </div>
                    </div>
                </a>
                <?php
            }
            ?>
        </div>
        <div class="p-2 border-top">
            <div class="d-grid">
                <a class="btn btn-sm btn-link font-size-14 text-center" href="javascript:void(0)">
                    <i class="mdi mdi-arrow-right-circle me-1"></i> <?= __('查看更多') ?>
                </a>
            </div>
        </div>
    </div>
</div>

            <!--通知 结束-->

            <div class="dropdown d-inline-block user-dropdown">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user"
                         src="<?= $this->getAvatar() ?>"
                         alt="<?= __('头像') ?>">
                    <span class="d-none d-xl-inline-block ms-1"><?= $this->getUser()->getUsername() ?></span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <!-- item-->
                    <a class="dropdown-item" href="#"><i class="ri-user-line align-middle me-1"></i><?= __('资料') ?></a>
                    <a class="dropdown-item" href="#"><i
                                class="ri-wallet-2-line align-middle me-1"></i> <?= __('我的钱包') ?></a>
                    <a class="dropdown-item d-block" href="#"><span class="badge bg-success float-end mt-1">11</span><i
                                class="ri-settings-2-line align-middle me-1"></i> <?= __('设置') ?></a>
                    <a class="dropdown-item" href="#"><i
                                class="ri-lock-unlock-line align-middle me-1"></i> <?= __('锁定屏幕') ?></a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-danger" href="<?= $this->getAdminUrl('admin/login/logout') ?>"><i
                                class="ri-shut-down-line align-middle me-1 text-danger"></i> <?= __('退出') ?></a>
                </div>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon right-bar-toggle waves-effect">
                    <i class="mdi mdi-cog"></i>
                </button>
            </div>

        </div>
    </div>
</header>