<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang="en" <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    <?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<meta charset="UTF-8">
<title><?php echo $this->getData('title'); ?></title>
<!--元数据-->
<meta content="<?php echo $this->getData('description'); ?>" name="description"/>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, shrink-to-fit=no'>
<meta content="<?php echo $this->getData('title'); ?>" name='author'/>
<meta content="<?php echo $this->getData('description'); ?>" name='description'/>
<link rel="Shortcut Icon" href="/Weline/Backend/view/statics/img/favicon.png?v=98235">
<link rel="Shortcut Icon" href="/Weline/Backend/view/statics/img/favicon.png?v=98235">
<link rel="Bookmark" href="/Weline/Backend/view/statics/img/favicon.png?v=98235">
<!--加载requirejs-->
<?php if (DEV) : ?>
    <!--        <script src="/Weline/Backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.js?v=25641"></script>-->
<?php
else:
    ?>
    <!--        <script src="/Weline/Backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.min.js?v=50701"></script>-->
<?php
endif;
?>
<!--加载require常用js模块-->
<!--<script src="/Weline/Backend/view/statics/base/require.configs.js?v=44456"></script>-->
<?php echo framework_view_process_block([
    'class' => 'Weline\\Backend\\Block\\Header\\Base',
    'template' => 'Weline_Admin::blocks/header/base.phtml',
]);?>

<!--css-->
<!--loading-->
<link  href='/Weline/Admin/view/statics/libs/loading/loading.css?v=38208' rel="stylesheet" type="text/css"/>
<link  href='/Weline/Admin/view/statics/backend/lib/bootstrap-5.1.3-dist/css/bootstrap.min.css?v=77587' rel="stylesheet" type="text/css"/>
<link  href='/Weline/Admin/view/statics/backend/lib/font-awesome-4.7.0/css/font-awesome.min.css?v=88459' rel="stylesheet" type="text/css"/>
<!-- Bootstrap Css -->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/bootstrap' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet"
      type="text/css"/>
<!-- Icons Css -->
<link  href='/Weline/Admin/view/statics/assets/css/icons.min.css?v=21176' rel="stylesheet" type="text/css"/>
<!-- App Css-->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/app' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet" type="text/css"/>
<!--JS-->
<script  src='/Weline/Backend/view/statics/backend/lib/jquery/3.6.0/jquery.js?v=57928'></script>
<?php if (DEV): ?>
    <!--    <script src="/Weline/Backend/view/statics/backend/lib/jquery/3.6.0/jquery.map?v=51423"></script>-->
<?php endif; ?>
<!--加载配置页头-->
<?php
echo $this->getHeader()->getHtml();
?>

    <!-- jvectormap -->
    <link href="/Weline/Admin/view/statics/assets/libs/jqvmap/jqvmap.min.css?v=81541" rel="stylesheet"/>
    <title>Weline Admin 管理面板</title>
</head>

<!--<body data-sidebar="dark" data-topbar='colored' data-layout='horizontal'>-->
<body <?= $themeConfig->getLayouts() ?? ''; ?>>

<!-- <body data-layout="horizontal" data-topbar="dark"> -->
<!--加载中组件 开始-->
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<!--Loading-->
<section id="loading">
    <div class='loader loader-1'>
        <div class='loader-outter'></div>
        <div class='loader-inner'></div>
    </div>
</section>
<script>
    function showLoading() {
        $('#loading').show()
    }

    function hideLoading() {
        $('#loading').hide()
    }

    $(function () {
        $('#loading').hide()
    })
</script>
<!-- 开始 页面 -->
<div id="layout-wrapper">

    <!--页头工具条 开始-->
    <?php echo framework_view_process_block([
    'class' => 'Weline\\Admin\\Block\\Backend\\Page\\Topbar',
    'cache' => '300',
]);?>
    <!--页头工具条 结束-->

    <!-- ========== Topnav Start ========== -->
    <!--页头菜单栏 开始-->
    <?php echo framework_view_process_block([
    'class' => 'Weline\\Admin\\Block\\Backend\\Page\\Topnav',
    'cache' => '300',
]);?>
    <!--页头菜单栏 结束-->

    <!-- ========== Left Sidebar Start ========== -->
    <!--左侧菜单栏 开始-->
    <?php
/**@var \Weline\Framework\View\Template $this */

use Weline\Framework\Manager\ObjectManager;

?>
<?php
$themeConfig = ObjectManager::getInstance('\Weline\Backend\Block\ThemeConfig');
if (!$themeConfig->getThemeConfig('topnav')):
?>
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <?php
                /**@var \Weline\Backend\Model\Menu $menuModel */
                $menuModel = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Model\Menu::class);
                $menus     = $menuModel->getMenuTree();
                /**@var \Weline\Backend\Model\Menu $menu */
                foreach ($menus as $menu) {
                    if (empty($menu->getAction()) && empty($menu->getParentSource()) && empty($menu->getPid())) {
                        ?>
                        <li class="menu-title"><i
                                    class="<?= $menu->getIcon() ?>"></i><span><?= __($menu->getTitle()) ?></span></li>
                        <?php
                    }
                    $submenus = $menu->getSubMenu();
                    /**@var \Weline\Backend\Model\Menu $submenu */
                    foreach ($submenus as $submenu) {
                        $level_3_menus = $submenu->getSubMenu();
                        if (empty($level_3_menus)) {
                            if ('/' === $submenu->getAction()) {
                                ?>
                                <li>
                                    <a href="<?= $submenu->getUrl() ?>" class="waves-effect">
                                        <i class="<?= $submenu->getIcon() ?>"></i><span
                                                class="badge rounded-pill bg-primary float-end">3</span>
                                        <span><?= $submenu->getTitle() ?></span>
                                    </a>
                                </li>
                                <?php
                            } else {
                                ?>
                                <li>
                                    <a href="<?= $submenu->getUrl() ?>" class=" waves-effect">
                                        <i class="<?= $submenu->getIcon() ?>"></i>
                                        <span><?= $submenu->getTitle() ?></span>
                                    </a>
                                </li>
                                <?php
                            }
                        } else {
                            if ('/' === $submenu->getAction()) {
                                ?>
                                <li>
                                    <a href="<?= $submenu->getUrl() ?>" class="waves-effect">
                                        <i class="<?= $submenu->getIcon() ?>"></i><span
                                                class="badge rounded-pill bg-primary float-end">3</span>
                                        <span><?= $submenu->getTitle() ?></span>
                                    </a>
                                </li>
                                <?php
                            } else {
                                ?>
                                <li>
                                    <a href="javascript: void(0);"
                                       class="has-arrow waves-effect">
                                        <i class="<?= $submenu->getIcon() ?>"></i>
                                        <span><?= $submenu->getTitle() ?></span>
                                    </a>
                                    <ul class="sub-menu" aria-expanded="false">
                                        <?php
                                        /**@var \Weline\Backend\Model\Menu $level_3_menu */
                                        foreach ($level_3_menus as $level_3_menu) {
                                            ?>
                                            <li>
                                                <a href="<?= $level_3_menu->getUrl() ?>"><i
                                                            class="<?= $level_3_menu->getIcon() ?>"></i><?= $level_3_menu->getTitle() ?>
                                                </a>
                                            </li>
                                            <?php
                                        }
                                        ?>
                                    </ul>
                                </li>
                                <?php
                            }
                        }
                    }
                }
                ?>
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<?php endif; ?>
    <!--左侧菜单栏 结束-->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
<div class='main-content'>

    <div class='page-content'>
        <div class='container-fluid'>
            <div class='row'>
                <!--消息-->
                <?php
echo \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Framework\Manager\MessageManager::class);
?>
            </div>
            <!-- start page title -->
            <div class='row'>
                <div class='col-12'>
                    <div class='page-title-box d-sm-flex align-items-center justify-content-between'>
                        <h4 class='mb-sm-0'>
                            面板
                        </h4>

                        <div class='page-title-right'>
                            <ol class='breadcrumb m-0'>
                                <li class='breadcrumb-item'><a href='javascript: void(0);'>
                                        后台
                                    </a></li>
                                <li class='breadcrumb-item active'>
                                    面板
                                </li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class='row'>
                <div class='col-xl-3 col-sm-6'>
                    <?php echo framework_view_process_block([
    'class' => 'Weline\\Admin\\Block\\Backend\\Total',
    'model' => 'Weline\\Backend\\Model\\BackendUser',
    'title' => '用户',
    'last-period' => 'yesterday',
    'now-period' => 'today',
    'tip' => '环比昨日',
]);?>
                </div>
                <!-- end col -->

                <div class='col-xl-3 col-sm-6'>
                    <div class='card'>
                        <div class='card-body'>
                            <div class='d-flex'>
                                <div class='flex-shrink-0 me-3 align-self-center'>
                                    <div id='radialchart-2' class='apex-charts' dir='ltr'></div>
                                </div>
                                <div class='flex-grow-1 overflow-hidden'>
                                    <p class='mb-1'>
                                        每分钟浏览者
                                    </p>
                                    <h5 class='mb-3'>50</h5>
                                    <p class='text-truncate mb-0'><span class='text-success me-2'> 1.7% <i
                                                    class='ri-arrow-right-up-line align-bottom ms-1'></i></span>
                                        环比
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!-- end card-body -->
                    </div>
                    <!-- end card -->
                </div>
                <!-- end col -->

                <div class='col-xl-3 col-sm-6'>
                    <div class='card'>
                        <div class='card-body'>
                            <div class='d-flex text-muted'>
                                <div class='flex-shrink-0 me-3 align-self-center'>
                                    <div id='radialchart-3' class='apex-charts' dir='ltr'></div>
                                </div>
                                <div class='flex-grow-1 overflow-hidden'>
                                    <p class='mb-1'>
                                        跳出率
                                    </p>
                                    <h5 class='mb-3'>24.03 %</h5>
                                    <p class='text-truncate mb-0'><span class='text-danger me-2'> 0.01% <i
                                                    class='ri-arrow-right-down-line align-bottom ms-1'></i></span>
                                        环比
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!-- end card-body -->
                    </div>
                    <!-- end card -->
                </div>
                <!-- end col -->

                <div class='col-xl-3 col-sm-6'>
                    <div class='card'>
                        <div class='card-body'>
                            <div class='d-flex text-muted'>
                                <div class='flex-shrink-0  me-3 align-self-center'>
                                    <div class='avatar-sm'>
                                        <div class='avatar-title bg-light rounded-circle text-primary font-size-20'>
                                            <i class='ri-group-line'></i>
                                        </div>
                                    </div>
                                </div>
                                <div class='flex-grow-1 overflow-hidden'>
                                    <p class='mb-1'>
                                        新浏览者
                                    </p>
                                    <h5 class='mb-3'>435</h5>
                                    <p class='text-truncate mb-0'><span class='text-success me-2'> 0.01% <i
                                                    class='ri-arrow-right-up-line align-bottom ms-1'></i></span>
                                        环比
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!-- end card-body -->
                    </div>
                    <!-- end card -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->

            <div class='row'>
                <div class='col-xl-8'>
                    <div class='card'>
                        <div class='card-body'>
                            <div class='d-flex align-items-center'>
                                <div class='flex-grow-1'>
                                    <h5 class='card-title'>
                                        概览
                                    </h5>
                                </div>
                                <div class='flex-shrink-0'>
                                    <div>
                                        <button type='button' class='btn btn-soft-secondary btn-sm'>
                                            全部
                                        </button>
                                        <button type='button' class='btn btn-soft-primary btn-sm'>
                                            1月
                                        </button>
                                        <button type='button' class='btn btn-soft-secondary btn-sm'>
                                            半年
                                        </button>
                                        <button type='button' class='btn btn-soft-secondary btn-sm active'>
                                            1年
                                        </button>
                                    </div>
                                </div>
                            </div>

                            <div>
                                <div id='mixed-chart' class='apex-charts' dir='ltr'></div>
                            </div>
                        </div>
                        <!-- end card-body -->

                        <div class='card-body border-top'>
                            <div class='text-muted text-center'>
                                <div class='row'>
                                    <div class='col-4 border-end'>
                                        <div>
                                            <p class='mb-2'><i
                                                        class='mdi mdi-circle font-size-12 text-primary me-1'></i>
                                                费用
                                            </p>
                                            <h5 class='font-size-16 mb-0'>$ 8,524 <span
                                                        class='text-success font-size-12'><i
                                                            class='mdi mdi-menu-up font-size-14 me-1'></i>1.2 %</span>
                                            </h5>
                                        </div>
                                    </div>
                                    <div class='col-4 border-end'>
                                        <div>
                                            <p class='mb-2'><i
                                                        class='mdi mdi-circle font-size-12 text-light me-1'></i>
                                                维护
                                            </p>
                                            <h5 class='font-size-16 mb-0'>$ 8,524 <span
                                                        class='text-success font-size-12'><i
                                                            class='mdi mdi-menu-up font-size-14 me-1'></i>2.0 %</span>
                                            </h5>
                                        </div>
                                    </div>
                                    <div class='col-4'>
                                        <div>
                                            <p class='mb-2'><i
                                                        class='mdi mdi-circle font-size-12 text-danger me-1'></i>
                                                利润
                                            </p>
                                            <h5 class='font-size-16 mb-0'>$ 8,524 <span
                                                        class='text-success font-size-12'><i
                                                            class='mdi mdi-menu-up font-size-14 me-1'></i>0.4 %</span>
                                            </h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end card-body -->
                    </div>
                    <!-- end card -->
                </div>
                <!-- end col -->

                <div class='col-xl-4'>
                    <div class='card'>
                        <div class='card-body'>
                            <div class='d-flex  align-items-center'>
                                <div class='flex-grow-1'>
                                    <h5 class='card-title'>
                                        社媒来源
                                    </h5>
                                </div>
                                <div class='flex-shrink-0'>
                                    <select class='form-select form-select-sm mb-0 my-n1'>
                                        <option value='MAY' selected=''>
                                            五月
                                        </option>
                                        <option value='AP'>
                                            四月
                                        </option>
                                        <option value='MA'>
                                            三月
                                        </option>
                                        <option value='FE'>
                                            二月
                                        </option>
                                        <option value='JA'>
                                            一月
                                        </option>
                                        <option value='DE'>
                                            十二月
                                        </option>
                                    </select>
                                </div>
                            </div>

                            <div>
                                <div id='radialBar-chart' class='apex-charts' dir='ltr'></div>
                            </div>

                            <div class='row'>
                                <div class='col-4'>
                                    <div class='social-source text-center mt-3'>
                                        <div class='avatar-xs mx-auto mb-3'>
                                                        <span class='avatar-title rounded-circle bg-primary font-size-18'>
                                                            <i class='ri  ri-facebook-circle-fill text-white'></i>
                                                        </span>
                                        </div>
                                        <h5 class='font-size-15'>Facebook</h5>
                                        <p class='text-muted mb-0'>125 sales</p>
                                    </div>
                                </div>
                                <div class='col-4'>
                                    <div class='social-source text-center mt-3'>
                                        <div class='avatar-xs mx-auto mb-3'>
                                                        <span class='avatar-title rounded-circle bg-info font-size-18'>
                                                            <i class='ri  ri-twitter-fill text-white'></i>
                                                        </span>
                                        </div>
                                        <h5 class='font-size-15'>Twitter</h5>
                                        <p class='text-muted mb-0'>112 sales</p>
                                    </div>
                                </div>
                                <div class='col-4'>
                                    <div class='social-source text-center mt-3'>
                                        <div class='avatar-xs mx-auto mb-3'>
                                                        <span class='avatar-title rounded-circle bg-danger font-size-18'>
                                                            <i class='ri ri-instagram-line text-white'></i>
                                                        </span>
                                        </div>
                                        <h5 class='font-size-15'>Instagram</h5>
                                        <p class='text-muted mb-0'>104 sales</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end card-body -->
                    </div>
                    <!-- end card -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->

            <div class='row'>
                <div class='col-xl-4'>
                    <div class='card'>
                        <div class='card-body'>
                            <h5 class='card-title'>
                                订单统计
                            </h5>
                            <div>
                                <ul class='list-unstyled'>
                                    <li class='py-3'>
                                        <div class='d-flex'>
                                            <div class='avatar-xs align-self-center me-3'>
                                                <div class='avatar-title rounded-circle bg-light text-primary font-size-18'>
                                                    <i class='ri-checkbox-circle-line'></i>
                                                </div>
                                            </div>
                                            <div class='flex-grow-1'>
                                                <p class='text-muted mb-2'>Completed</p>
                                                <div class='progress progress-sm animated-progess'>
                                                    <div class='progress-bar bg-success' role='progressbar'
                                                         style='width: 70%' aria-valuenow='70' aria-valuemin='0'
                                                         aria-valuemax='100'></div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <li class='py-3'>
                                        <div class='d-flex'>
                                            <div class='avatar-xs align-self-center me-3'>
                                                <div class='avatar-title rounded-circle bg-light text-primary font-size-18'>
                                                    <i class='ri-calendar-2-line'></i>
                                                </div>
                                            </div>
                                            <div class='flex-grow-1'>
                                                <p class='text-muted mb-2'>Pending</p>
                                                <div class='progress progress-sm animated-progess'>
                                                    <div class='progress-bar bg-warning' role='progressbar'
                                                         style='width: 45%' aria-valuenow='45' aria-valuemin='0'
                                                         aria-valuemax='100'></div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <li class='py-3'>
                                        <div class='d-flex'>
                                            <div class='avatar-xs align-self-center me-3'>
                                                <div class='avatar-title rounded-circle bg-light text-primary font-size-18'>
                                                    <i class='ri-close-circle-line'></i>
                                                </div>
                                            </div>
                                            <div class='flex-grow-1'>
                                                <p class='text-muted mb-2'>Cancel</p>
                                                <div class='progress progress-sm animated-progess'>
                                                    <div class='progress-bar bg-danger' role='progressbar'
                                                         style='width: 19%' aria-valuenow='19' aria-valuemin='0'
                                                         aria-valuemax='100'></div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>

                            <hr>

                            <div class='text-center'>
                                <div class='row'>
                                    <div class='col-4'>
                                        <div class='mt-2'>
                                            <p class='text-muted mb-2'>Completed</p>
                                            <h5 class='font-size-16 mb-0'>70</h5>
                                        </div>
                                    </div>
                                    <div class='col-4'>
                                        <div class='mt-2'>
                                            <p class='text-muted mb-2'>Pending</p>
                                            <h5 class='font-size-16 mb-0'>45</h5>
                                        </div>
                                    </div>
                                    <div class='col-4'>
                                        <div class='mt-2'>
                                            <p class='text-muted mb-2'>Cancel</p>
                                            <h5 class='font-size-16 mb-0'>19</h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end card-body -->
                    </div>
                    <!-- end card -->
                </div>
                <!-- end col -->

                <div class='col-lg-4'>
                    <div class='card'>
                        <div class='card-body'>
                            <h4 class='card-title'>
                                通知
                            </h4>

                            <div class='pe-3' data-simplebar style='max-height: 287px;'>
                                <a href='#' class='text-body d-block'>
                                    <div class='d-flex py-3'>
                                        <div class='flex-shrink-0 me-3 align-self-center'>
                                            <img class='rounded-circle avatar-xs' alt=''
                                                 src='/Weline/Admin/view/statics/assets/images/users/avatar-2.jpg?v=21179'>
                                        </div>

                                        <div class='flex-grow-1 overflow-hidden'>
                                            <h5 class='font-size-14 mb-1'>Scott Elliott</h5>
                                            <p class='text-truncate mb-0'>
                                                If several languages coalesce
                                            </p>
                                        </div>
                                        <div class='flex-shrink-0 font-size-13'>
                                            20 min ago
                                        </div>
                                    </div>
                                </a>
                                <a href='#' class='text-body d-block'>
                                    <div class='d-flex py-3'>
                                        <div class='flex-shrink-0 me-3 align-self-center'>
                                            <div class='avatar-xs'>
                                                            <span class='avatar-title bg-soft-primary rounded-circle text-primary'>
                                                                <i class='mdi mdi-account-supervisor'></i>
                                                            </span>
                                            </div>
                                        </div>
                                        <div class='flex-grow-1 overflow-hidden'>
                                            <h5 class='font-size-14 mb-1'>Team A</h5>
                                            <p class='text-truncate mb-0'>
                                                Team A Meeting 9:15 AM
                                            </p>
                                        </div>
                                        <div class='flex-shrink-0 font-size-13'>
                                            9:00 am
                                        </div>
                                    </div>
                                </a>
                                <a href='#' class='text-body d-block'>
                                    <div class='d-flex py-3'>
                                        <div class='flex-shrink-0 me-3 align-self-center'>
                                            <img class='rounded-circle avatar-xs' alt=''
                                                 src='/Weline/Admin/view/statics/assets/images/users/avatar-3.jpg?v=45631'>
                                        </div>
                                        <div class='flex-grow-1 overflow-hidden'>
                                            <h5 class='font-size-14 mb-1'>Frank Martin</h5>
                                            <p class='text-truncate mb-0'>
                                                Neque porro quisquam est
                                            </p>
                                        </div>
                                        <div class='flex-shrink-0 font-size-13'>
                                            8:54 am
                                        </div>
                                    </div>
                                </a>
                                <a href='#' class='text-body d-block'>
                                    <div class='d-flex py-3'>
                                        <div class='flex-shrink-0 me-3 align-self-center'>
                                            <div class='avatar-xs'>
                                                            <span class='avatar-title bg-soft-primary rounded-circle text-primary'>
                                                                <i class='mdi mdi-email-outline'></i>
                                                            </span>
                                            </div>
                                        </div>
                                        <div class='flex-grow-1 overflow-hidden'>
                                            <h5 class='font-size-14 mb-1'>Updates</h5>
                                            <p class='text-truncate mb-0'>
                                                It will be as simple as fact
                                            </p>
                                        </div>
                                        <div class='flex-shrink-0 font-size-13'>
                                            27-03-2020
                                        </div>
                                    </div>
                                </a>

                                <a href='#' class='text-body d-block'>
                                    <div class='d-flex py-3'>
                                        <div class='flex-shrink-0 me-3 align-self-center'>
                                            <img class='rounded-circle avatar-xs' alt=''
                                                 src='/Weline/Admin/view/statics/assets/images/users/avatar-4.jpg?v=37931'>
                                        </div>
                                        <div class='flex-grow-1 overflow-hidden'>
                                            <h5 class='font-size-14 mb-1'>Terry Garrick</h5>
                                            <p class='text-truncate mb-0'>
                                                At vero eos et accusamus et
                                            </p>
                                        </div>
                                        <div class='flex-shrink-0 font-size-13'>
                                            27-03-2020
                                        </div>
                                    </div>
                                </a>

                            </div>
                        </div>
                        <!-- end card-body -->
                    </div>
                    <!-- end card -->
                </div>
                <!-- end col -->

                <div class='col-lg-4'>
                    <div class='card'>
                        <div class='card-body'>
                            <h5 class='card-title mb-3'>
                                区域营收
                            </h5>

                            <div>
                                <div id='usa' style='height: 226px'></div>
                            </div>

                            <div class='text-center mt-4'>
                                <a href='#' class='btn btn-primary btn-sm'>
                                    查看更多
                                </a>
                            </div>
                        </div>
                        <!-- end card-body -->
                    </div>
                    <!-- end card -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->

            <div class='row'>
                <div class='col-lg-12'>
                    <div class='card'>
                        <div class='card-body'>
                            <h4 class='card-title mb-4'>
                                最近成交
                            </h4>

                            <div class='table-responsive'>
                                <table class='table table-centered table-nowrap mb-0'>
                                    <thead>
                                    <tr>
                                        <th scope='col' style='width: 50px;'>
                                            <div class='form-check'>
                                                <input type='checkbox' class='form-check-input' id='customCheckall'>
                                                <label class='form-check-label' for='customCheckall'></label>
                                            </div>
                                        </th>
                                        <th scope='col' style='width: 60px;'></th>
                                        <th scope='col'>ID & Name</th>
                                        <th scope='col'>Date</th>
                                        <th scope='col'>Price</th>
                                        <th scope='col'>Quantity</th>
                                        <th scope='col'>Amount</th>
                                        <th scope='col'>Status</th>
                                        <th scope='col'>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>
                                            <div class='form-check'>
                                                <input type='checkbox' class='form-check-input' id='customCheck1'>
                                                <label class='form-check-label' for='customCheck1'></label>
                                            </div>
                                        </td>
                                        <td>
                                            <img src='/Weline/Admin/view/statics/assets/images/users/avatar-2.jpg?v=21179' alt='user'
                                                 class='avatar-xs rounded-circle'/>
                                        </td>
                                        <td>
                                            <p class='mb-1 font-size-12'>#AP1234</p>
                                            <h5 class='font-size-15 mb-0'>David Wiley</h5>
                                        </td>
                                        <td>02 Nov, 2019</td>
                                        <td>$ 1,234</td>
                                        <td>1</td>

                                        <td>
                                            $ 1,234
                                        </td>
                                        <td>
                                            <i class='mdi mdi-checkbox-blank-circle text-success me-1'></i> Confirm
                                        </td>
                                        <td>
                                            <button type='button' class='btn btn-outline-success btn-sm'>Edit
                                            </button>
                                            <button type='button' class='btn btn-outline-danger btn-sm'>Cancel
                                            </button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class='form-check'>
                                                <input type='checkbox' class='form-check-input' id='customCheck2'>
                                                <label class='form-check-label' for='customCheck2'></label>
                                            </div>
                                        </td>
                                        <td>
                                            <div class='avatar-xs'>
                                                                <span class='avatar-title rounded-circle bg-soft-primary text-success'>
                                                                    W
                                                                </span>
                                            </div>
                                        </td>
                                        <td>
                                            <p class='mb-1 font-size-12'>#AP1235</p>
                                            <h5 class='font-size-15 mb-0'>Walter Jones</h5>
                                        </td>
                                        <td>04 Nov, 2019</td>
                                        <td>$ 822</td>
                                        <td>2</td>

                                        <td>
                                            $ 1,644
                                        </td>
                                        <td>
                                            <i class='mdi mdi-checkbox-blank-circle text-success me-1'></i> Confirm
                                        </td>
                                        <td>
                                            <button type='button' class='btn btn-outline-success btn-sm'>Edit
                                            </button>
                                            <button type='button' class='btn btn-outline-danger btn-sm'>Cancel
                                            </button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class='form-check'>
                                                <input type='checkbox' class='form-check-input' id='customCheck3'>
                                                <label class='form-check-label' for='customCheck3'></label>
                                            </div>
                                        </td>
                                        <td>
                                            <img src='/Weline/Admin/view/statics/assets/images/users/avatar-3.jpg?v=45631' alt='user'
                                                 class='avatar-xs rounded-circle'/>
                                        </td>
                                        <td>
                                            <p class='mb-1 font-size-12'>#AP1236</p>
                                            <h5 class='font-size-15 mb-0'>Eric Ryder</h5>
                                        </td>
                                        <td>05 Nov, 2019</td>
                                        <td>$ 1,153</td>
                                        <td>1</td>

                                        <td>
                                            $ 1,153
                                        </td>
                                        <td>
                                            <i class='mdi mdi-checkbox-blank-circle text-danger me-1'></i> Cancel
                                        </td>
                                        <td>
                                            <button type='button' class='btn btn-outline-success btn-sm'>Edit
                                            </button>
                                            <button type='button' class='btn btn-outline-danger btn-sm'>Cancel
                                            </button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class='form-check'>
                                                <input type='checkbox' class='form-check-input' id='customCheck4'>
                                                <label class='form-check-label' for='customCheck4'></label>
                                            </div>
                                        </td>
                                        <td>
                                            <img src='/Weline/Admin/view/statics/assets/images/users/avatar-6.jpg?v=75876' alt='user'
                                                 class='avatar-xs rounded-circle'/>
                                        </td>
                                        <td>
                                            <p class='mb-1 font-size-12'>#AP1237</p>
                                            <h5 class='font-size-15 mb-0'>Kenneth Jackson</h5>
                                        </td>
                                        <td>06 Nov, 2019</td>
                                        <td>$ 1,365</td>
                                        <td>1</td>

                                        <td>
                                            $ 1,365
                                        </td>
                                        <td>
                                            <i class='mdi mdi-checkbox-blank-circle text-success me-1'></i> Confirm
                                        </td>
                                        <td>
                                            <button type='button' class='btn btn-outline-success btn-sm'>Edit
                                            </button>
                                            <button type='button' class='btn btn-outline-danger btn-sm'>Cancel
                                            </button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class='form-check'>
                                                <input type='checkbox' class='form-check-input' id='customCheck5'>
                                                <label class='form-check-label' for='customCheck5'></label>
                                            </div>
                                        </td>
                                        <td>
                                            <div class='avatar-xs'>
                                                                <span class='avatar-title rounded-circle bg-soft-primary text-success'>
                                                                    R
                                                                </span>
                                            </div>
                                        </td>
                                        <td>
                                            <p class='mb-1 font-size-12'>#AP1238</p>
                                            <h5 class='font-size-15 mb-0'>Ronnie Spiller</h5>
                                        </td>
                                        <td>08 Nov, 2019</td>
                                        <td>$ 740</td>
                                        <td>2</td>

                                        <td>
                                            $ 1,480
                                        </td>
                                        <td>
                                            <i class='mdi mdi-checkbox-blank-circle text-warning me-1'></i> Pending
                                        </td>
                                        <td>
                                            <button type='button' class='btn btn-outline-success btn-sm'>Edit
                                            </button>
                                            <button type='button' class='btn btn-outline-danger btn-sm'>Cancel
                                            </button>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- end card-body -->
                    </div>
                    <!-- end card -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->

        </div>
        <!-- container-fluid -->
    </div>
    <!-- End Page-content -->

    <footer class='footer'>
        <div class='container-fluid'>
            <div class='row'>
                <div class='col-sm-6'>
                    <script>document.write(new Date().getFullYear())</script>
                    © Weline.
                </div>
                <div class='col-sm-6'>
                    <div class='text-sm-end d-none d-sm-block'>
                        Crafted with <i class='mdi mdi-heart text-danger'></i> By <a
                                href='https://www.aiweline.com/'>秋枫雁飞(aiweline)</a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

</div>
<!-- end main content-->

</div>
<!-- END layout-wrapper -->

<!--右边栏-->
<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!-- Right Sidebar -->
<div class='right-bar'>
    <div data-simplebar class='h-100'>
        <div class='rightbar-title d-flex align-items-center px-3 py-4'>

            <h5 class='m-0 me-2'><?= __('设置') ?></h5>

            <a href="javascript:void(0);" class="right-bar-toggle ms-auto">
                <i class="mdi mdi-close noti-icon"></i>
            </a>
        </div>

        <!-- Settings -->
        <hr class='mt-0'/>
        <h6 class='text-center mb-0'><?= __('布局元素') ?></h6>
        <div class='p-4'>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        导航栏
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='data-topbar-light'
                               value='light' <?= ($themeConfig->getThemeConfig('data-topbar') === 'light') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-light'>
                            明亮
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='data-topbar-colored'
                               value='colored' <?= ($themeConfig->getThemeConfig('data-topbar') === 'colored') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-colored'>
                            有色
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-topbar'
                               id='data-topbar-dark'
                               value='dark' <?= ($themeConfig->getThemeConfig('data-topbar') === 'dark') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-topbar-dark'>
                            暗黑
                        </label>
                    </div>
                </div>
            </div>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        侧边栏
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar'
                               id='data-sidebar-light'
                               value='light' <?= ($themeConfig->getThemeConfig('data-sidebar') === 'light') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-light'>
                            明亮
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar'
                               id='data-sidebar-dark'
                               value='dark' <?= ($themeConfig->getThemeConfig('data-sidebar') === 'dark') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-dark'>
                            暗黑
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar-size'
                               id='data-sidebar-size-default'
                               value='' <?= ($themeConfig->getThemeConfig('data-sidebar-size') === '') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-size-default'>
                            默认尺寸
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-sidebar-size'
                               id='data-sidebar-size-small'
                               value='small' <?= ($themeConfig->getThemeConfig('data-sidebar-size') === 'small') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-sidebar-size-small'>
                            小尺寸
                        </label>
                    </div>
                </div>
            </div>
            <div class='mb-3'>
                <div class='mt-4 mt-lg-0'>
                    <h5 class='font-size-14 mb-3'>
                        布局尺寸
                    </h5>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-layout-size'
                               id='data-layout-size-default'
                               value='' <?= ($themeConfig->getThemeConfig('data-layout-size') === '') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-layout-size-default'>
                            默认
                        </label>
                    </div>
                    <div class='form-check form-check-inline'>
                        <input class='form-check-input' type='radio' name='data-layout-size'
                               id='data-layout-size-boxed'
                               value='boxed' <?= ($themeConfig->getThemeConfig('data-layout-size') === 'boxed') ? 'checked' : '' ?>>
                        <label class='form-check-label' for='data-layout-size-boxed'>
                            盒子
                        </label>
                    </div>
                </div>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='data-layout'
                    <?= $themeConfig->getThemeConfig('data-layout') ? 'checked' : '' ?>>
                <label class="form-check-label" for="data-layout"
                       title='"默认无布局：开启后，设置水平布局，关闭后，设置垂直布局"'><?= __('水平布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='data-keep-enlarged'
                    <?= $themeConfig->getThemeConfig('data-keep-enlarged') ? 'checked' : '' ?>>
                <label class="form-check-label" for="data-keep-enlarged"
                       title='"开启后，保持内容最大化"'><?= __('保持最大化') ?></label>
            </div>

            <div class='mb-3'>
                <h5 class='font-size-14 mb-3'>
                    布局类
                </h5>
                <div class='form-check form-check-inline'>
                    <input class='form-check-input' type='radio' name='layout-class'
                           id='layout-class-default'
                           value='' <?= ($themeConfig->getThemeConfig('layout-class') === '') ? 'checked' : '' ?>>
                    <label class='form-check-label' for='layout-class-default'>
                        默认
                    </label>
                </div>
                <div class='form-check form-check-inline'>
                    <input class='form-check-input' type='radio' name='layout-class'
                           id='layout-class-vertical-collpsed'
                           value='vertical-collpsed' <?= ($themeConfig->getThemeConfig('layout-class') === 'vertical-collpsed') ? 'checked' : '' ?>>
                    <label class='form-check-label' for='layout-class-vertical-collpsed'>
                        垂直塌陷
                    </label>
                </div>
            </div>
        </div>
        <hr class="mt-0"/>
        <h6 class='text-center mb-0'><?= __('菜单布局') ?></h6>
        <div class='p-4'>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='light-sidebar'
                    <?= $themeConfig->getThemeConfig('light-sidebar') ? 'checked' : '' ?>>
                <label class="form-check-label" for="light-sidebar"><?= __('菜单明亮') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='topnav'
                    <?= $themeConfig->getThemeConfig('topnav') ? 'checked' : '' ?>>
                <label class="form-check-label" for="topnav"><?= __('页顶菜单') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='icon-sidebar'
                    <?= $themeConfig->getThemeConfig('icon-sidebar') ? 'checked' : '' ?>>
                <label class="form-check-label" for="icon-sidebar"><?= __('图标菜单') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='layouts-compact-sidebar'
                    <?= $themeConfig->getThemeConfig('layouts-compact-sidebar') ? 'checked' : '' ?>>
                <label class="form-check-label" for="layouts-compact-sidebar"><?= __('图文菜单') ?></label>
            </div>
        </div>

        <hr class="mt-0"/>
        <h6 class='text-center mb-0'><?= __('主题布局') ?></h6>
        <div class='p-4'>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='horizontal_menu_top'
                    <?= $themeConfig->getThemeConfig('horizontal_menu_top') ? 'checked' : '' ?>>
                <label class="form-check-label" for="horizontal_menu_top"><?= __('水平菜单置顶') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='boxed'
                    <?= $themeConfig->getThemeConfig('boxed') ? 'checked' : '' ?>>
                <label class="form-check-label" for="boxed"><?= __('紧凑布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='horizontal-boxed'
                    <?= $themeConfig->getThemeConfig('horizontal-boxed') ? 'checked' : '' ?>>
                <label class="form-check-label" for="horizontal-boxed"><?= __('水平紧凑布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='horizontal'
                    <?= $themeConfig->getThemeConfig('horizontal') ? 'checked' : '' ?>>
                <label class="form-check-label" for="horizontal"><?= __('水平布局') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='layouts-hori-topbar-dark'
                    <?= $themeConfig->getThemeConfig('layouts-hori-topbar-dark') ? 'checked' : '' ?>>
                <label class="form-check-label" for="layouts-hori-topbar-dark"><?= __('水平顶黑') ?></label>
            </div>
            <div class='form-check form-switch mb-3'>
                <input class='form-check-input' type='checkbox'
                       id='layouts-hori-boxed-width'
                    <?= $themeConfig->getThemeConfig('layouts-hori-boxed-width') ? 'checked' : '' ?>>
                <label class="form-check-label" for="layouts-hori-boxed-width"><?= __('水平盒子') ?></label>
            </div>
        </div>
        <hr class="mt-0"/>
        <h6 class="text-center mb-0"><?= __('主题颜色') ?></h6>

        <div class="p-4">
            <div class="mb-2">
                <img src="/Weline/Admin/view/statics/assets/images/layouts/layout-1.png?v=66025" class="img-thumbnail"
                     alt="layout-1">
            </div>
            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="checkbox" id="light-mode-switch"
                    <?= $themeConfig->getThemeConfig('light-mode-switch') ? 'checked' : '' ?>>
                <label class="form-check-label" for="light-mode-switch"><?= __('明亮模式') ?></label>
            </div>

            <div class="mb-2">
                <img src="/Weline/Admin/view/statics/assets/images/layouts/layout-2.png?v=76017" class="img-thumbnail"
                     alt="layout-2">
            </div>
            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="checkbox"
                       id="dark-mode-switch" <?= $themeConfig->getThemeConfig('dark-mode-switch') ? 'checked' : '' ?>>
                <label class="form-check-label" for="dark-mode-switch"><?= __('暗黑模式') ?></label>
            </div>

            <div class="mb-2">
                <img src="/Weline/Admin/view/statics/assets/images/layouts/layout-3.png?v=60778" class="img-thumbnail"
                     alt="layout-3">
            </div>
            <div class="form-check form-switch mb-5">
                <input class="form-check-input theme-choice" type="checkbox"
                       id="rtl-mode-switch" <?= $themeConfig->getThemeConfig('rtl-mode-switch') ? 'checked' : '' ?>>
                <label class="form-check-label" for="rtl-mode-switch"><?= __('RTL模式') ?></label>
            </div>
        </div>

    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>

<!-- apexcharts js -->
<script  src='/Weline/Admin/view/statics/assets/libs/apexcharts/apexcharts.min.js?v=21674'></script>

<!-- jquery.vectormap map -->
<script  src='/Weline/Admin/view/statics/assets/libs/jqvmap/jquery.vmap.min.js?v=74666'></script>
<script  src='/Weline/Admin/view/statics/assets/libs/jqvmap/maps/jquery.vmap.usa.js?v=57138'></script>
<script  src='/Weline/Admin/view/statics/assets/libs/jqvmap/maps/jquery.vmap.usa.js?v=57138'></script>

<script  src='/Weline/Admin/view/statics/assets/js/pages/dashboard.init.js?v=28615'></script>
<!--页脚-->
<?php
/**@var \Weline\Framework\View\Template $this*/
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="footer-wapper">
                <?php echo framework_view_process_block([
    0 => 'Weline\\Backend\\Block\\Version',
]);?>
            </div>
        </div>
    </div>
</div>
<!-- end Account pages -->

<!-- JAVASCRIPT -->
<!--<script src="/Weline/Admin/view/statics/assets/libs/jquery/jquery.min.js?v=70688"></script>-->
<script src="/Weline/Admin/view/statics/assets/libs/bootstrap/js/bootstrap.bundle.min.js?v=52832"></script>
<script src="/Weline/Admin/view/statics/assets/libs/metismenu/metisMenu.min.js?v=61832"></script>
<script src="/Weline/Admin/view/statics/assets/libs/simplebar/simplebar.min.js?v=41028"></script>
<script src="/Weline/Admin/view/statics/assets/libs/node-waves/waves.min.js?v=53481"></script>

<script src="/Weline/Admin/view/statics/assets/js/app.js?v=68960"></script>
<!--加载配置页脚-->
<?php
/**@var \Weline\Framework\View\Template $this */
echo $this->getFooter()->getHtml();
?>
</body>
</html>

