<?php
/**
 * 文件信息
 * 作者：邹万才
 * 网名：秋风雁飞(可以百度看看)
 * 网站：www.aiweline.com/bbs.aiweline.com
 * 工具：PhpStorm
 * 日期：2020/7/2
 * 时间：18:05
 * 描述：此文件源码由Aiweline（秋枫雁飞）开发，请勿随意修改源码！
 */

namespace M\Framework\Database;


abstract class Model extends \think\Model
{
    private static DbManager $_db;
    protected static function init()
    {
        self::$db=self::$_db = new DbManager();
//        self::setDb(new DbManager());
        /**
         * 重载方法
         */
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @DESC         |获取数据库基类
     *
     * 参数区：
     *
     * @return \think\DbManager
     */
    function getDb(){
        return self::$db;
    }
}