<?php
/**@var \Weline\Framework\View\Template $this */
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang="en">
<head>
    <?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<meta charset="UTF-8">
<title><?php echo $this->getData('title'); ?></title>
<!--元数据-->
<meta content="<?php echo $this->getData('description'); ?>" name="description"/>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, shrink-to-fit=no'>
<meta content="<?php echo $this->getData('title'); ?>" name='author'/>
<meta content="<?php echo $this->getData('description'); ?>" name='description'/>
<link rel="Shortcut Icon" href="/Weline/Backend/view/statics/img/favicon.png?v=34969">
<link rel="Shortcut Icon" href="/Weline/Backend/view/statics/img/favicon.png?v=34969">
<link rel="Bookmark" href="/Weline/Backend/view/statics/img/favicon.png?v=34969">
<!--加载requirejs-->
<?php if (DEV) : ?>
    <!--        <script src="/Weline/Backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.js?v=23327"></script>-->
<?php
else:
    ?>
    <!--        <script src="/Weline/Backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.min.js?v=30438"></script>-->
<?php
endif;
?>
<!--加载require常用js模块-->
<!--<script src="/Weline/Backend/view/statics/base/require.configs.js?v=28366"></script>-->
<?php echo framework_view_process_block([
    'class' => 'Weline\\Backend\\Block\\Header\\Base',
    'template' => 'Weline_Admin::blocks/header/base.phtml',
]);?>

<!--css-->
<!--loading-->
<link  href='/Weline/Admin/view/statics/libs/loading/loading.css?v=51569' rel="stylesheet" type="text/css"/>
<link  href='/Weline/Admin/view/statics/backend/lib/bootstrap-5.1.3-dist/css/bootstrap.min.css?v=72860' rel="stylesheet" type="text/css"/>
<link  href='/Weline/Admin/view/statics/backend/lib/font-awesome-4.7.0/css/font-awesome.min.css?v=53991' rel="stylesheet" type="text/css"/>
<!-- Bootstrap Css -->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/bootstrap' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet"
      type="text/css"/>
<!-- Icons Css -->
<link  href='/Weline/Admin/view/statics/assets/css/icons.min.css?v=71587' rel="stylesheet" type="text/css"/>
<!-- App Css-->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/app' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet" type="text/css"/>
<!--JS-->
<script  src='/Weline/Backend/view/statics/backend/lib/jquery/3.6.0/jquery.js?v=97068'></script>
<?php if (DEV): ?>
    <!--    <script src="/Weline/Backend/view/statics/backend/lib/jquery/3.6.0/jquery.map?v=46469"></script>-->
<?php endif; ?>
<!--加载配置页头-->
<?php
echo $this->getHeader()->getHtml();
?>

    <title>Weline Admin 登录面板</title>
</head>

<body class="bg-pattern" >
<div class="bg-overlay"></div>
<div class="account-pages my-5 pt-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-4 col-lg-6 col-md-8">
                <div class="card">
                    <div class="card-body p-4">
                        <div class="">
                            <div class="text-center">
                                <a href="../../../../../../../index.html" class="">
                                    <img src="/Weline/Backend/view/statics/img/logo.png?v=38754" alt="" height="24"
                                         class="weline-logo auth-logo logo-dark mx-auto">
                                    <img src="/Weline/Backend/view/statics/img/logo.png?v=38754" alt="" height="24"
                                         class="weline-logo auth-logo logo-light mx-auto">
                                </a>
                            </div>
                            <!-- end row -->
                            <h4 class="font-size-18 text-muted mt-2 text-center"><?= __('欢迎回来！') ?></h4>
                            <p class="mb-5 text-center"><?= __('登录 Weline 管理面板') ?>.</p>
                            <div class='row'>
                                <!--消息-->
                                <?php
echo \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Framework\Manager\MessageManager::class);
?>
                            </div>
                            <form class="form-horizontal" action="<?= $this->getData('post_url') ?>" method="post">
                                <?= $this->getFormKey($this->getData('post_url')) ?>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="mb-4">
                                            <label class="form-label" for="username"><?= __('管理员') ?></label>
                                            <input type="text" class="form-control" id="username" name="username" value="秋枫雁飞"
                                                   placeholder="<?= __('输入管理员') ?>">
                                        </div>
                                        <div class="mb-4">
                                            <label class="form-label" for="userpassword"><?= __('密码') ?></label>
                                            <input type="password" class="form-control" id="userpassword"
                                                   name="password"  value="admin"
                                                   placeholder="<?= __('输入密码') ?>">
                                        </div>
                                        <div class="row">
                                            <?php if ($this->getData('need_backend_verification_code')) {
                                                ?>
                                                <div class="form-group">
                                                    <img src="<?= $this->getData('backend_verification_code_url') ?>"
                                                         alt="">
                                                    <label class="form-control-label"><?= __('验证码：') ?>
                                                        <input name="code" type="text" class="form-control" value=""
                                                               placeholder="<?= __('请输入验证码！') ?>" required>
                                                    </label>
                                                </div>
                                                <?php
                                            } ?>
                                            <?php
echo \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Framework\Manager\MessageManager::class);
?>
                                            <?php
                                            /**@var \Weline\Framework\Session\Session $session */
                                            $session = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Framework\Session\Session::class);
                                            ?>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <div class="form-check">
                                                    <input type="checkbox" class="form-check-input"
                                                           id="customControlInline">
                                                    <label class="form-label" class="form-check-label"
                                                           for="customControlInline"><?= __('记住我') ?></label>
                                                </div>
                                            </div>
                                            <div class="col-7">
                                                <div class="text-md-end mt-3 mt-md-0">
                                                    <a href="auth-recoverpw.html" class="text-muted"><i
                                                                class="mdi mdi-lock"></i> <?= __('忘记密码？') ?></a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="d-grid mt-4">
                                            <button class="btn btn-primary waves-effect waves-light <?php if ($session->getData('backend_disable_login')) echo 'disable' ?>"
                                                    type="submit"><?= __('登 录') ?></button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="mt-5 text-center">
                    <p class="text-white-50"><?= __('还没有账号？') ?> <a href="auth-register.html"
                                                                    class="fw-medium text-primary"> <?= __('注册') ?> </a>
                    </p>
                    <p class="text-white-50">©
                        <script>document.write(new Date().getFullYear())</script>
                        Weline. Crafted with <i class="mdi mdi-heart text-danger"></i> By <a
                                href="https://www.aiweline.com/">秋枫雁飞</a></p>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
</div>
<?php
/**@var \Weline\Framework\View\Template $this*/
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="footer-wapper">
                <?php echo framework_view_process_block([
    0 => 'Weline\\Backend\\Block\\Version',
]);?>
            </div>
        </div>
    </div>
</div>
<!-- end Account pages -->

<!-- JAVASCRIPT -->
<!--<script src="/Weline/Admin/view/statics/assets/libs/jquery/jquery.min.js?v=20468"></script>-->
<script src="/Weline/Admin/view/statics/assets/libs/bootstrap/js/bootstrap.bundle.min.js?v=37511"></script>
<script src="/Weline/Admin/view/statics/assets/libs/metismenu/metisMenu.min.js?v=47242"></script>
<script src="/Weline/Admin/view/statics/assets/libs/simplebar/simplebar.min.js?v=19571"></script>
<script src="/Weline/Admin/view/statics/assets/libs/node-waves/waves.min.js?v=76914"></script>

<script src="/Weline/Admin/view/statics/assets/js/app.js?v=35143"></script>
<!--加载配置页脚-->
<?php
/**@var \Weline\Framework\View\Template $this */
echo $this->getFooter()->getHtml();
?>
</body>
</html>

