<!--
================================================================================================================ 
模板文件：D:\wwwroot\dev-bbs.aiweline.com\app\code\Weline\Frontend\view\templates\public\footer.phtml START
================================================================================================================
 -->
<?php echo framework_view_process_block([
    0 => 'Weline\\Frontend\\Block\\Footer\\Base',
]);?>
<?php
/**@var \Weline\Framework\View\Template $this */
echo $this->getFooter()->getHtml();
?>
</html>
<!--
=============================================================================================================================
模板文件：D:\wwwroot\dev-bbs.aiweline.com\app\code\Weline\Frontend\view\tpl\\en_US\templates\public\com_footer.phtml END
=============================================================================================================================
-->