<header class="navbar navbar-expand-lg navbar-dark bg-dark" id="header">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav" aria-controls="navbar_collapse" aria-expanded="false" aria-label="展开菜单">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand text-truncate" href="https://bbs.aiweline.com/">
            <img src="@static(Aiweline_Bbs::/aiweline.png)" class="logo-2">

        </a>
        <a class="navbar-brand hidden-lg" href="https://bbs.aiweline.com/thread-create-0.htm" aria-label="发表主题"><i class="icon-edit icon"></i></a>
        <div class="collapse navbar-collapse" id="nav">
            <!-- 左侧：版块 -->
            <div class="top-search hidden-lg">
                <div class="form-group">
                    <form action="https://bbs.aiweline.com/search.htm" id="search_form">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" name="keyword">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">搜索</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <ul class="navbar-nav mr-auto hidden">
                <li class="nav-item home active" fid="0" data-active="fid-0"><a class="nav-link" href="https://bbs.aiweline.com/"><i class="icon-home"></i> 首页</a></li>
                <li class="nav-item hidden-lg" fid="1" data-active="fid-1">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-1.htm"><i class="icon-comments d-md-none"></i> Python</a>
                </li>
                <li class="nav-item hidden-lg" fid="2" data-active="fid-2">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-2.htm"><i class="icon-comments d-md-none"></i> PHP</a>
                </li>


                <li class="nav-item hidden-lg" fid="3" data-active="fid-3">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-3.htm"><i class="icon-comments d-md-none"></i> Java</a>
                </li>


                <li class="nav-item hidden-lg" fid="4" data-active="fid-4">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-4.htm"><i class="icon-comments d-md-none"></i> Go</a>
                </li>


                <li class="nav-item hidden-lg" fid="8" data-active="fid-8">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-8.htm"><i class="icon-comments d-md-none"></i> JS</a>
                </li>


                <li class="nav-item hidden-lg" fid="6" data-active="fid-6">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-6.htm"><i class="icon-comments d-md-none"></i> Linux</a>
                </li>


                <li class="nav-item hidden-lg" fid="9" data-active="fid-9">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-9.htm"><i class="icon-comments d-md-none"></i> 数据库</a>
                </li>


                <li class="nav-item hidden-lg" fid="7" data-active="fid-7">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-7.htm"><i class="icon-comments d-md-none"></i> 下载</a>
                </li>


                <li class="nav-item hidden-lg" fid="10" data-active="fid-10">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-10.htm"><i class="icon-comments d-md-none"></i> 新闻</a>
                </li>


                <li class="nav-item hidden-lg" fid="13" data-active="fid-13">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-13.htm"><i class="icon-comments d-md-none"></i> 测试</a>
                </li>


                <li class="nav-item hidden-lg" fid="11" data-active="fid-11">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-11.htm"><i class="icon-comments d-md-none"></i> 闲谈</a>
                </li>


                <li class="nav-item hidden-lg" fid="12" data-active="fid-12">
                    <a class="nav-link" href="https://bbs.aiweline.com/forum-12.htm"><i class="icon-comments d-md-none"></i> 经验</a>
                </li>


            </ul>





            <!-- 右侧：用户 -->
            <ul class="navbar-nav">
                <li class="nav-item usernotice " id="nav-usernotice">
                    <a class="nav-link" href="https://bbs.aiweline.com/my-notice.htm"><i class="icon icon-bell"></i> 消息 <span class="d-none unread badge badge-danger badge-pill" id="nav-usernotice-unread-notices">0</span>
                    </a>
                </li>
                <li class="nav-item hidden-lg">
                    <a class="nav-link" href="https://bbs.aiweline.com/search.htm"><i class="icon-search"></i> 搜索</a>
                </li>
                <li class="nav-item username"><a class="nav-link" href="https://bbs.aiweline.com/my.htm"><img class="avatar-1" src="@static(Aiweline_Bbs::/1.png)"> admin</a></li>
                <!-- 管理员 -->
                <li class="nav-item"><a class="nav-link" href="https://bbs.aiweline.com/admin/"><i class="icon-home"></i> 后台管理</a></li>

                <li class="nav-item"><a class="nav-link" href="https://bbs.aiweline.com/user-logout.htm"><i class="icon-sign-out"></i> 退出</a></li>

            </ul>
            <!-------手机------->



        </div>
    </div>
</header>