<?php
/**
 * @var $this \Weline\Framework\View\Template
 */
?>
<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_TEMPLATE,trim("Weline_Backend::public/header.phtml"));// 读取资源文件 ?>
<link rel="stylesheet" href="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("Weline_Admin::backend/theme/material/css/iot-theme-bundle.min.css"));// 读取资源文件 ?>">
<link rel="stylesheet" href="<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_STATICS,trim("Weline_Admin::backend/theme/material/css/material.css"));// 读取资源文件 ?>">
</head>
<body>
<div class="header-wapper">
    <div>Menu</div>
</div>
<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_TEMPLATE,trim("Weline_Backend::blocks/menu.phtml"));// 读取资源文件 ?>
<script>
    require(['jquery','bootstrapBundle'],function ($,bootstrapBundle){
        alert($(window).width())
    })
</script>
</body>
<?php echo $this->fetchTemplateTagSource(\Weline\Framework\View\Data\DataInterface::dir_type_TEMPLATE,trim("Weline_Backend::public/footer.phtml"));// 读取资源文件 ?>