@template(Weline_Admin::header.phtml)
<?php
/**
 * @var $this \Weline\Framework\View\Template
 */
?>
<link rel="stylesheet" href="@static(Weline_Admin::css/header.css)">
<link rel="stylesheet" href="@static(Weline_Admin::css/index.css)">
<body>
<a href="<?=$this->getUrl('admin/login/logout')?>">退出登录</a>
<script>
    require(['jquery','bootstrapBundle'],function ($,bootstrapBundle){
        console.log('后端Js执行...')
    })
</script>
</body>
@template(Weline_Admin::footer.phtml)