<w:template>Weline_Admin::backend/page-layout/main-content-before.phtml</w:template>
<div class='main-content'>

    <div class='page-content'>
        <div class='container-fluid'>
            <div class='row'>
                <!--消息-->
                <template>Weline_Component::message.phtml</template>
            </div>
            <!--end row-->
            <div class="row">
                <div class='col-lg-12'>
                    <div class='card'>
                        <div class='card-body'>
                            <h4 class='card-title'>路由表</h4>
                            <p class='card-title-desc'>For basic styling—light padding and
                                only horizontal dividers—add the base class <code>.table</code> to any
                                <code>&lt;table&gt;</code>.
                            </p>

                            <div class='table-responsive'>
                                <table class='table mb-0'>
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>First Name</th>
                                        <th>Last Name</th>
                                        <th>Username</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <th scope='row'>1</th>
                                        <td>Mark</td>
                                        <td>Otto</td>
                                        <td>@mdo</td>
                                    </tr>
                                    <tr>
                                        <th scope='row'>2</th>
                                        <td>Jacob</td>
                                        <td>Thornton</td>
                                        <td>@fat</td>
                                    </tr>
                                    <tr>
                                        <th scope='row'>3</th>
                                        <td>Larry</td>
                                        <td>the Bird</td>
                                        <td>@twitter</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <pp>rewrites</pp>
            </div>
        </div>
        <!-- container-fluid -->
    </div>
    <!-- End Page-content -->

    <footer class='footer'>
        <div class='container-fluid'>
            <div class='row'>
                <div class='col-sm-6'>
                    <script>document.write(new Date().getFullYear())</script>
                    © Weline.
                </div>
                <div class='col-sm-6'>
                    <div class='text-sm-end d-none d-sm-block'>
                        Crafted with <i class='mdi mdi-heart text-danger'></i> By <a
                                href='https://www.aiweline.com/'>秋枫雁飞(aiweline)</a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

</div>
<w:template>Weline_Admin::backend/page-layout/main-content-after.phtml</w:template>