<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>欢迎加入 M Framework 的世界! 发现不一样的世界！</title>
    <link rel="Shortcut Icon" href="<?= __STATIC__; ?>/img/favicon.png">
    <link rel="Shortcut Icon" href="<?= __STATIC__; ?>/img/favicon.png">
    <link rel="Bookmark" href="<?= __STATIC__; ?>/img/favicon.png">
    <?php
    /**
     * @var $this \M\Framework\View\Template
     */
    ?>
    <link href="<?= __STATIC__; ?>/css/get.css" type="text/css" rel="stylesheet">
    <script src="<?= __STATIC__ ?>/js/demo.js"></script>
</head>
<?php
//include $this->getViewFile('public/header.phtml');
?>
<body>
<h1>欢迎加入 M Framework 的世界! 发现不一样的世界！</h1>
<div class="img-box"><img src="<?= __STATIC__ ?>/img/logo.png" alt=""></div>
<p class="official-p">开发者：秋枫雁飞&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;论坛：<a href="http://bbs.aiweline.com" target="_blank">bbs.aiweline.com</a>
</p>
<div class="feature">
    <div class="feature-detail">
        <h3>特色：</h3>
        <p>1、功能代码可移植安装。</p>
        <p>2、一个需求一个App应用，一个应用涵盖前后端源码。</p>
        <p>3、无插件等复杂影响性能构建，源码可直接修改。</p>
        <p>4、使用国内TP6 ORM无缝封装，更加符合国人数据库操作习惯。</p>
        <p>5、更加灵活严谨的API开发体验。</p>
    </div>
</div>
<div class="sample">

    <div class="debug">
        <a href="/helloworld/p" target="_blank" onclick="openWindow(this.href,this.text)">调试样式</a>
        <a href="/helloworld/ex" target="_blank" onclick="openWindow(this.href,this.text)">异常调试</a>
        <a href="/helloworld/demo" target="_blank" onclick="openWindow(this.href,this.text)">Demo</a>
        <a href="/helloworld/cache" target="_blank" onclick="openWindow(this.href,this.text)">Cache</a>
        <a href="/helloworld/session" target="_blank" onclick="openWindow(this.href,this.text)">Session</a>
    </div>
</div>
<?php

//include $this->getViewFile('public/footer.phtml');
?>
</body>
</html>
