<!-- end main content-->

</div>
<!-- END layout-wrapper -->

<!--右边栏-->
<w:template>Weline_Admin::common/right-sidebar.phtml</w:template>

<!-- apexcharts js -->
<w:js>Weline_Admin::assets/libs/apexcharts/apexcharts.min.js</w:js>

<!-- jquery.vectormap map -->
<w:js>Weline_Admin::assets/libs/jqvmap/jquery.vmap.min.js</w:js>
<w:js>Weline_Admin::assets/libs/jqvmap/maps/jquery.vmap.usa.js</w:js>
<w:js>Weline_Admin::assets/libs/jqvmap/maps/jquery.vmap.usa.js</w:js>

<w:js>Weline_Admin::assets/js/pages/dashboard.init.js</w:js>
<!--页脚-->
<w:template>Weline_Admin::common/footer.phtml</w:template>
</body>
</html>
